layouts/v7/modules/Users/partials/EditViewContents.tpl
一行に置く入力欄の数を数える際にuitype21をカウントしていなかったので修正
=> ユーザー情報編集画面においてシステム管理者でないユーザーの場合、詳細情報の配置が崩れる問題を修正

modules/Vtiger/views/Basic.php
- 例えば、顧客企業の関連から製品に飛んだ場合、販売管理のカテゴリーのサイドバーになるはずがマーケティングのカテゴリーになる
- 別カテゴリーのモジュールでもマーケティングになる
- リンク先のモジュールが属するカテゴリーのサイドバーが表示されるように修正
- 複数のカテゴリーに属するモジュール(顧客企業など)の場合、左側に表示されるカテゴリーを優先
=> モジュールを関連から遷移した場合、左サイドバーのメニューがMARKETINGのものになる不具合修正

include/ListView/ListViewController.php, layouts/v7/modules/Documents/CreateDocument.tpl, layouts/v7/modules/Vtiger/uitypes/FileLocationType.tpl, modules/Vtiger/models/Field.php, modules/Vtiger/uitypes/DocumentsFileUpload.php
- 外部リンクを保存したときにリストにURLが表示されない
- 詳細画面に表示されるURLがハイパーリンクにならない
ダウンロード種別は内部アップロード・外部リンクともにデフォルトで内部
|        |  ダウンロード種別-内部  |  ダウンロード種別-外部  |
| ---- | ---- | ---- |
|  内部アップロード  |  正常  |  保存時に自動でダウンロード種別-内部に変更  |
|  外部リンク  |  ﾘｽﾄにURLなし・詳細がﾊｲﾊﾟｰﾘﾝｸにならない  |  正常  |
- 「外部リンク」ならダウンロード種別-外部がデフォルトで選択されるように変更
- 外部リンクでダウンロード種別-内部だとリストのファイル名と詳細画面のファイルのURLがハイパーリンクにならない問題を修正
=> ドキュメントの保存・表示を修正

docker/php/Dockerfile, docker/php/php.ini
JPGファイルをアップロードしようとするとエラーが発生する
Fixes #24 
- dockerfileに exif を追加
- php.iniにshort_open_tag=offを追加
=> JPGファイルがアップロードできない問題を修正

layouts/v7/modules/Calendar/AddUserCalendar.tpl, layouts/v7/modules/Calendar/CalendarSharedUsers.tpl, modules/Calendar/models/Module.php
Closes #13
表示するユーザーはすべてマイグループに手動で追加するように変更した。
"visible"は初期値でNULLであり、NULLの"visible"は「カレンダーの追加」で初めて1になり、削除されると0になる。
"visible"が0とNULLのときカレンダーが表示されないように修正
"visible"が0とNULLのときカレンダーが追加できるように修正
ページ遷移せずにページ内でマイグループを表示した際に正常に表示されるように修正
=> 共有カレンダーのマイグループの初期値をすべてのユーザーからcurrentUserのみに変更

layouts/v7/modules/Calendar/uitypes/StatusPickListFieldSearchView.tpl
カレンダーのリスト表示でステータスを絞り込もうとするとTODOと予定の値が一緒に出る
closes #19 
｢(TODO)完了｣、｢(活動)完了｣のように前に種別を表示するように変更
=> カレンダーのリスト表示でステータスを絞り込むとき、ピックリストの値がTODO・予定の区別がつかない問題を修正

layouts/v7/modules/Settings/LayoutEditor/FieldCreate.tpl, layouts/v7/modules/Settings/LayoutEditor/resources/LayoutEditor.js
モジュール設定→項目設定のスイッチが崩れていた・翻訳が入っていなかった
bootstrap-switchのサイズの変更とvtransrateを追加
closes #43
=> #43 項目編集のスイッチの翻訳とスタイルを修正

modules/Migration/schema/731_to_732.php
#28 の修正です。
原因は以下でした。
- uitype53の項目（担当）が、1モジュールに複数あると本Issueのような現象が起きます。
これを回避するために、SQLでvtiger_fieldの該当項目を10に変更し、検索用にtypeofdataも'V~M'or'V~O'となるようなMigrationスクリプトを追加しました。
制約事項として、マイグレーションを動かす必要がありますが、v7.3.2相当のタイミングで動くようにしているので、一度もう動かしているユーザーさんは手動でSQLを実行して貰う必要があります。
=> #28 日報の一覧画面で提出先が検索できない不具合の修正

data/CRMEntity.php, languages/en_us/Vtiger.php, languages/ja_jp/Vtiger.php, layouts/v7/modules/Settings/LayoutEditor/FieldCreate.tpl, layouts/v7/modules/Settings/LayoutEditor/resources/LayoutEditor.js, modules/Settings/LayoutEditor/models/Module.php, resources/styles.css
#32 の課題について、選択肢に表示することと、レポートで表示されなかった問題を合わせて修正
コミットの中に混ぜてますが、 `CRMEntity.php  getReportsUiType10Query() `内の以下のコードについて、
```php
if ($queryPlanner->requireTable($crmentityRelModuleFieldTable, $matrix)) {
// Usersを関連にした場合、vtiger_crmentityをJoinするとレコードがないため、vtiger_usersを一度JOINする
if($rel_mod == "Users"){
// vtiger_crmentityの代わりとして動かすため、
//   - vtiger_users.id as `crmid` として振る舞わせる
//   - deleted = 0となっていた箇所は、vtiger_users.status = 'Active'で判定する
// [TODO] Usersの場合、通常のレコードとは異なり過去のユーザーも見せたいのであれば、この判定は無く必要がある
$relquery.= " LEFT JOIN (select u.*, u.id as `crmid` from vtiger_users u) AS $crmentityRelModuleFieldTable ON $crmentityRelModuleFieldTable.id = $tab_name.$field_name AND vtiger_crmentityRel$module$field_id.status='Active'";
}else{
$relquery.= " LEFT JOIN vtiger_crmentity AS …
```
=> #32 関連項目としてユーザーモジュールを選択できるように修正

modules/Calendar/Activity.php, modules/Calendar/actions/DragDropAjax.php
close #10 
1. 関連に顧客担当者が複数登録された活動を作成する
1. 活動の日時をドラッグして変更する
1. 活動をクリックして編集画面を開く
1. 顧客担当者が消える
ドラッグ&ドロップ時には$_REQUESTに顧客担当者の情報が存在しないので顧客担当者がいないものとして扱われてしまう
* ドラッグ&ドロップ時に$_REQUESTにフラグを追加
* フラグがある場合、顧客担当者を更新しないように修正
=> #10 カレンダーの関連の顧客担当者が編集時に消える問題を修正

layouts/v7/modules/Vtiger/resources/dashboards/Widget.js
close #48 
ダッシュボードのウィジェットのノートで、URLを記入し保存すると ?以降が切り取られてしまう
postのparamsの形式を変更
=> #48 ダッシュボードのウィジェットのノートで、URLを記入し保存すると ?以降が切り取られてしまう不具合を修正

layouts/v7/modules/Vtiger/resources/Vtiger.js
close #33 
#33 参照
上部メニューが開いたときに｢その他｣ボタンのドロップダウンが消えるように変更
=> #33 一覧リストの｢その他｣ボタンを押したあと上部メニューを押すと重なってしまう不具合を修正

docker-compose.yml
mysqlのコンテナは常時起動する設定になっているが、apache+phpのコンテナは常時起動しない設定になっていたため、docker-compose.ymlを変更しました。
=> docker-compose.ymlのPHPコンテナも常時自動起動するような設定に変更

layouts/v7/modules/Calendar/resources/Calendar.js, modules/Calendar/Activity.php, modules/Calendar/RepeatEvents.php, modules/Calendar/actions/DragDropAjax.php, modules/Calendar/views/Edit.php, modules/Events/actions/Save.php
非終日から終日にドラッグした際に開始時刻と終了時刻を0時に設定するように修正。
終日から非終日にドラッグした際に終了時刻を開始時刻から2時間後に設定するように修正。
=> カレンダー画面で終日予定をドラッグすると、終日チェックが外れない件を修正。

resources/styles.css
- fix #83
1. システム設定の画面幅が小さくなるとフィールドラベルが右寄せになる
1.  画面幅が狭まるとラベルとバリューは二段重ねになるが,ラベルのスタイルが右寄せのままであり, #41 の変更の一部がusersに適用されていなかった.
1. 画面幅が830以下ではラベルを左寄せ
usersモジュール
=> #83 システム設定の画面幅が小さくなるとフィールドラベルが右寄せになる不具合を修正

resources/styles.css
- fix #116 
1.  概要画面で関連項目を編集する際,ウィンドウの幅が一定の範囲の場合表示が崩れる
1.  minwidthの設定により,幅が狭まったときにはみ出てしまう
1.  minwidthをautoや100%に変更
summaryView内部
=> #116 概要画面で関連項目を編集する際,ウィンドウの幅が一定の範囲の場合表示が崩れる不具合を修正

modules/Migration/schema/732_to_733.php
fix #99 
```
mysql> mysql> EXPLAIN SELECT reminderid , recordid FROM vtiger_activity_reminder_popup INNER JOIN vtiger_activity on vtiger_activity.activityid = vtiger_activity_reminder_popup.recordid INNER JOIN vtiger_crmentity Or_activity_reminder_popup.recordid = vtiger_crmentity.crmid WHERE vtiger_activity_reminder_popup.status = 0 AND vtiger_crmentity.smownerid = '1' AND vtiger_crmentity.deleted = 0 AND ( ( DATE_FORMAT( vtiger_activity_reminder_popup.date_start , '%Y-%m-%d' ) <= '2021-03-24' ) AND ( TIME_FORMAT( vtiger_activity_reminder_popup.time_start , '%H:%i' ) <= '18:53' ) ) AND vtiger_activity.eventstatus <> 'Held' AND ( vtiger_activity.status <> 'Completed' OR vtiger_activity.status IS NULL ) LIMIT 20;
+----+-------------+--------------------------------+------------+--------+--- …
```
=> #99 activity_reminder_popupの高速化

layouts/v7/modules/Accounts/uitypes/Text.tpl, layouts/v7/modules/Contacts/uitypes/Text.tpl, layouts/v7/modules/PurchaseOrder/uitypes/Text.tpl, layouts/v7/modules/Vtiger/resources/Field.js, layouts/v7/modules/Vtiger/uitypes/Text.tpl
-  詳細項目(uitype=19, 20 fieldname='description', 'terms_conditions'など)が対象
- 編集画面でのheight, widthを変更した
- "詳細"項目の高さをheight : 250px(uitype=21の高さに合わせた)に変更
- "詳細"項目の横幅をmaxwidth : 325pxのcss適用を外す
- 詳細画面でのheight, widthを変更した
- "詳細"項目の高さをheight : 250px(uitype=21の高さに合わせた)に変更
- "詳細"項目の横幅をmaxwidth : 325pxのcss適用を外す
- クイッククリエイト画面でのheight, widthを変更した
- "詳細"項目の高さをheight : 250px(uitype=21の高さに合わせた)に変更
- "詳細"項目の横幅をwidth : 100% に変更
maxwidth : 325pxのcss適用を外すは横幅への影響がない()ためwidthを設定した
- 詳細画面
- 編集画面
- リスト画面
- クイッククリエイト
=> #125 [要望]description項目の編集・個別編集において、縦・横の長さが短くて使いづらい

README.md, docker-compose.yml, docker/php/Dockerfile, docker/php/php.ini
開発を行うにあたって、デバッグツールが無いのは不便だったため追加しました。
docker-compose.yml上では、xdebugは無効に設定しているので、手動で実行設定にしない限りは動きません。
=> docker環境にxdebug3がインストールされるように修正し、README.mdを修正

modules/Vtiger/actions/ExportData.php
「現在のページをエクスポート」の並び順がおかしい
現在のページ以外のデータがエクスポートされる
ソート順が指定されていない場合、'modifiedtime'の降順(デフォルトの並び順)でソートするように修正
=> 現在のページをエクスポートする際にソートしていないと、表示されていないデータが出力されたりデータや並び順がおかしい問題を修正

layouts/v7/modules/Documents/CreateDocument.tpl, layouts/v7/modules/Documents/UploadDocument.tpl, layouts/v7/modules/Documents/resources/Documents.js, resources/styles.css
- fix #140 
1. 画面幅が狭いとき、ドキュメントのアップロードモーダルのレイアウトが崩れる
1. 該当モーダルのdivに対し、直接width要素が指定されていた
1. 該当モーダルのdivからwidth要素を削除
2. 該当モーダルにCSSを適用し、画面幅が狭いときは改行して表示されるよう修正
ドキュメントのアップロードモーダル
外部ドキュメントの登録モーダル
=> fiexd #140 ドキュメントのアップロードモーダルをデバイスの横幅に応じてレイアウトするよう修正

docker-compose.yml, layouts/v7/modules/Install/Step4.tpl, modules/Install/models/Utils.php, modules/Install/views/Index.php
1.  初期インストール時に特定の環境変数が入っている場合に、自動で入力済みの状態にする
インストール時のみ
=> 環境変数にDBのルートユーザーID、PWが入っている場合、インストーラーでの入力をスキップするように修正

layouts/v7/modules/Reports/resources/List.js, resources/styles.css
- fix #114
1. レポートのリスト表示画面で幅を狭くするとフォルダとリストの表示が偏る
2. ドキュメントのリスト表示画面で幅を狭くするとフォルダとリストの表示が偏る
1.  画面幅が狭くなり,サイドバーが上部に移動しても,widthが固定値のままであった
2. レポートのみ,サイドバーのheightがjqueryで固定されていた
1. widthが991px以下のときサイドバーのwidthを100%に変更
2. レポートのサイドバーのheightの固定を解除
- レポート
- ドキュメント
レポートとドキュメントのリスト表示画面
=> #114 レポート及びドキュメントモジュールのリスト表示画面で幅を狭くするとフォルダとリストの表示が偏る不具合を修正

modules/Vtiger/actions/MassPDFExport.php
なし
1. PDFをエクスポートする際にファイル名の頭の企業名が正常に入らない
1. ファイルパスからファイル名を取るbasename関数が正常に働かない
2. 発注モジュールの宛名は顧客企業名でなく発注先名である
1.  ファイル名を連想配列でファイルパスとともに引数に渡すように変更
2. 発注モジュールの場合,発注先名を用いるように変更
- PDFエクスポート機能
- 請求モジュール
- 受注モジュール
- 発注先モジュール
- basename関数が正常に働かないのはsetlocale関数でのロケール設定が正常にできていない可能性あり
=> エクスポートするPDFファイルの企業名が正常に入らない問題を修正

modules/Calendar/CalendarCommon.php
- fix #121 
1. 活動の招待メールに添付されるiCalendarファイルのTIMEZONE設定がZ（UTC）となっている
1. カレンダー等からリクエストを受け取った時点で日時はJSTとなっている
2. ics（iCalendar）ファイル生成時、DTSTART/DTENDの値に1. で受け取った日時にZを付与しており、JSTの日時をUTCとして扱ってしまっていた
1. icsファイル生成時、TIMEZONEの設定を行い、JST（UTC+09:00）としてDTSTART/DTENDを設定するよう「修正
**予定情報**
**icsファイル**
**Outlookインポート画面**
予定の作成、予定の変更時、招待者に送付されるメール
=> fiexd #121 活動の招待メールに添付されるiCalendarファイルのTIMEZONEをUTCからAsia/Tokyoに修正

modules/Calendar/actions/DragDropAjax.php
- fix #160 
1.  ,ドラッグで時間幅を変更すると,カレンダーに紐付けられた顧客担当者が減る
1.  プルリクエスト #55 でドラッグアンドドロップで活動の時間の場所を変更した際に,顧客担当者を更新しないフラグを作ったが,リサイズの際は別の関数で処理していた.
1. リサイズの関数でも顧客担当者を更新しないフラグを作った.
カレンダー画面
=> #160 カレンダーの関連の顧客担当者が時間を変更すると減る問題を修正

layouts/v7/modules/Users/ChangeUsername.tpl, layouts/v7/modules/Users/resources/Detail.js, modules/Users/actions/SaveAjax.php, modules/Users/models/Record.php
「ユーザー名の変更」モーダルから「新しいパスワード」「パスワードの確認」入力欄を削除
- fix #181 
1. ユーザ詳細画面「その他」の「ユーザー名の変更」から変更を行うと、パスワードがエラーで保存が出来ない
1. 新しいパスワード入力欄のJSバリデーションにおいて、new_passwordフィールドの値に対してバリデーションを行うべきところが、new_passwordフィールド要素そのものに対してバリデーションを実施していた
1. ユーザー名の変更時はパスワード入力を求めないよう修正
※パスワード変更は同一画面の「ユーザー名の変更」メニューの直下に存在するため、そちらで対応可能
「ユーザー名の変更」モーダルウィンドウ
=> fiexd #181 「ユーザー名の変更」がパスワードがエラーで保存出来ない

includes/runtime/LanguageHandler.php, languages/ja_jp/Users.php
- fix #183 
1. 「ユーザー名の変更」モーダルの新ユーザー名が翻訳されていない
1. vJSTranslate()経由でgetJSTranslatedString()に渡される引数が常に誤った値となっていた
1. getJSTranslatedString()の引数順を変更し、言語が指定されなかった場合はgetTranslatedString()メソッド同様、自動で言語を取得するよう修正
2. New Usernameの日本語訳を追加
「ユーザー名の変更」モーダルウィンドウ
=> fiexd #183 「ユーザー名の変更」モーダルの新ユーザー名が翻訳されていない

modules/ModComments/models/Record.php
- fix #172 
1.  コメントのサムネイルが表示されない
1.  画像のパスが間違っている(画像の名前がvtiger_attachmentsのstorednameになっていなかった)
1.  nameからパスを生成せず,予め配列に格納されているurlを用いる
コメント機能
=> #172 コメントに自身が設定しているサムネイル画像（プロフィール画像）が表示されない不具合の修正

modules/Reports/ReportRun.php
- fix #192 
1. レポートで日付項目に対して「空である」「空ではない」の条件を指定した際にレコードが正しく出力されない
1. MySQL8の仕様変更に伴うSQLエラー
1. 日付項目に対する「空である」「空ではない」の条件で「=''」「!=''」の条件が付かないように修正
レポートの出力内容、出力件数
なし
=> #192 レポートで日付項目に対して「空である」「空ではない」の条件を指定した際にSQLエラーにならないように修正

modules/Migration/models/Module.php, modules/Migration/schema/733_to_734.php, setup/Setup.php, vtigerversion.php
- fix #194 
1. プロジェクトからプロジェクトタスクを作成すると、関連に自動で入らない
1. 関連用のフィールドが指定されていない
1. インストール時に `vtiger_relatedlists` にfieldidを追加
2. マイグレーションで `vtiger_relatedlists` にfieldidを追加
該当の関連周り
今回の修正で、vtigerversion.phpにv7.3.4を記載しました。
=> fixed #194 プロジェクトからPJマイルストーンを作るときに自動で反映されるように修正

setup/Setup.php
- fix #79
1. （不具合ではないが）初期インストール時にプロジェクトタスクの終了日がクイック作成の項目に入っていない
1. 指定されていない
1. インストール最後に呼ばれるスクリプトに処理を追加
プロジェクトタスクの「終了日」項目のみ
=> fixed #79 プロジェクトタスク「終了日」のクイック作成をデフォルトで有効になるように修正

layouts/v7/modules/Calendar/resources/Calendar.js
- fix #201 
1. カレンダーの00:00を押したときに、終日フラグにチェックが付いてしまっていた
1. 00:00 または 12:00 AMの場合に終日フラグがOnになるように設定していたため
1. 引数として渡ってくるstartDateTime Object内の_ambigTimeプロパティを参照するように修正
※_ambigTimeプロパティは曖昧な時間かどうかの判定を行っており、終日は曖昧な予定として表現されている
カレンダー表示部分をクリックしたとき
カレンダーの予定をクリックして編集画面を表示するとき
=> fixed: #201 カレンダーにて上部終日エリアをクリックした場合に就実フラグが付き、00:00をクリックしてもつかないよう修正

layouts/v7/modules/PDFTemplates/partials/SidebarHeader.tpl
- fix #66 
1. PDFテンプレートを開いたときの左のカテゴリーアイコンが表示されない
1. 誤ったclassが指定されている
1. classの変更
- pdf template表示時のみ
- cssのみ
=> fixed #66 PDFTemplatesでサイドバー上部のカテゴリアイコンが表示されない不具合の修正

layouts/v7/modules/Calendar/TaskManagement.tpl, layouts/v7/modules/Calendar/resources/TaskManagement.js, modules/Calendar/views/TaskManagement.php
- fix #205 
1. 右上のTODOの看板表示画面で、検索条件を入れた後閉じる
2. 二度目の表示のときに、検索条件が保持されない
1. Javascriptで表示時に常に固定の4選択肢が表示されていた
1. セッションに保持しているデータをJS側に渡し、その選択肢を初期取得するように修正
TODOのこの画面のみ
=> fixed #205 TODO表示画面で一度閉じると検索条件が破棄される不具合を修正

layouts/v7/modules/EmailTemplates/ListViewActions.tpl, layouts/v7/modules/PDFTemplates/ListViewActions.tpl, layouts/v7/modules/Vtiger/ListViewActions.tpl
- fix #67 
1. 詳細画面の関連メニューのその他からコメントを表示すると、コメントのアイコンが小さい
1. スタイル指定の記述漏れ
1. style属性の追加
その他からコメントを表示したときのみ
=> fixed #67 その他からコメントを表示するとアイコンが小さくなる不具合の修正

layouts/v7/skins/marketing/style.css
- fix #158 
1. 画面幅が狭いとき(iPhone5/SE等)ドキュメントのアップロードモーダルが崩れる
1. cssでmin-widthが300px、hightが150pxで指定されていた
1. min-widthを265px、padding-bottomを20pxと指定
アップロードモーダルの枠幅
.dragdrop-dottedを適用している箇所
=> #158画面幅が狭いときドキュメントのアップロードモーダルが崩れる箇所の修正

layouts/v7/modules/Vtiger/resources/Detail.js
- fix #179 
> 関連のコメント一覧画面で、コメントの編集を行うときだけ改行が削除されて更新されたように見える
> ※概要画面では発生しない
> `JavaScriptの問題で、返ってきた値の\nを<br>に置換していない。`
layouts/v7/modules/Vtiger/resources/Detail.js:2881 のコードを置換
コメントができるモジュール全て
- [✔] 自らテストを行った
- [✔] 不必要な変更が無い
- [✔] 影響範囲の検討を行った
=> fixed #179 関連画面のコメントを編集した際の改行機能

modules/Accounts/models/Module.php
- fix #234
1. 活動に企業とその企業に関連した担当者を登録すると、企業の概要画面活動一覧が二重に表示される
1. UNIONでつないだQUERYがDistinctできていない
1. 暫定対応ではあるが、同一のCRMIDの場合に表示しない対応とする
顧客企業の概要画面、活動一覧部分
一応暫定対応としますが、LIMIT周りには問題ないはずです（追加取得のときに二重表示されるバグが残っている）
=> fixed: #234 顧客企業の概要画面で、活動が特定条件で重複する不具合の修正

modules/CustomView/CustomView.php, modules/CustomView/models/Record.php
- fix #78 
1, 2, 3はリストのチェックボックスのバグ、4はデフォルトで(ログイン時に)表示されるリストのバグ
1. リストのチェックボックスが複数選択できる
2. 共有リスト作成者がその共有リストをデフォルトに設定した際, 他のユーザーのチェックボックスにも✓が入ってしまう
3. 更新を押さないとチェックボックスの変更が反映されない
4. どのチェックボックスにも✓が入っていなかった場合の挙動がおかしい
1. vtiger_customviewのsetdefault値がリセットされていなかった。
2. 共有リストのsetdefault値が全ユーザーに影響を及ぼしていた
3. **未解決**部分的にリロードすることで解決すると思われる。#230 で登録済み
4. getViewId()でデフォルトのリストを決定しているが、setdefault値で判定していた
1. チェックボックスに✓が入った場合、共有リスト以外のsetdefault値を0にした後、指定のsetdefault値を1にする。
チェックボックスから✓がとられた場合、共有リスト以外のsetdefault値を0にする。
2. vtiger_customviewとvtiger_user_module_preferencesを比較し、ログイン中のユーザーidとDBのuseridが一致する場合に✓を入れる
3. **未解決**
4. 2と同様の変更をgetViewId()に加えた。
リストのチェックボックスとデフォルトのリスト表示
[チェックリスト](https://thinkingreed.sharepoint.com/sites/tr-doc/Shared%20Documents/51_F-RevoCRM/30_%E3%83%86%E3%82%B9%E3%83%88%E4%BB%95%E6%A7%98% …
=> フィルターのデフォルト設定の不具合の修正

layouts/v7/skins/marketing/style.css, resources/styles.css
- fix #161 
1. システム設定画面のホームで画面幅を狭くするとヘッダーがずれて概要の文字が隠れる。
1. ヘッダーの高さが42pxで固定されていた。
1. ヘッダーの高さを自動調節できるようにした。
- [✔] 自らテストを行った
- [✔] 不必要な変更が無い
- [✔] 影響範囲の検討を行った
=> fixed #161 システム設定画面のヘッダー修正

layouts/v7/modules/Vtiger/resources/Vtiger.js, modules/Settings/LayoutEditor/models/Module.php
- fix #123 
1. カスタム項目で関連の活動を作成しても,関連を選択できず保存できない.
1. 関連項目には活動(Events)とTODO(Calendar)が存在するが,vtiger_tabのpresenceにより活動(Events)が無効化されている
2. presenceのチェックを外すとエラーはなくなるが,保存しても表示されない(別のバグ？)
1. vtiger_tabのpresenceを書き換える方法は影響範囲が読めないため,活動(Events)を非表示にし,TODO(Calendar)をカレンダーとして一元化した.(関連としての機能は活動もTODOも保存できるため影響なし)
2. クイック作成はTODOではなく活動を優先し,表示されるようにした.(親要素からカスタム項目を判定)
項目設定画面
編集画面
=> #123 カスタム項目で関連の活動を作成した際に動作しない不具合を修正

include/utils/EditViewUtils.php
- fix #169 
1. 見積の総合計とエクスポートしたPDFファイルの合計金額が1円違うケースが存在する
1. 見積の総合計はvtiger_quotes.totalを参照しており、PDFファイルの合計金額は税引き前の合計と消費税をPDFファイル生成時に加算した値を参照しているため、参照している値に差異が存在する。
2. include/utils/EditViewUtils.phpにおいて消費税額を生成している箇所が五捨六入になっており、PDFファイルの合計金額を生成する処理において、丸め位置の数値が5の場合に切り捨てが発生している。
3. 見積の総合計はvtiger_quotes.totalをnumber_format関数にて丸め処理を行っている。
4. number_format関数は丸め位置において四捨五入が行われるため、丸め位置の値が5の際に切り捨て、切り上げの差異が発生していた。
1. include/utils/EditViewUtils.phpにおいて消費税額を生成している箇所にて丸め位置の数値が5の場合切り捨てを行っている処理を削除し、一律でnumber_format関数で四捨五入するよう修正。
製品の設定を行う画面（見積、請求、受注、発注）
=> fixed #169 見積の合計金額と出力したPDFファイルの合計金額が合うよう修正

layouts/v7/modules/Inventory/resources/Edit.js
- fix #244 
1. 見積などの「項目の設定」から送料を入力しても設定されない
1. 送料を設定するポップアップにおいて、「保存」ボタン押下時のイベント内で送料の算出を行っている。
2. jQuery(element).val()で取得した金額が数値かどうかの判定にNumber.isFinite()を使用している。
3. 取得した金額は"100"のように常に文字列で取得されるため、判定が常にfalseとなり、金額が常に0で上書きされていた。
1. Number.isFinite()ではなく、isNaN()を使用した判定に変更。
製品の設定を行う画面（見積、請求、受注、発注）
=> fixed #244 Inventoryの送料を設定した際、常に0になっていた問題を修正

include/InventoryPDFController.php
- fix #238 [不具合]見積書で入力した調整金額がPDF出力すると合計金額に反映されない。
1. 上記の通り
1. 合計金額算出処理時に調整金額を反映していない
1. include/InventoryPDFController.phpの549行目を追加し、調整金額を取得、550行目の合計処理を修正し、調整金額を反映。
これにより注文請書、請求書、注文書等の同様の問題も修正される
=> fixed #238 見積書をPDF出力すると合計に調整金額が反映されない不具合を修正

modules/Users/models/ListView.php
- fix #239
1. 関連項目でモジュール「ユーザー」を作成する
2. 一般ユーザーでアクセスすると、自身しか選択できない
1. 取得処理が自分のみとなっていた
1. Users_Record_Model::getAccessibleUsers()を使い、ロールベースのアクセス可能なユーザー一覧を取得し、SQLのINで取得するように修正
ListViewのgetQuery()を修正しているので、Usersモジュールに関しては、Popup表示のみの想定です。
=> fixed #239 ユーザー一覧を表示する関連項目のリストに、管理者でない場合は自分のみしか表示されない不具合を修正

layouts/v7/modules/Users/ListViewContents.tpl, resources/styles.css
- fix #290 
1. ユーザー一覧の｢名前とメールアドレス｣の列がズレて表示される
1. ユーザー一覧のユーザーアイコンは｢名前とメールアドレス｣の列の幅によって相対的にdivの幅が決められている
1. スタイルが相対変化しないように修正
ユーザー一覧
=> #290 ユーザー一覧の｢名前とメールアドレス｣の列がズレて表示される不具合を修正

languages/ja_jp/Vtiger.php, layouts/v7/modules/Install/resources/Index.js, layouts/v7/modules/Users/ForgotPassword.tpl, layouts/v7/resources/helper.js
- fix #284 
1. パスワード登録、変更の文字数制限が正常に機能していない
1. checkStrengthPassword()関数内の文字数判定が機能していなかった
1. password.lenght → password.lengthへ
2. パスワード変更成功時の通知の翻訳
3. パスワード変更画面のロゴ修正
パスワード設定/変更時
以下の内容についてテストしました
- ユーザー新規作成時
- 既存ユーザーのパスワード変更
- インストール時
- ログイン画面からパスワード変更時
=> パスワード登録、変更の文字数制限が正常に機能していない箇所の修正

layouts/v7/modules/Calendar/resources/Calendar.js
- fix #198 
1. 共有カレンダーにて参加者が2名以上いる予定をドラッグアンドドロップすると予定表示が2倍になる
1. layouts\v7\modules\Calendar\resources\Calendar.jsのrenderEvents関数と_updateAllOnCalendar関数で,二重にfullCalendarのイベントが登録されている.処理のタイミングで二重に表示されたりされなかったする.
1. _updateAllOnCalendar関数でイベントを一回実行後に削除する.
カレンダー
=> #198 共有カレンダーにて参加者が2名以上いる予定をドラッグアンドドロップすると予定表示が2倍になる不具合を修正

languages/ja_jp/Vtiger.php
- fix #253 
1. すでにあるグループ名を登録すると未翻訳のメッセージが表示される
1. JS_DUPLICATES_EXISTに対応する日本語が用意されていなかった
1. 翻訳を追加した
JS_DUPLICATES_EXISTが適応されている箇所の和訳
=> #253 すでにあるグループ名を登録すると未翻訳のメッセージが表示される箇所の修正

languages/ja_jp/Vtiger.php, layouts/v7/modules/CustomView/resources/CustomView.js
- fix #203 
1. リスト作成時、必須項目を選ばず作成するとエラーメッセージが表示される。このメッセージが未翻訳であった。
1. CustomView.jsのメッセージ作成箇所にvtranslate()関数が使用されていなかった。
1. vtranslate()関数を使用した。
新しいリストを作成する処理
=> #203 リスト作成時のエラーメッセージ翻訳

include/Webservices/VtigerModuleOperation.php
- fix #336
1. Query処理でデータを取得する際、明細行の最終行のデータのみ残っていた。
1. Query処理でデータを取得する際、レコードID毎にデータをまとめていた為に明細行が複数あった場合に最終行のデータのみ残る形となっていた。
1. 明細行のデータを取得する場合、レコードID毎に上書きするのではなく新しい配列データとして追加するように修正。
2. 取得するデータに明細行のデータが含まれていない場合は、今まで通り取得するように修正。
　⇒明細行を除いた項目を取得しようとした場合、同じデータが明細行分取れてしまわないように対応。
見積、受注、発注、請求モジュールをQuery処理で取得する場合。
※Retrieve処理は対象外。
=> fix #336 WebAPIのQuery処理で受注モジュールの明細行が全行取得できるように修正。

include/utils/EditViewUtils.php, languages/ja_jp/Vtiger.php, modules/PDFTemplates/models/Module.php
- fix #335
1. PDFテンプレーtト編集画面より､｢明細行番号｣が選択できるように修正。
2. 明細魚番号を選択した際、$[モジュール名]-sequence_no$の文言が設定されるように修正。
3. $[モジュール名]-sequence_no$の箇所に明細行の行番号が表示されるように修正。
=> fix #335 PDFテンプレートモジュールにて、各明細の行番号が表示できるように修正。

include/Webservices/VtigerCRMObjectMeta.php
- fix #351 
1. APIの「describe」 でモジュールの詳細を取得した際に項目の並び順が画面上の並び順と異なる。
1. フィールド取得時のクエリに order by が指定されていない
1. include/Webservices/VtigerCRMObjectMeta.php#retrieveMetaForBlock
vtiger_blocksもJOINして、ブロック順、フィールド順でorder byを指定する。
API全般（モジュールの詳細取得は至る所で使われているため、API全体が影響範囲となる）
- [] 自らテストを行った
- [] 不必要な変更が無い
=> #351 APIでモジュールの詳細を取得した際の項目の並び順がバラバラ

layouts/v7/modules/Vtiger/resources/validation.js
- fix #346 
1. 金額フィールドでマイナスの値を登録できない
1. バリデーションで弾いている
2. データベース的にはINT型なので問題ない
1. validation.jsにて該当のコードを削除
2. 表示確認
3. CSVエクスポート
4. レポート出力
5. Excel・CSV出力
金額フィールド全体に影響があります。
=> fixed #346 金額フィールドでマイナス値を登録できるように修正

include/InventoryPDFController.php
- fix #342 
1. 明細行のテキストエリア内の改行がPDFに反映されない。
1. 改行記号をそのままHTMLとして出力していた為、改行として認識されていなかった。
1. 改行記号を<br>に変換するように修正。
受注、発注、見積、請求モジュールにて、テキストエリア項目で且つ改行を入力している場合。
=> fix #342 PDFテンプレートで作成されたPDFの明細行に、テキストエリアで入力された改行が反映されない件を修正

modules/Vtiger/actions/MassPDFExport.php
一括エクスポート時のクエリにて、項目名だけではなくテーブル名も合わせて指定するように修正。
- fix #344
1. PDFファイル一括エクスポート時、zipファイルの中身が空となる場合がある
1. PDFファイル一括エクスポート時のクエリにてテーブル名を指定していない箇所があり、テーブル名は異なるが同じカラム名の項目が複数存在する場合に、クエリエラーが発生していた。
1. PDFファイル一括エクスポート時のクエリにてテーブル名を指定して処理を実行するように修正。
見積、受注、請求、発注モジュールにてPDF一括エクスポートを行う場合。
=> fix #344 PDFファイル一括エクスポート時、zipファイルの中身が空となる場合がある件の修正。

modules/Import/actions/Data.php
- fix #310 
1. 10001件以上のデータをインポートすると途中でエラーがでる
1. modules\Import\models\Config.phpの**immediateImportLimit**(デフォルト値:1000)を超えるとインポートは一度に行われずcron処理される.さらに,同ファイルの**importPagingLimit**(デフォルト値:10000)を超えるとページング処理されて複数回のcronで処理されるはずがうまく働いていない.
1. 未完了のインポートがvtiger_import_(ユーザーID)に残っている場合,vtiger_import_queueを消さずに残すように修正
2. vtiger_import_queueが残っている場合,importPagingLimitで止まっているのか前の実行が継続中かどうか判定するように修正
全モジュールのインポート
レコード数が多いCSVをインポートする際に,PHPの制限でデフォルトでは2MB以上のファイルをアップロードできないため,php.iniのupload_max_filesizeの上限を引き上げてApacheを再起動する必要あり(8MBより引き上げたい場合はpost_max_sizeなども変更が必要)
=> #310 多数のデータをインポートする際の不具合を修正

layouts/v7/modules/Accounts/DetailViewHeaderTitle.tpl, layouts/v7/modules/Contacts/DetailViewHeaderTitle.tpl, layouts/v7/modules/HelpDesk/DetailViewHeaderTitle.tpl, layouts/v7/modules/Invoice/DetailViewHeaderTitle.tpl, layouts/v7/modules/Leads/DetailViewHeaderTitle.tpl, layouts/v7/modules/Potentials/DetailViewHeaderTitle.tpl, layouts/v7/modules/Products/DetailViewHeaderTitle.tpl, layouts/v7/modules/PurchaseOrder/DetailViewHeaderTitle.tpl, layouts/v7/modules/Quotes/DetailViewHeaderTitle.tpl, layouts/v7/modules/SalesOrder/DetailViewHeaderTitle.tpl, layouts/v7/modules/Vendors/DetailViewHeaderTitle.tpl, layouts/v7/modules/Vtiger/DetailViewHeaderTitle.tpl, modules/Vtiger/models/Module.php, modules/Vtiger/views/Detail.php, resources/styles.css
- fix #295 
- merge #53 のコミットで発生した不具合
詳細画面のアイコンの背景色が消えている
背景色透明化のcss(.Read_BG_clear)を、
ユーザーが画像を追加した場合にのみ適応したかったが、それ以外の場合にも適応されてしまっていた。
1. Read_BG_clearの削除
2. ユーザーが画像を追加した場合、背景色をwhiteで上書きする
- デフォルトアイコン
- 背景透過されている画像を追加した場合
モジュール詳細画面のアイコン背景色
=> [WIP]背景透明化のcssがデフォルトのアイコンにも適応されてしまっていたので修正

layouts/v7/modules/Users/DetailViewBlockView.tpl, layouts/v7/modules/Vtiger/DetailViewBlockView.tpl, resources/styles.css
かならず内部的にはtd4カラム構成になるように、高さ0のtdを追加する
- fix #153 
1. uitype19だけのBlockの場合、横長のテキストエリアが左に寄ってしまう。
1. uitype19だけの場合、trの中身はtd2つのみの要素になる
2. ただし、上部にuitype1などの要素がある場合は、そのtrがtd4つの要素になるため、左による
1. block内のtableの最初の行に、高さ0のtd4つ分の要素を追加するようにした
Block表示全体
=> fixed #153 2列分の表示項目がセンター寄せされる不具合の修正

include/utils/EditViewUtils.php, include/utils/InventoryUtils.php, languages/ja_jp/Vtiger.php, layouts/v7/modules/Inventory/LineItemsDetail.tpl, layouts/v7/modules/Inventory/partials/LineItemsContent.tpl, layouts/v7/modules/Inventory/resources/Edit.js, layouts/v7/modules/Vtiger/PopupContents.tpl, modules/Inventory/actions/GetTaxes.php, modules/Migration/models/Module.php, modules/Migration/schema/734_to_735.php, modules/Vtiger/actions/GetData.php, vtigerversion.php
PDFテンプレートで $invoice-usageunit$ を利用する必要がある
作業中です、サービスを紐付けた時に正常に単位が出ない不具合が残っています。
その他、サービスに関係する処理がテストできていません。
- fix #237 
1. PDFテンプレートで製品の単位を利用できるようにする
1. 製品の単位を見えるように修正
Inventory関係のモジュール全体に影響
- [] 自らテストを行った
サービスを請求などに紐付けたときの処理がまだ完成していないため、WIPとする。
=> fixed: #237 見積書、発注書などに単位を表示できるように修正

modules/Migration/schema/734_to_735.php
- fix #377
1. 請求,受注,発注,見積に関連した活動を関連のリストから作成できない
1. 該当モジュールの｢予定の登録｣ボタンのURLにparent_idがないため自動で親モジュールが選択されない
2. 親フィールド(関連元)と活動が1対多で紐づく場合のみparent_idを付与する
2. 親フィールド(関連元)と活動はrelationtypeが1対多で紐づくはずが,該当モジュールでは多対多で登録されている
1. vtiger_relatedlistsの該当フィールドの値を更新
before
after
請求,受注,発注,見積,日報モジュール
=> #377 請求,受注,発注,見積に関連した活動を関連のリストから作成できない不具合を修正

modules/PriceBooks/PriceBooks.php
- fix #381 
1. 価格表モジュールが、レポートの「関連」として指定している時に起きる
2. 価格表モジュールでレポートを出力する際に、新規作成フィールドを扱うとエラーになる
1. generateReportsSecQueryにて、`vtiger_pricebookcf` をJOINしていなかったため。
1. vtiger_pricebookcfを追加するように修正
価格表のレポート周り
本修正を行ったとしても、集計を行う際には価格表モジュールのフィールドを1つ以上、カラムとして指定する必要がある。
根本的な問題については、#357（v7.3.6） にて対応予定となります。
=> fixed #381 価格表モジュールでレポートを出力する際に、新規作成フィールドを扱うとエラーになる不具合の修正

modules/Import/actions/Data.php, modules/Import/readers/FileReader.php
- fix #401 
1. 活動のインポート時、管理画面から追加した項目があるとインポートに失敗する
1. インポート時、仮テーブルを生成する際に、対象モジュールのカラム一覧を取得している。
2. そのカラム一覧から、インポート設定の画面で設定したフィールドをピックアップし、仮テーブルのカラムとしている。
3. その際、活動の場合だけ管理画面から追加したcf_xxxの形のフィールドが取得できていなかった。
1. カレンダーの場合は別ルートでカラム一覧を取得するように修正。
インポート機能
=> fixed #401 活動のインポート時、項目設定から追加した項目が含まれていてもインポートできるように修正

modules/CustomView/models/Record.php
- fix #384 
1. 共有リストで「すべて」がフィルター名をソートした場所になる
2. 「すべて」は一番上にきてほしい
1. ソートの結果順だから
1. array_shiftを使って「All」の場合は先頭にする
- 個人リストには影響なし
- フィルターの表示順関係すべての並び順
=> fixed #384 共有リストではAll（すべて）が先頭に来るように修正

modules/Reports/ReportRun.php
- fix #404 
1. サービスモジュールに関連フィールドを追加するとレポートが表示されない
1. サービスモジュールのレポートクエリ生成時、CRMEntity::getReportsUiType10Query()が呼び出されておらず、必要なテーブルがJOINされていなかった
1. ReportRunQueryPlanner::getReportsQuery()にServicesモジュール用の分岐を追加し、CRMEntity::getReportsUiType10Query()を呼び出すように追加した。
サービスモジュールを含めたレポート
=> fixed #404 サービスモジュールのレポートクエリ生成時、UiType10Queryを呼び出すように修正

modules/Settings/Vtiger/models/OutgoingServer.php
- fix #410 
1. 送信メールサーバーを設定した際に送られる確認用メールを英語から日本語に変更。
1. outgoingServer.phpファイル内の送信するメール文を修正
=> #410　送信メールサーバーを設定した際に送られるメールの本文が英語になっている

modules/Reports/ReportRun.php
- fix #414 
1. 価格表モジュールに関連のフィールドを項目追加し、レポートにそのフィールドを表示すると、件数だけが表示され、表が表示されなくなる。
1. 価格表モジュールのレポートクエリ生成時、CRMEntity::getReportsUiType10Query()が呼び出されておらず、必要なテーブルがJOINされていなかった
1. ReportRunQueryPlanner::getReportsQuery()にPriceBooksモジュール用の分岐を追加し、CRMEntity::getReportsUiType10Query()を呼び出すように追加した。
価格表モジュールを含めたレポート
#404 同様のため、分岐を追加
=> fixed #414 価格表モジュールのレポートクエリ生成時、UiType10Queryを呼び出すように修正

modules/Migration/schema/735_to_736.php, vtlib/Vtiger/FieldBasic.php
- fix #371 
1. 過去に生成された関連項目(uitype10)にindexが付与されない
1. 735_to_736のマイグレーションファイルにindexを付与する修正を追加
- 顧客企業に関連項目を追加した後、マイグレーション実行したケース
- vtiger_fieldmodulerelに紐づけられたテーブルのindex
=> #371 マイグレーションでINDEXが効いていないuitype10(関連項目)にINDEXを追加する修正

layouts/v7/modules/Users/ListViewContents.tpl
- fix #363 
1. ユーザー一覧の罫線が一部消えることがある
1. タグの位置が他のリストと異なっていた
=> fixed #363 ユーザー一覧の罫線を正常に表示させる

layouts/v7/modules/Settings/LayoutEditor/FieldsList.tpl, layouts/v7/modules/Settings/LayoutEditor/resources/LayoutEditor.js, layouts/v7/skins/marketing/style.css
- fix #315 
1. 項目の並び順を変更する際、左の列と右の列が独立していたため移動後の並び順が不自然であった
1. 奇数番目は左の列(sortable1)、奇数番目は右の列(sortable2)に分かれていた
1. sortable1とsortable2を結合し、sortable2は削除した
2. 「新しい項目の追加」の項目がsortable1の一番最後になるように修正
- 変更前(顧客担当者IDを先頭(左上)に移動する。姓→名→勤務先電話番号→顧客担当者IDの順)
- 変更後(顧客担当者ID→姓→名→勤務先電話番号の順に並び直されている)
項目設定の項目順番および新規追加項目の挙動
=> 項目の並び順変更時の挙動を変えたい箇所の修正

modules/Vtiger/models/ListView.php
- fix #266
1. 一覧画面で他のモジュールの項目によるソートが利かない
1. ソートするカラム名(関連の場合記号を含む)をサニタイズするgetForSql関数によって値が消えていた.
1. 単純なget関数で記述するように変更
全モジュールの一覧表示
カラム名のサニタイズを省略したが,これ以降のクエリを生成する前に整形されているのでセキュリティ上の問題は生じないと考えられる.
=> #266 一覧画面で他のモジュールの項目によるソートが利かない不具合を修正

modules/Settings/Workflows/actions/SaveWorkflow.php
- fix #370 
1. ワークフロー新規作成・保存後の画面遷移で、フィルタが解除されて「全て　ワークフロー」になってしまう
1. 編集の場合はヘッダーのreturnSourceModuleに遷移前のフィルターモジュールが記録されるが,上部の新規追加のボタンはsettingsの共通部分なので値が入らない
1. returnSourceModuleがない場合は保存するモジュールにがフィルターされたリストに遷移するように変更
ワークフロー
- モジュールのフィルターなし状態で保存した際にフィルターあり状態にするか,フィルターなし状態するかは微妙だが,現状フィルターありになる
=> #370 ワークフロー新規作成・保存後の遷移を対象モジュールのフィルターがかかったリストになるように修正

modules/Accounts/models/Module.php
- fix #440
1. 顧客企業モジュールでのみ非公開の活動の詳細内容が権限のないユーザーで閲覧可能となっている。
1. 顧客企業モジュールのみ`getCalendarActivities`関数の配列`$visibleFields`に`'description'`が含まれているため、非公開であっても詳細内容が表示される
1. 配列`$visibleFields`から`'description'`を削除
顧客企業の詳細表示
- 関連のリストビューでは`modules\Vtiger\models\RelationListView.php`の`getEntries`関数でカレンダーを取得している
- `getCalendarActivities`関数をoverrideしている主要モジュールは顧客企業と顧客担当者のみ
=> #440 顧客企業の概要画面で非公開の活動の「詳細内容」が確認できてしまう問題を修正

modules/Import/actions/Data.php, modules/Vtiger/actions/ExportData.php
再フォークにより#265 を再投稿
- fix #249 
1. カスタムフィールドの関連ユーザーをエクスポートすると全く異なるモジュールのデータが出力される.
2. カスタムフィールドの関連ユーザーを正常にインポートできない
1. 一般のモジュールのidはcrmidとして通しで振られているが,userモジュールのidは含まれていない.
しかし,インポート時にフィールド名からモジュールを逆引きする際には常にcrmidを参照している.
2. 関連ユーザーをインポートする際に,値が空であった場合は常に現在のユーザーの値が入る.
1. カスタムフィールドのユーザーをエクスポート・インポートする際にはフィールド名→モジュールの逆引きを独自のものに変更
2. インポート時に関連ユーザーは必須項目以外は値の空を維持するように変更
* インポート
* エクスポート
- クエリの実行が増加するので,インポート・エクスポートの数が多い際にパフォーマンスに影響する可能性あり.
- 同姓同名の場合はuseridが若い方が当たる(仕様)
=> #249 関連のユーザーをエクスポート・インポートした際に生じる問題を修正

resources/styles.css
- fix #389 
1. 各モジュールの一覧画面を開いたとき、先頭項目の区切り線が一部消えているものがある。
1. `transform: scale(0.999)`で表の要素を微妙に縮小していたため
1. 縮小を外し、行ごとに`margin-bottom`で線を引くように変更
=> #389 一覧画面で一部の区切り線が消える不具合を修正

modules/Documents/models/EditRecordStructure.php
- fix #149 
1. ドキュメントモジュールの編集画面にて、メモやバージョンに記入されていた**0**が表示されない
1. データの有無の判定に`if ($fieldValue)`が使用されていたため、値が**0**だとif文を通り抜けてしまう。
1. 文字列の長さで判定するように変更した
- ドキュメントの編集画面
=> #149 半角で数字0を入力し保存した場合、編集画面で0の値が表示されずに空となっている箇所の修正

vtlib/Vtiger/Functions.php
- fix #391 
1. ポータルの初期パスワードが簡単な英数で生成されてしまう。
1. 小文字と数字のみで生成されていた。
1. パスワードの生成に用いる文字の選択肢に大文字を追加した。
generateRandomPasswordを用いてパスワードを生成する範囲に影響が想定される。
=> #391 ポータルの初期パスワードが簡単な英数で生成される問題の修正

layouts/v7/modules/Calendar/ListViewRecordActions.tpl
- fix #362 
1. カレンダーのリストビューにおいて、｢次の予定を登録する｣アイコンがステータス(TODO)がリストに含まれる場合のみでしか表示されない。
1. テンプレートファイルでアイコンの表示を制御する際に、表示するリストからステータスを取得しているため、リストにステータスがない場合、たとえステータスが｢完了｣でも｢次の予定を登録する｣アイコンが表示されない
1. レコードIDからステータスを取得し、ステータスがリストに無い場合でも表示できるように修正
カレンダーのリスト表示
- リストビューの｢ステータス｣には内部的に｢ステータス(活動)｣と｢ステータス(TODO)｣が存在する
- ｢ステータス(活動)｣は活動のステータスのみを表示する
- ｢ステータス(TODO)｣は活動とTODO両方のステータスを表示する
=> #362 カレンダーのリストビューにおいて｢次の予定を登録する｣アイコンが表示されなくなる不具合を修正

modules/Users/Users.php
- fix #474 
1. ユーザーをインポートするとカレンダー設定のタイムゾーンがSamoaになる
2. 日付形式がdd-mm-yyyyになる
各テーブルの先頭の要素が設定されていた。
空である場合の値を設定した。
- タイムゾーン
- スクリプト中の日付
- 日付形式
- yyyy-mm-dd
ユーザー登録時の処理
- インポート時、正常に動作するかどうか→ok
- TZが設定されていても正常に動作するか→ok
- 日付形式が設定されていても正常に動作するか→ok
- TZ, 日付形式が設定されていても正常に動作するか→ok
- 今回の修正ではタイムゾーンと日付形式のみの対応となっている。添付画像のように**英語表記**になってしまうバグも存在する
- 本来はデータベース(vtiger_field)のデフォルト値を参照すべきであるが、どちらのカラムも空であったためphp側で設定した
=> #474 ユーザーをインポートするとカレンダー設定のタイムゾーンがSamoaになる箇所の修正

config.template.php, languages/ja_jp/Vtiger.php, modules/Settings/LayoutEditor/actions/Field.php
- fix #424
1. カスタムフィールドを無制限に追加できるため、DB側の許容量を超過する
1. カスタムフィールドの上限数が存在しない
1. モジュールあたり200個をデフォルトのカスタムフィールド上限に設定
2. config.inc.php (config.template.php)に上限数のグローバル変数`$custom_field_limit`を追加
3. ` $custom_field_limit`を超過した場合カスタムフィールドの追加がエラーとなるように修正
カスタムフィールド関連、全モジュール
- config.inc.phpはインストール時に生成されるため、既存の環境では自ら`$custom_field_limit = 200;`を追加する必要あり
- `$custom_field_limit`が設定されていない環境では修正を適用しても上限は適用されずに追加可能
- インストール時に`$custom_field_limit = 200;`が生成されることは確認済み
=> #424 カスタムフィールドを追加する上限を設定できるように修正

layouts/v7/modules/Calendar/ModuleHeader.tpl
- fix #307 
1. ウィンドウの横幅が1000ｐx前後のとき,カレンダーの詳細編集画面で｢カスタマイズ｣タブの位置がずれる.
1. ウィンドウを小さくしたときにヘッダーの領域の大きさが足りず、表示が乱れていた。
1. 「カスタマイズ」などがあるヘッダーの領域を大きくした。
カレンダーのヘッダーの表示に関する範囲
=> #307 カレンダーの詳細編集画面での一部表示の乱れを修正

layouts/v7/modules/Vtiger/resources/Field.js
- fix #393
1. フィールドエディタで「選択肢(単数)」のデフォルト値で｢オプションの選択｣が2つ表示される
**英語を前提として条件文が書かれていたため**
- picklistの選択肢はサーバー側(`modules\Settings\LayoutEditor\models\Field.php`)とクライアント側(`layouts\v7\modules\Vtiger\resources\Field.js`)で制御されている
- サーバー側で`オプションの選択`が追加された場合はクライアント側で`オプションの選択`は追加しない仕様
- サーバー側で`オプションの選択`が追加されているかは`'Select an Option'`の有無で判定している
- `'Select an Option'`はサーバー側で翻訳されて`オプションの選択`となっていたため判定が漏れていた
1. 翻訳を適用
設定のフィールドエディタ
=> #393 カスタム項目「選択肢(単数)」のデフォルト値表示の不具合を修正

modules/Inventory/models/Record.php
- fix #518 
1. 見積印刷時に下部に線が入ってしまう
1. ページ・フッターが表示されてしまっていた
1. ページ・フッターを出力しないように修正
以下のPDF出力に影響があります。
- 発注書
- 注文請書
- 請求書
- 見積書
=> #518 見積印刷時に下部に線が入ってしまう箇所の修正

layouts/v7/modules/Settings/LayoutEditor/resources/LayoutEditor.js
- fix #350 
1. 「関連」項目から他の項目に変更すると、デフォルト値の入力欄が消える
2. 「チェックボックス」項目から他の項目に変更すると、デフォルト値の入力欄に0が表示される
3. 「選択肢(複数)」項目から他の項目に変更すると、デフォルト値の入力欄にnullが表示される
1. 関連項目から変更した際に追加したクラスを外す処理がなかった
2. 「チェックボックス」と「選択肢(複数)」項目に変更した際にはデフォルト値が設定される
1. 関連項目以外ではクラスを追加するように変更(他の項目はすべてデフォルト値が設定可能なため)
2. 変更前の項目データを用意し、これが「チェックボックス」or「選択肢(複数)」の場合はデフォルト値を""(空)にするように修正
- カスタム項目の作成
=> 項目追加時に項目タイプを何回か切り替えると、デフォルト値の表示がおかしくなる箇所の修正

modules/com_vtiger_workflow/VTSimpleTemplate.inc
- fix #515 
1. ワークフローから複数選択肢の項目を含むメールを送信すると「選択肢１ |##| 選択肢２」のように送信される。
1. 「;」で分割する処理しか無かった。(「;」で分割した後、選択肢を和訳し「;」で結合して送信)
1. 「 |##| 」で分割する処理を追加。
- 選択肢「a、b、c、d」の場合
- ワークフローによるメール送信
=> #515 WEBフォームから取り込まれた複数選択肢の区切り記号の修正

modules/Migration/schema/735_to_736.php, modules/Settings/LayoutEditor/models/Module.php
- fix #472
1. デフォルトのメールアドレス項目は100字、カスタムフィールドのメールアドレス項目は50字までしか登録できない。
1. MySQLでuitypeがメールアドレスのフィールドは型が`varchar(100)`または`varchar(50)`となっている
2. RFC準拠のメールアドレスは256字まで存在する
1. uitypeが13または104のフィールドを探し、`varchar(256)`とするスクリプトを記述
2. カスタムフィールドでメールアドレス項目を作成する際のデフォルトを`varchar(256)`とした
カスタムフィールド以外では
* 顧客企業
* リード
* 顧客担当者
* 発注先
* ユーザー
にデフォルトのメールアドレス項目が存在
* メールアドレスは基本的にuitype=13であるが、ユーザーモジュールの必須のメールアドレスのみuitype=104となっている
=> #472 メールアドレス項目が途中で切れて保存される不具合を修正

languages/ja_jp/Vtiger.php, libraries/jquery/multiplefileupload/jquery_MultiFile.js
- fix #480
1. 同じファイルを選択した際に出る警告が英語
1. 言語ファイルとvtranslateの追加
- 製品の編集
- コメント
=> #480 同じファイルを選択した際の警告の翻訳漏れを修正

layouts/v7/modules/Vtiger/resources/Edit.js, layouts/v7/modules/Vtiger/resources/Vtiger.js, layouts/v7/modules/Vtiger/uitypes/Date.tpl, layouts/v7/modules/Vtiger/uitypes/Reference.tpl, layouts/v7/modules/Vtiger/uitypes/Time.tpl
- fix #498 
1. 登録/編集画面で入力を行い、関連項目の追加ボタン→詳細入力と進み、「戻る」ボタンや「キャンセル」ボタンで戻った際、一部のフィールドは編集していた内容が残り、一部のフィールドは編集していた内容が消えるといった状態となっていた。
1. ヒストリバックで編集画面に戻った際、画面描画時にJSで初期化しているフィールドについてはブラウザが復元したデータが削除されてしまっている。
1. 特定のフィールド（単数選択肢、複数選択肢、担当）について、編集画面を開いた際にchangeトリガを発火させることで編集中だった内容を復元
3. 特定のフィールド（関連、日付、時刻）について、編集時にchangeトリガを元にデータを保持し、ヒストリバックで戻ってきた際に保持していたデータを書き戻すように修正
登録/編集画面
ヒストリバック時の編集フォームの復元はブラウザの仕様によるため、ブラウザの更新によって動作しなくなる可能性がある。
=> fixed #498 登録/編集画面から別画面に遷移し、history.backで戻った際に一部のフィールドだけ入力中の値がクリアされていたのでリストアされるよう修正

layouts/v7/modules/CustomView/EditView.tpl
- fix #503 
1. リスト作成時の項目選択に関連モジュール名がなく、わかりずらかった
1. 
1. 選択肢を「uitype10の項目名(モジュール名)-項目名」に表示を修正した。
リスト作成時の項目選択の範囲
=> #503 リスト作成時の項目選択にモジュール名を表示する修正

modules/com_vtiger_workflow/tasks/VTEmailTask.inc
- fix #452 
- ワークフローで送信されるメールにて、プレーンテキスト部分のマルチバイト文字が欠落している
- プレーンテキスト作成時、ASCIIに変換する処理が入っていた。プレーンテキストの生成処理は以下の通り
1. HTMLメールからタグを取り除き、`<body>～</body>`部分を抽出する
2. ASCIIへ変換する
3. トラッキングURLへ変換
- ASCIIへ変換する処理を削除
- 日本語を含むURL
- htmlで装飾した日本語文字列
- ワークフローにて送信されるメール(プレーンテキスト)
=> #452 F-RevoCRMのワークフロー機能にて送信されるメールにて、TEXT形式部分のマルチバイト文字が欠落している箇所の修正

includes/http/Request.php, layouts/v7/modules/Calendar/QuickCreate.tpl, layouts/v7/modules/Calendar/resources/Calendar.js, layouts/v7/modules/Vtiger/EditView.tpl, layouts/v7/modules/Vtiger/resources/Vtiger.js, modules/Calendar/actions/Save.php, modules/Calendar/models/Module.php
- fix #387 
1.  カレンダー上から詳細入力を行ったあとの戻り先は対象レコードの詳細画面となる
1. URLSearchParamsにlastRecordDateとして変更したレコード開始日時を保持し,その日が含まれるデフォルトカレンダーを表示
カレンダー
・URLSearchParamsに日付が入った状態で詳細入力→キャンセルするとhistory.back()によりその日付に戻ってしまう
・historyを書き換える処理が必要かもしれない
=> #387 カレンダー上から詳細入力を行ったあとの戻り先が遷移元のカレンダーとなるように修正

layouts/v7/modules/Settings/Workflows/CreateEntity.tpl, layouts/v7/modules/Settings/Workflows/Tasks/VTUpdateFieldsTask.tpl, modules/Vtiger/models/Field.php
- fix #312 
1. ワークフローを追加する
2. アクションで｢レコードの作成｣か｢項目の値の更新｣を追加する
3. 項目の追加でメールアドレスを追加する
4. 値に表現式を保存する
5. 表現式がrawテキストとして保存されてしまう
1. おそらく型がemailなのでバリデーションがかかっているため
1.  型をstringに変更
ワークフロー
* `getFieldInfoForWfEditTask()` の変更は `getFieldInfo()` に例外を追加したのみ
* コミット d844b7e はチェリーピック
=> #312 ワークフローで｢レコードの作成｣,｢項目の値の更新｣を行う際に,フィールドタイプがメールアドレスだと,値を常にrawテキストとしてしまう不具合を修正

layouts/v7/modules/Vtiger/resources/Detail.js
- fix #328 
- pullrequest #529 
1. 関連モジュールの場所に表示されるコメントの削除ができない問題を修正
1. 概要画面のコメント部分と関連モジュールのコメント部分はHTML構成が異なるにも関わらず、同一のセレクタを適用して削除後の再読み込みを行おうとしていたためエラーが起きていた。
1. 関連モジュールの場合、再読み込みでなくjqueryのremove()で該当レコードの表示を削除するようにした。
全モジュールのコメント欄
=> #328 関連モジュール表示でコメントの削除ができない問題を修正

layouts/v7/modules/Calendar/resources/Calendar.js, layouts/v7/modules/Vtiger/partials/Topbar.tpl
- fix #326 
1. カレンダーにおいてリロードをしてしまうと表示している日付が今日に戻ってしまう。
1. defaultdateが今日になっているため。
1. defaultdateとdefaultviewを今見ている日付と表示に毎回更新するようにした。
fullcalendarの範囲。
#387 のissueとコンフリクトが起きそう
=> #326 カレンダーにてリロードした際に閲覧していた日付を表示する

includes/main/WebUI.php, layouts/v7/modules/Calendar/resources/Calendar.js
- fix #326 
1. ホーム画面のカレンダーにユーザー設定したデフォルト表示が反映されていない
1. ホーム画面へのリンクにViewtypeやviewの情報が入っていなかった。
1. ホーム画面へのリンクにlastViewDate=defaultを追加した。
2. day表示から個人カレンダーや共有カレンダーに遷移した時に表示形式を保持するように修正した。
カレンダーの表示の範囲。
=> #326 ホーム画面をカレンダーに設定したときにデフォルト表示になるように修正

include/InventoryPDFController.php, libraries/tcpdf/tcpdf.php, modules/Migration/schema/736_to_737.php
- fix #577 
1. 画像を添付した場合、PDFが出力されないもしくは出力されたPDFに画像が添付されてない
1. 画像ファイルのデコードに失敗していた
2. preg_split()にて検索結果が多いため、処理落ちしていた
3. 大きな画像ファイルを張り付けた場合、DBのカラムサイズの上限に引っかかっていた
1. base64のデコード処理を追加
2. preg_split()前にimgタグを置換する
3. DBのカラム型をtextからlongtextへ変更する(7.3.6→7.3.7のマイグレーション)
- PDFテンプレートのプレビュー表示
- PDFテンプレートの出力
=> #577 PDFテンプレートに画像をコピー＆ペーストで貼り付けると、PDFが出力されない箇所の修正

layouts/v7/modules/Reports/resources/Edit2.js, layouts/v7/modules/Reports/step2.tpl
- fix #556 
1. レポートの項目選択の最大数を25個から60個に拡張したい。
1. 最大選択数が25個に設定されていた。
1. レポートの最大選択数'LBL_MAX'を60に変更した。
#
レポートに記載される結果の増加
=> #556 レポートの項目選択の最大数を60に拡張

layouts/v7/modules/Settings/Vtiger/ListViewContents.tpl
- fix #490 
1. 文語変更において翻訳する文字の一覧のリストにも文語の翻訳がかかってしまい変更前の文字が何だったのかわからなくなってしまう。
1. リスト内の変更前の文字にも翻訳がかかってしまっていた。
1. vtranslateによる翻訳を解除した。
2. 翻訳の解除はリスト内だけだのでリストの項目名などはそのまま翻訳される。
文語変更におけるリスト内
=> #490 文語変更において変更する箇所のリストまで変更されてしまう

layouts/v7/modules/Users/resources/List.js
- fix #597 
1. ユーザー一覧画面から「ユーザー名の変更」をすることができない。
「ユーザー名の変更」を選択するとポップアップは表示されるが、保存を押しても保存されない（保存を押せない）。
1. 「ユーザー名の変更」を押したときに呼び出される関数Settings_Users_List_Js.triggerChangeUsernameによって動かされる関数triggerChangeUsernameと関数ChangeUsernameの中に不要な文が混ざっており、正しく動作しなかった。
1. 関数triggerChangeUsernameと関数ChangeUsernameの不要な文を削除した
ユーザー一覧画面からユーザー名を変更するときのみ
=> #597 ユーザー一覧画面から「ユーザー名の変更」ができない。

layouts/v7/modules/Vtiger/dashboards/MiniListContents.tpl, resources/styles.css
- fix #639 
1. ダッシュボードのミニリストにて、5つの項目を選択するとレイアウトが崩れる
1. Bootstrapのグリッドを使用しているため、5等分レイアウトが作成できない
※項目は6項目までしか選べないため、5項目選択した場合にのみレイアウトが崩れる
1. Bootstrapのグリッドではなく、`display:flex`で分割する
* デスクトップPC
* スマホ/タブレット ※縦並びになる
- ダッシュボード>ミニリスト
=> #639 ダッシュボードのミニリストのレイアウトが崩れる箇所の修正

languages/ja_jp/Settings/Vtiger.php, layouts/v7/modules/Settings/Vtiger/CustomRecordNumbering.tpl, modules/Settings/Vtiger/views/CustomRecordNumbering.php
- fix #622 
1. レコード番号設定画面に「レコード番号」と「モジュール番号」が混在している。
ややこしい為、文言を統一してほしい
1. レコード番号設定画面のページタイトルと見出しに「モジュール番号」という文言を呼び出している。
1. 辞書に「レコード番号」を追加し、レコード番号設定画面のページタイトルと見出しで呼び出すように変更した。
変更前
変更後
「モジュール番号」を呼び出している画面はレコード番号設定画面のタイトルと見出しのみであったため、影響範囲はレコード番号設定画面のみだと考えられる。
=> #622 レコード番号設定画面の文言を統一してほしい

modules/Users/views/Login.php
- fix #573 
1. ログイントップ画面でのRSS取得処理においてFatalエラーが起きたときに、ログインできない可能性があった。
1. Exceptionによって例外をキャッチしていたが、これだとerrorが投げられた場合にキャッチすることができなかった。
1. Exceptionではなくthrowableでキャッチすることにより、すべてをキャッチするようにした。
下記のFatalエラーはExceptionだとキャッチできなかった。Throwableだとキャッチできた。
ログイン時のRSS取得処理の例外処理部分。
=> #573 ログイントップ画面でのFatalエラーに対応する修正

layouts/v7/lib/jquery/select2/select2.css
- fix #587 
1. 必須項目の選択肢項目がバリデーションエラーになった際に、デフォルトで設定されている選択肢はピンク色になるが、システム設定から追加した選択肢の背景色が白になる。デフォルトの無色（=empty(color)）の場合はtplかmodelクラスの中で白（#ffffff）にしてほしい。
1. デフォルトの選択肢に背景色が登録されておらず、空だったため、選択肢がピンク色になっていた
1.  layouts/v7/lib/jquery/select2 の「select2.css」にて背景色を白（#ffffff）で追加した
変更前（案件）
[![スクリーンショット (4)](https://user-images.githubusercontent.com/107910164/182521788-9af877db-6692-4bf8-9361-ea2c63a84fac.png)](url)
変更後（案件）
[![選択肢のバリデーションエラー時の配色がおかしい1](https://user-images.githubusercontent.com/107910164/182521608-c66a0e4b-bc35-479b-8a63-7143a966305b.png)](url)
変更後（資産・レンタル管理）
[![選択肢のバリデーションエラー時の配色がおかしい2](https://user-images.githubusercontent.com/107910164/182521661-a2cc6ab5-7520-4476-a21f-6658feff98d3.png)](url)
その他の「資産・レンタル管理」「見積」等の必須選択項目画面
=> 選択肢のバリデーションエラー時の配色がおかしい

layouts/v7/modules/Settings/Workflows/resources/List.js
- fix #635 
1. ワークフロー一覧表にて、モジュール名が長いワークフローを選択するとワークフロー件数が表示されない
1. ワークフロー名と件数バッジが一つのタグとして処理されていたため、名前が長くなり検索ボックスの枠を超えてしまうとバッジも省略されてしまっていた。
1. ワークフロー名とワークフロー件数バッジを別のタグに分け、ワークフロー名が一定の長さを超えると省略されるようにし、件数バッジを表示させる枠を確保した。
ワークフロー名が長いとき
ワークフロー名が短いとき
ワークフロー設定画面のワークフロー一覧表のみ
=> #635 モジュール名が長いとワークフローの件数が表示されない

layouts/v7/modules/Settings/Webforms/resources/Edit.js
- fix #146 
1. webフォームの一部項目の×ボタンが表示されない。
1. その項目が必須項目であった場合に×ボタンを表示させないようにするモジュールにおいて、判別方法が必須項目の文字列を含むかどうかになっていた。
1.  モジュールの判別方法を完全一致に変更した。
webフォームにおいてそれぞれの項目が必須項目かどうかを判断する箇所。
=> #146 webフォームの項目に×が表示されない問題の修正

include/utils/UserInfoUtil.php, layouts/v7/modules/Calendar/resources/Calendar.js, layouts/v7/modules/Vtiger/RelatedList.tpl, modules/Accounts/Accounts.php, modules/Accounts/models/Module.php, modules/Calendar/models/ListView.php, modules/Contacts/Contacts.php, modules/Contacts/models/Module.php, modules/Dailyreports/models/Module.php, modules/Dailyreports/models/RelationListView.php, modules/Reports/ReportRun.php, modules/Vtiger/models/Module.php, modules/Vtiger/models/RelationListView.php
- fix #631 
1. カレンダー画面にて活動のポップアップを表示した際、非公開として登録した予定の内容が表示されている。
1. そもそもカレンダー画面にて活動のポップアップを表示した際に、非公開として登録した場合に予定の内容を非表示にする条件が書かれていなかった。
1. 非公開として登録した予定については内容を非表示にするよう条件を追加。
カレンダー
（管理者権限であっても非表示になっている）
=> refs #631 カレンダー画面で非公開として登録した予定が表示される件を修正

modules/Migration/schema/736_to_737.php
- fix #578 
1.  Excelファイルをアップロードした時に、vtiger_notesのfiletypeの桁数が足りていなかった。
1. vtiger_notesのfiletypeの型がvarchar(50)になっていた。
1. migrationを使ってvtiger_notesのfiletypeの型をvarchar(255)とした。
fileをアップロードした際など、vtiger_notesを参照、書き込みする箇所。
MIMEタイプの桁数を明確に定めているところはありませんでした。
以下にMIMEタイプの一覧が載っていますが、その中だと一番長いもので84でした。現状で言うならばfiletypeの桁数は100でも足りるかもしれません。
https://www.iana.org/assignments/media-types/media-types.xhtml
=> #578 vtiger_notesのfiletypeの桁数を増やす修正

layouts/v7/modules/Calendar/resources/Calendar.js, modules/Calendar/actions/DeleteAjax.php, modules/Calendar/actions/Feed.php, modules/Calendar/actions/SaveAjax.php, modules/Calendar/actions/SaveFollowupAjax.php
- fix #354 
1. プロジェクトタスクをカレンダー上のポップアップから完了にできるようにしたい。
1. feed.phpに予定があるかどうかのリクエストをする際に、プロジェクトタスクのstatus情報を返してもらえるように修正
2. プロジェクトタスクのstatusがCompletedでない時に完了ボタンが表示されるように修正
3. 完了ボタンが押されたときにプロジェクトタスクのstatusが完了になるように修正
・完了にするボタンをクリックしたときの処理。
・カレンダーに表示する予定がプロジェクトタスクの場合の処理を追記したためその付近の範囲
=> #354 プロジェクトタスクをカレンダー上のポップアップから完了にできるようにする修正

modules/Contacts/models/RelationListView.php
- fix #536
1. 顧客担当者概要画面からチケット作成を行った際に、担当者に紐づく顧客企業を自動的に登録してほしい
1. 顧客担当者詳細画面からチケット作成の際、リクエストURLにparent_idが含まれていなかった。
1. 顧客担当者に関連する顧客企業idをURLに追加
顧客担当者->チケット(HelpDesk)作成・詳細入力画面
=> #536 顧客担当者概要画面からチケット作成を行った際に、担当者に紐づく顧客企業を自動的に登録する

layouts/v7/modules/Calendar/QuickCreate.tpl
- fix #507 
1. スマートフォンから活動のクイック編集を開くとスクロールした際に表示が崩れてしまう。
1. クイック編集のいずれかの項目を選択してしまうとoverflowのスクロールが適用されなくなってしまう。
1. 親クラスのほうにoverflowの条件を追加した。
クイック編集の表示の範囲。
Androidを用いて修正の確認を行ったためiosによる確認はできていない。
=> #507 スマートフォンから活動のクイック編集を開くと表示が崩れる

languages/ja_jp/Vtiger.php
- fix #501 
カレンダーの繰り返しの日付選択画面において翻訳漏れがあった。
1. 翻訳を追加した。
=> #501 カレンダーの繰り返しの日付選択画面の翻訳漏れ

modules/CustomView/models/Record.php
- fix #495 
1. リストに選択した項目名をリスト作成時と異なるものに変更してしまうと、編集・複製時該当項目が引き継がれず表示されない
1. vtiger_cvcolumnlistに各リストの項目が登録されており、このテーブルが変更されないため
1. vtiger_cvcolumnlistの情報とvtiger_fieldの情報を比較し、vtiger_fieldのfieldlabelを優先するようにする
2. クエリを何度も送信しないようにデータをキャッシュする
- リスト編集画面
- 各モジュールの一覧画面
- これは標準の機能ではないため、DBを直接書き換えることによって修正・テストを行いました。
=> リスト作成後に項目名を変更した項目もリストの編集・複製時に引き継がれるようにしてほしい箇所の修正

layouts/v7/modules/Settings/Vtiger/ListViewContents.tpl, layouts/v7/skins/marketing/style.css
- fix #489 
1. 文語変更の編集や削除を行うと不要なスクロールバーが表示される。
1. 編集を行った後にjavascriptによって追加されるはずのクラスがうまく追加されていなかった。
1. cssを新しく書きなおした。
今回はjavascriptのクラスの追加の部分が特定できなかったためcssを新しく書くことで対応した。
javascriptのほうを修正すれば文語変更以外のモジュールで同様のバグが発生しても対応できると思われる。
=> #489 文語変更の編集を行うと現れるスクロールバーのスタイルの修正

modules/Settings/LayoutEditor/actions/Field.php
- fix #486 
1. 複数選択肢の項目を編集するとデフォルト値が削除される
1. デフォルト値が配列要素として格納されていた
1. 配列要素を" |##| "により連結する
- uitype33の項目の保存
=> #486 複数選択肢の項目を編集するとデフォルト値が削除される箇所の修正

layouts/v7/skins/contact/style.css, layouts/v7/skins/inventory/style.css, layouts/v7/skins/marketing/style.css, layouts/v7/skins/marketing_and_sales/style.css, layouts/v7/skins/project/style.css, layouts/v7/skins/sales/style.css, layouts/v7/skins/support/style.css, layouts/v7/skins/tools/style.css, layouts/v7/skins/vtiger/style.less
- fix #455 
1. 画面左上のモジュール名のフォントの大きさが一部乱れていた。
1. cssのフォントサイズが間違っていた。
1. cssのmodule-titleの部分を修正。
すべてのモジュールのヘッダー部分の範囲。
=> #455 モジュール名の表示の乱れを修正

modules/Vtiger/actions/ExportData.php
- fix #652 
1. 参照権限のユーザーでログインしている場合、CSVをエクスポートできない。
1. 権限の処理時に一括編集の権限を記しているVtiger_Mass_Actionを継承しており、それにより権限の設定不具合が生じていたため。
1. ![2022-10-03 (12)](https://user-images.githubusercontent.com/112600172/193542837-1e7b7c22-e771-49ea-9e0a-293f89e55ddd.png)
$permissions = parent::requiresPermission($request);をコメントアウトし、$permissions[] = array('module_parameter' => 'module', 'action' => 'DetailView');を追加。
CSVのエクスポート
=> #652 参照権限のみのユーザーでCSVエクスポートができない問題を修正

include/QueryGenerator/QueryGenerator.php, languages/en_us/Vtiger.php, languages/ja_jp/Vtiger.php, layouts/v7/modules/Vtiger/resources/AdvanceFilter.js, modules/Reports/ReportRun.php, modules/Vtiger/models/Field.php
- fix #551 
1. レポートおよびリストの条件にて、「担当」に対し「自分」が設定できなかった
1. 項目が用意されていない
1. FilterOptionにown(自分)を追加
- レポートおよびリストの条件
- レポート
- 「担当-自分」の条件が機能するか
- 共有レポートとして機能するか
- リスト
- 「担当-自分」の条件が機能するか
- 共有リストとして機能するか
=> #551 リスト（フィルタ）、レポートの条件で「担当」項目に対して「自分」が設定可能にする修正

layouts/v7/modules/Import/resources/Import.js
- fix #552 
1. インポートでマージを選択した際に必須項目を選択しないとインポートすることができなかった。
任意項目をマッチング項目に選択しマージしたい時などに不便だった。
1. 重複レコードの処理にマージを選択した時だけ、必須項目を選択していなくてもエラーにならないように修正。
インポートのマージの範囲
マッチング項目に任意項目を選択し、マッピング項目に必須項目を選択しなかったときにデータが新規作成されるときは必須項目は????でデータが作成される。このときマッチング項目に選択した任意項目はインポート元のcsvファイルの値ではなく新規作成した時に割り振られる値が設定される。
またカレンダーのインポートに関しては修正にかかわらず正しく動作していなかった。今回のissueとは関係ないため修正していません。
=> #552 インポートでマージを選択した際に必須項目を選択しなくてもインポートできるようにする修正

data/VTEntityDelta.php, modules/com_vtiger_workflow/VTJsonCondition.inc
- fix #646 
1. ワークフローの複数選択肢条件が機能していない 
1. 複数選択肢の一致は他項目の一致と異なる処理のはずだが区別されていなかった
例) 複数選択肢が「あ」「い」「う」の3つある場合で「等しい」条件
条件値 : あ,い,う
入力値 : あ,う,い
→ワークフロー結果 : falise
1. 複数選択肢で使用するすべての条件に対して別処理を追加
- ワークフロー条件
=> #646 ワークフローの複数選択肢条件が機能していない箇所の修正

layouts/v7/modules/Reports/Step1.tpl, layouts/v7/modules/Reports/resources/Edit1.js
- fix #555
1. レポートの関連モジュールの数を2個から4個に変更したい。
1. レポートの関連モジュールの最大選択数が2に設定されている。
1.  レポートの関連モジュールの最大選択数を4に変更する。
レポート結果の表示量の増加。
=> #555 レポートの副モジュールの最大選択数の拡張

layouts/v7/modules/Calendar/resources/Calendar.js
- fix #538 
1. 活動の複製を行うときにクイック作成画面でEnterキーを連打すると複数活動が複製されてしまっていた。
1. 活動をアップデートする関数内でsaveButtonのdisableを解除してから活動の保存を行っていたが、その後にdisableを付け足されていなかった。
1. 活動を複製した最後にsaveButtonにdisable属性を付与した。
カレンダーの活動の保存編集複製の範囲。
編集時になぜdisableを解除していたのかがわからなかった。
テストは一通り行ったがdisableをつけると動かない箇所があるのかもしれない。
=> #538 活動を複製するときにEnterキーを連打すると活動が複数作成される問題を修正

include/utils/EditViewUtils.php, layouts/v7/modules/Inventory/partials/LineItemsEdit.tpl, layouts/v7/modules/Inventory/resources/Edit.js
- fix #625 
1. 請求書を作成するときに「項目の詳細」で消費税を「個別」に変更してPDF出力すると、「小計」に合計が入り、「消費税」に合計に消費税率をかけた金額が入ってしまう。
1. 請求書作成・編集画面で保存した段階で、消費税が「個別」のときに合計が入っている変数(hdnSubTotal)（「グループ」の時には小計が入っている）を、小計(subTotal)に反映していた。
2. 請求書に反映される消費税の値が、消費税の種類（個別・グループ）に関係なく一律で計算された値になっていたため、値がおかしくなっていた。
1. 請求書作成・編集画面で保存した段階で、消費税の種類に関係なく小計(subTotal)に小計(pre_tax_total)を代入するように変更した。
2. 消費税が「個別」の請求書を作成するときには、「消費税」に入る値を計算しなおすように変更した。
3. 消費税を「個別」に変更した時点で、値引きは各製品項目にて行うようにし、合計金額から値引きは行えないように変更した。
変更後の請求書編集画面（個別・グループ）
変更後の請求書（個別・グループ）
請求書作成・編集画面
PDF出力した請求書
=> #625 消費税が「個別」の請求書を出力すると、値がおかしくなる 

layouts/v7/modules/Settings/Webforms/ShowForm.tpl, layouts/v7/modules/Settings/Webforms/resources/Detail.js
- fix #92 
1. Webフォームの「Webフォームを表示する」を選択すると表示されるソースコードが一行で表示されるため、内容が確認しずらい
1. smartyのstripタグの影響でpreタグ内の改行や空白が削除されてしまっていた
1. stripタグの範囲を変更
2. インデントの調整
3. 改行の追加
「Webフォームを表示」の範囲
=> #92 Webフォームのソースコードの表示機能を見やすくなるよう修正

layouts/v7/modules/Reports/RelatedFields.tpl, layouts/v7/modules/Reports/step2.tpl, layouts/v7/skins/contact/style.css, layouts/v7/skins/inventory/style.css, layouts/v7/skins/marketing/style.css, layouts/v7/skins/marketing_and_sales/style.css, layouts/v7/skins/project/style.css, layouts/v7/skins/sales/style.css, layouts/v7/skins/support/style.css, layouts/v7/skins/tools/style.css
- fix #569
1. レポートで画面サイズを小さくすると表示が崩れてしまう。
1. レイアウトの設定がうまくいっていなかった。
2. classの設定ミスで選択ボックスの高さにずれがあった。
1. classとstyleの設定を変更した。
変更箇所と同ページの表示
=> #569 レポートで画面サイズを縮小した時に、表示が崩れるバグを修正

layouts/v7/modules/Settings/LayoutEditor/FieldCreate.tpl, modules/Settings/LayoutEditor/models/Module.php
- fix #562 
1. カスタム項目の「関連」がテキストとして保存される。
2. 活動をカスタム項目の関連として登録した時に、その項目を編集すると権限エラーが発生する。
1. テキストとして保存されていることに対して
　関連として保存はされていた。変数の比較の部分（下記参照）が左辺ではReration、右辺ではReferenceが入ってきていた。
　RerationもReferenceも変換すると「関連」になる。
2.登録した項目を編集すると権限エラーが発生することに対して
　利用用途が少ないため関連項目から「活動」と「カレンダー」を選べないようにした。
　
1. テキストとして保存されていることに対して
　ReferenceとRerationを比較した時は選択肢をselectedにするようにした。
　変数に代入する箇所をRerationかReferenceのどちらかに合わせる方法もあったが、ここ以外でも両方が混ざって使われていたため、このような修正にした。
2. 登録した項目を編集すると権限エラーが発生することに対して
　利用用途が少ないため関連項目から「活動」と「カレンダー」を選べないようにした。
全てのモジュールのカスタム項目の範囲
テキストとして保存されていることに対しての修正で、RerationかReferenceのどちらかに合わせて変数に代入するよう修正したほうがいい場合はコメントください。
=> #562 カスタム項目において関連を選択した時に「関連」として保存されるようにする修正

layouts/v7/modules/Vtiger/BreadCrumbs.tpl, layouts/v7/skins/marketing/style.css
- fix #138 
1. レポート作成画面において画面幅が狭いときに改行されてしまい、綺麗に表示されなかった。
1. インライン要素に設定されているため通常時は正しく表示されるのだが、画面の幅が狭くなると領域が足りず改行されてしまう。
1. 強制的に横に並ぶように一つの要素で括り、関数を適用して横並びになるようにした。
レポート追加の範囲のみ
CSSファイルに.header_workflowという変数を作ったため、この先この名前の変数を用いる
=> #138 レポート作成画面において画面幅が狭いときの一部表示の乱れを修正

layouts/v7/modules/Calendar/CalendarSettings.tpl
- fix #579  
1. カレンダーの設定画面を開いたときに、画面の幅を狭めると「カレンダー共有」の表示が崩れる。
1. グリッド幅の指定にミスがあった。
1. カレンダー共有ラベルのグリッド幅指定を変更した。
[
](url)
カレンダー設定の画面
=> カレンダー設定を開いたときに、画面の幅が狭いとカレンダー共有の表示が崩れる。

layouts/v7/modules/Vtiger/resources/List.js, layouts/v7/modules/Vtiger/resources/Vtiger.js, modules/Vtiger/helpers/Util.php
- fix #281 
1. 一括編集にて複数選択肢の変更が保存されない
2. 一括編集にて関連項目のチェックボックスが変更後に✓されない
3. クイック作成にて複数選択肢が保存されない
4. カレンダー/TODOのクイック作成にて複数選択肢が保存されない
1. multipicklsitの場合、"cf_980"ではなく"cf_980[]"の値を参照する必要があった(cf_980はフィールド名)
2. キーワードを入力する場合、フィールド名から"_display"を削除する必要があった。選択肢から選択する場合、選択肢の保存画面にてチェックボックスに✓を入れる処理する必要があった
- キーワードを入力する場合
- 選択肢から選択する場合
3. validateFieldValue()内の編集可能な変数(editablePicklistValues)の条件が誤っていた
4. 3と同様
1. "cf_980"ではなく"cf_980[]"の値を参照するようにした
2. _displayの削除と、チェックボックスに✓を入れる処理を追加した
3. $fieldValueを$valueに変更した(4も同様)
=> 一括編集にて複数選択肢の編集が反映されない箇所の修正

layouts/v7/modules/Calendar/resources/Edit.js
- fix #195 
1. カレンダーの繰り返し予定を編集し、保存するときに警告文が表示されてしまう。
1. 保存する際にブラウザ側が画面遷移として自動で警告をつけてしまっていた。
1. 繰り返し予定の変更のいずれかをクリックした際にブラウザの警告を無効にするように修正した。
=> #195 繰り返し予定の編集を保存する際に出る警告文の修正

languages/ja_jp/Settings/MenuEditor.php, layouts/v7/modules/Settings/MenuEditor/AddModule.tpl
- fix #458 
1. メニュー設定において「非表示のモジュールを選択」を選択したときに一部不必要な文字の省略があった。
1. 省略に設定されているタグの横幅がおかしかった。
1. 関係するタグの横幅を調整した。
メニュー設定における「非表示のモジュールを選択」を選択した際の表示に関する範囲。
=> #458「非表示のモジュールを選択」を選択したときの表示の乱れの修正

layouts/v7/modules/Settings/MenuEditor/Index.tpl
- fix #461 
1. ウィンドウの横幅が特定の幅になったときにメニュー設定においてマーケティングのアイコンの表示の位置がおかしい。
1. cssにてposition:relativeに設定されていたが、relativeの基準となる位置がほかのタグと被ってしまっていたため。
1. relativeの基準がうまくいくようにタグの範囲を直した。
システム構成>メニュー設定の範囲。
=> #461 メニュー設定においてのモジュールアイコンの表示位置の修正

modules/Users/Users.php
- fix #477 
1. インポートしたユーザーのデフォルトの言語が英語である
2. vtiger_fieldテーブル内のタイムゾーン、日付形式にデフォルト値が設定されていない
1. php側でインポートしたデータが空の場合、英語になるように記述されていた
1. 設定値を英語から日本語に変更
ユーザーインポート時の処理
- 本来はデフォルト値をvtiger_fieldから参照するべきであるが、すべての項目にそれを適応して良いのかわからないので今回はphp側での設定で解決とする
=> #477 インポートしたユーザーのデフォルトの言語を日本語にする修正

layouts/v7/modules/Settings/Workflows/EditView.tpl
- fix #450
1. ワークフローを作成する際に選択できるモジュールはTODOと活動で別れているが、保存したあとはカレンダーと活動になり見分けづらい
1. ｢Calendar｣の翻訳は｢カレンダー｣だが、｢Single_Calendar｣の翻訳は｢TODO｣であり食い違っている
1. ｢Single_XXX｣の形に統一
before
after
ワークフロー
コミットメッセージは不正確
=> #450 ワークフローのモジュール選択時は活動とTODOにもかかわらず、保存後は活動とカレンダーとなる不具合を修正

layouts/v7/modules/Vtiger/DetailViewTagList.tpl, layouts/v7/modules/Vtiger/Tag.tpl, layouts/v7/modules/Vtiger/partials/SidebarEssentials.tpl, layouts/v7/modules/Vtiger/resources/Tag.js, resources/styles.css
- fix #369 
1. タグのポップアップで出てくる編集画面に作成者の表示がないため、作成者の名前を表示してほしい。
1. 作成者を表示する機能がなかったため。
1. タグに紐づいているowner情報を作成者として表示した。
タグの一覧が表示されるモジュールすべて
=> refs #369 タグの所有者をわかるように修正

config.template.php
- fix #629 
1. 初回インストール時にメールの「クリック数カウント」がオフになっているので、初回インストール時オンに修正
1. 初回インストール時にメールの「クリック数カウント」がオフになっている
1. config.template.phpに初期インストール時オンを追加
config.inc.php
=> refs #629 初期設定でメールの「クリック数」のカウントをオン

modules/Calendar/actions/SaveFollowupAjax.php
- fix #456 
1. 完了済みのTODOの「次の予定を登録する」のアイコンからTODOを新規作成すると完了状態で新規作成されてしまう。
1. 新規作成する際に元のTODOのステータス情報をそのまま引き継いでしまっていた。
1. 新規作成する際にステータスを計画済みとして登録されるように修正した。
TODOをfollowupとして登録する際。
=> #456 完了済みTODOのアイコンから新規作成すると完了状態のTODOが作られる問題の修正

include/fields/DateTimeField.php, layouts/v7/modules/Settings/LayoutEditor/resources/LayoutEditor.js, modules/Calendar/models/EditRecordStructure.php, modules/Calendar/models/QuickCreateRecordStructure.php, modules/Inventory/models/EditRecordStructure.php, modules/Settings/LayoutEditor/models/Module.php, modules/Vtiger/models/EditRecordStructure.php, modules/Vtiger/models/QuickCreateRecordStructure.php
- fix #70 
1. カスタム項目において日付形式を選択した時に、デフォルト値にTODAYを設定できるようにした。
2. TODAYを設定された項目は項目値にその日の日付が入力されるようにした。
1. vtiger、カレンダー、インベントリモジュールにおいて以下の修正を行った
　・fieldmodelのdatatyeがdate型かつデフォルト値がTODAYの時に値をその日の日付に設定する。
2. settingsのLayoutEditorにてdate型かつデフォルト値がTODAYの時に型をuitypeのdate型に合わせる処理をスキップした。
3. カスタム項目の日付項目のデフォルト値がTODAYの時は入力欄のバリデーションを外す処理を行った。
4. カレンダーの日付形式においてTODAYの時は表示形式をユーザーの設定に合わせずにそのままTODAYと表示するように変更。
　例)
　・ユーザー設定で日付形式をmm/dd/yyyyにしていた時もカスタム項目のデフォルト値にはTODAYと表示される。これを行わないとカスタム項目のデフォルト値にはTODAY//と表示されてしまう。
　・include/fieldsにてこの処理を行っているが、この処理はdate型を表示する最後のほうの処理である。そのためユーザーの設定に合わせない処理が行われるのはカスタム項目のデフォルト値を表示するとき、かつその値がTODAYの時だけである。
上の画像のようにすると下の画像のようにその日の日付が入力される。
クイック作成時もその日の日付が入力される。
・カスタム項目の日付項目におけるバリデーションの範囲。
・fieldmodelのdatatyeがdate型の時のデフォルト値に関する範囲。 …
=> #70 カスタム項目において日付項目にTODAYを使えるように改善

include/utils/EditViewUtils.php, layouts/v7/modules/Inventory/partials/LineItemsContent.tpl
- fix #632 
1. 製品モジュールの「在庫数」項目を非表示にした時に、見積の編集画面に行くと「在庫が不足しています 最大値：0」の警告文が表示されてしまう。
1. 「在庫数」を非表示にしたとき$data.$qtyInStocknが空になるため、在庫数が数量を上回っていても$data.$qty <= $data.$qtyInStockがfalseになってしまう。
2. 1の条件を満たす場合、本来不必要であっても警告文が表示されてしまっていた。
1.「 $data.$qtyInStocknが空の場合、警告文を出さない。」という条件を加えた。
見積編集画面
製品の数量、在庫に関係する範囲。
=> #632 不必要なコメントが非表示になるように修正

layouts/v7/modules/Vtiger/resources/Detail.js
- fix #539 
1. 日報データの概要画面にある「活動の追加」から活動データを作成する際、
「関連」項目で他モジュールのデータを選択し、保存すると「関連」が空になっている。
1. 日報の概要画面で「活動の追加」を選択し、「関連」項目で他モジュールを選択した際、選択した他モジュールのIDが追加先の「日報」のIDに上書きされていたため、関連項目が空になってしまった。
1. 日報の概要画面で「活動の追加」を選択したときに、「関連」項目のIDが日報のIDに更新されないよう条件分岐した
日報の「活動の追加」「TODOの追加」
=> #539日報の概要画面から活動追加すると関連が空になる

include/QueryGenerator/QueryGenerator.php, include/Webservices/VtigerCRMObjectMeta.php, modules/Vtiger/views/Popup.php
- fix #609 
1. 管理者ユーザー権限を持たないユーザーが、csvインポートをする際に「重複レコードの処理方法」の「選択可能な項目」に項目が何も表示されない。
1. /include/Webservices/VtigerCRMObjectMeta.phpのretrieveMetaForBlock()において、SQL文が適切ではなかったため、ユーザーが選択できる項目の取得に失敗していた。
1. /include/Webservices/VtigerCRMObjectMeta.phpのretrieveMetaForBlock()内部のSQL文を修正し、期待した結果が取得できるSQL文に変更した。
retrieveMeta()を利用してフィールド名を取得している範囲
=> #609 管理者以外のユーザーでログインするとインポートする際に「2 重複レコードの処理方法」で「選択可能な項目」に一覧が表示されない問題の修正

include/QueryGenerator/QueryGenerator.php, modules/Vtiger/views/Popup.php
- fix #603 
1. カレンダーなどから「活動の追加」をする際に「顧客企業」選択後「ご担当者様名」の検索が正常にできない。
1. /modules/Vtiger/views/Popup.phpのinitializeListViewContents()において、「顧客企業」と関連付けて「ご担当者様名」を検索する際に、検索条件が検索用の値を保持する変数にセットされていなかったため
1. 「顧客企業」と関連付けて「ご担当者様名」を検索する際に、検索条件が正しくセットされるように修正
ポップアップウィンドウを利用して「顧客企業」と「ご担当者様名」を関連付けて検索する範囲
=> #603 「活動の追加」をする際に「顧客企業」選択後「ご担当者様名」の検索が正常にできない問題の修正

languages/ja_jp/Vtiger.php, layouts/v7/modules/Reports/Step1.tpl
- fix #691 
1. レポート作成・編集画面でUser、Role、RoleAndSubordinatesに翻訳が当たっていないバグの修正
1. User、Roleはvtransrateが当たっていなかった。
2. RoleAndSubordinatesについてはlanguagesファイルから項目が洩れていた。
1. vtransrate関数を追加
2. languagesファイルにRoleAndSubordinates項目を追加
レポート編集画面
=> refs #691 レポート作成・編集画面での翻訳漏れ修正

layouts/v7/modules/Documents/CreateDocument.tpl, layouts/v7/modules/Documents/UploadDocument.tpl, modules/Documents/views/QuickCreateAjax.php
- fix #678 
1. ドキュメントのカスタム項目においてクイック作成をオンにしていると、非表示にしてもクイック作成に表示されてしまう。
1. 表示させる項目においてクイック作成についての情報しか参照していなかった。
1. fieldlistの項目がRecordStructureに存在するかの条件分岐を入れた。
　存在しなかった場合は表示しないように設定。
　（RecordStructureには非表示の項目は存在しないため、非表示かつクイック作成がオンの項目のみ表示するようになっている。）
> 修正前
> 修正後
=> #678 ドキュメントのクイック作成の非表示項目を表示しないようにする

data/VTEntityDelta.php, languages/en_us/Settings/Workflows.php, languages/ja_jp/Settings/Workflows.php, layouts/v7/modules/Settings/Workflows/FieldExpressions.tpl, layouts/v7/modules/Settings/Workflows/resources/AdvanceFilter.js, layouts/v7/modules/Settings/Workflows/resources/Edit.js, modules/Calendar/Activity.php, modules/Settings/Workflows/models/Record.php
merge #796 
1. ワークフローのアクションの選択肢をRAW入力できるようにしたい
2. 単数・複数選択肢・担当の場合、選択肢を選択できるようにしたい
3. #796 
※ 3について、こちらの修正を加えないと動作しなかったため追加しています。
1. 単数・複数選択肢・担当項目の場合もウィンドウをポップアップさせるように修正
2. 単数・複数選択肢・担当の場合、「--選択肢を使用--」から選択肢を選択できるようにする
- ポップアップウィンドウ(複数選択肢項目)
- ワークフロー条件「単数選択肢」「複数選択肢」「担当」
- ワークフローアクション「項目の値の更新」
=> ワークフローのアクションの選択肢をRAW入力できるようにする

modules/Calendar/Activity.php
- fix #755 
1. ワークフローのアクション「TODOの作成」より特定の条件で発火すると処理が終わらない
1. ワークフロー実行することで元のレコードが更新されるため無限ループとなっていた
1. イベントを発火させないために、saveentity()に置きかえた
関連に活動を持つモジュール
- 案件
- 顧客担当者
- 顧客企業
- リード
- チケット
- 見積
- 発注
- 請求
- キャンペーン
- プロジェクト(活動を関連に持たないが、ワークフローから活動を作成可能)
同様の修正に#535 があった。
イベントを発生させないことが目的であるので、クエリによる更新ではなくsaveentity()に置きかえた。
=> #755 ワークフロー「TODOの作成」より特定の条件で発火すると処理が終わらない箇所の修正

config.customize.php, modules/CustomView/models/Record.php
- fix #830 
1. 下位の役割のリスト（admin権限の場合は全体のリスト）が共有リストに表示される。ユーザーが大量にいると、共有リストが大量に表示されてしまい、本来アクセスしたいリストにアクセスしづらくなる。
1. 表示するリストを取得する段階で、自分より下位の役割が作成したリストをすべて含める処理があった
1. config.customize.phpに$show_subordinate_roles_listを追加し、上記の処理を分岐できるように修正した。
=> #830 [再]共有リストの切り替えの修正

docker/php/Dockerfile
1.php docker イメージ作成のpecl install xdebug  エラー
docker-compose up 実行時、php dockerイメージ作成の段階で以下エラーが発生し、docker-compose upが中断しました。
> [f-revocrm-php 5/5] RUN pecl install xdebug   && docker-php-ext-enable xdebug:
#0 3.667 pecl/xdebug requires PHP (version >= 8.0.0, version <= 8.2.99), installed version is 7.4.33
#0 3.667 No valid packages found
#0 3.667 install failed
1.xdebugの最新バージョンがphp 8.0対応版となったため、php7.4環境を対象に pecl install xdebugを行うとエラーになる。
1. php7.4に対応するxdebugのバージョンを以下より確認し、php/Dockerfile のpecl install xdebugにバージョンを追記してdocker-compose up にて正常動作を確認しました。
[https://xdebug.org/download/historical](https://xdebug.org/download/historical)
特になし
- [] 不必要な変更が無い
特にありません。
=> php Dockerイメージ作成時 pecl install xdebugにてエラーとなる件の対処#789に関連

modules/Reports/ReportRun.php
- fix #797 
1. レポートの副モジュールにカレンダーを設定して時に正しくレポートが出力されないことがあった。
1. 非公開のスケジュールを表示しないようにvtiger_activity.visibility != 'Private' という条件があるが、レポートのカラムの選択にカレンダーのカラムが選択されていないとvtiger_activityを取得しないためここで不具合が発生していた。
1. 副モジュールがカレンダーだった場合はvtiger_activityを取得するよう変更した。
レポートにおいて、カレンダーが副モジュールとして設定された場合。
=> #797 レポートの副モジュールにカレンダーを設定した時に正しくレポートが出力されるように修正

layouts/v7/modules/Calendar/resources/Calendar.js, layouts/v7/modules/Calendar/resources/SharedCalendar.js, modules/Calendar/actions/DeleteAjax.php, modules/Calendar/models/Record.php
- fix #574
- fix #549 
- fix #325 再修正
1. 共有カレンダーにて、予定をマウス移動すると非表示にしていたユーザーの予定も表示される
2. 共有カレンダーにて、現在のログインユーザーの予定が参加者の予定と一緒に移動しない
3. カレンダーのスケジュール削除時に共同参加者も削除してほしい
1. changeUserListにて、インジケータ(左のチェックボックス等)を再構成するときに、再構成前のチェックボックスの状態が考慮されていなかった
2. カレンダーが移動した際に更新されるユーザーリストの中に自分が含まれていなかった
3. php側にて、削除対象となる活動のidのみが送信されていた
1. 再構成前のチェックボックスの状態をgetDisabledFeeds()にて取得できるように変更
2. リストに自分を追加するのではなく、自分の活動に対してrefreshFeed()を実行する
3. リクエストにviewの情報も追加しphp側で判定できるようにし、共同参加者の活動のidも含めて送信するように修正
不具合内容の1について。
layouts/v7/modules/Calendar/resources/SharedCalendar.jsのchangeUserList
このコードでは、最初にわざわざインジケータを削除してから、インジケータの再作成・活動の削除＆追加の処置が行われています。
活動の移動で発火するイベントなのに、インジケータを削除する理由が分かりませんでした。
=> #574 共有カレンダーにて、予定をマウス移動すると非表示にしていたユーザーの予定も表示される

include/QueryGenerator/EnhancedQueryGenerator.php, include/QueryGenerator/QueryGenerator.php, layouts/v7/modules/Vtiger/resources/List.js
- fix #847 
一覧画面（リスト表示）の項目の下にある検索ボックスで、数値項目をピンポイントの数値しか検索できない。
以下のように数値項目を範囲検索できると嬉しい。（カンマで表現）
100以上：100,
100～200：100,200
200以下：,200
新たなsearchOperator"range"を追加し、数値項目の検索欄で","が入力されたときに適用した。
searchOperatorがrangeのときにカンマの前後の数値を取得して検索を行うようにした。
全体表示
手数料率0以上、在庫数30以下、単価-5以上13000以下で検索
在庫数30以下で検索
一覧表示（リスト表示）の検索欄で検索時の挙動
- [] 不必要な変更が無い
=> #847 リストで数値を範囲検索できる機能を追加

modules/Reports/Reports.php
- fix #840 
「全てのレポート」「自分自身にも共有」以外のフォルダからレポートを一覧表示すると、閲覧権限がないレポートを含めすべてのレポートが表示される。
閲覧権限がないレポートは非表示にしたい。
「全てのレポート」「自分自身にも共有」以外のフォルダを開いたとき、閲覧権限のあるレポートのみ表示するように条件を追加。
「全てのレポート」「自分自身にも共有」以外のフォルダを開いた際のレポートの一覧表示画面
- [] 不必要な変更が無い
修正中に発見。レポートを作成する際、レポートの共有にて「役割と部下」から役割を選択すると、選択した役割の部下のユーザーでレポートを閲覧しようとしたときにエラーが起きる。
=> #840 閲覧権限のないレポートを非表示にするように修正

layouts/v7/modules/Inventory/resources/Edit.js
- fix #835 
見積の新規作成画面にて控除された税金のキャンセルが効かない。
再現手順（To Reproduce）
1,見積の作成画面を開く
2,ページ下の方にある控除された税金をクリックする
3,キャンセルを押しても保存を押しても閉じない
控除された税金が登録されていないときは入力欄が存在しないため、.find('input').valid();でエラーが発生してキャンセル等が効かなかった。
入力欄の存在を確認してから.find('input').valid()を行うように修正した。
見積や請求等（請求でも修正確認いたしました。）
=> #835 見積の新規作成画面にて控除された税金のキャンセルが効くように修正

modules/Potentials/dashboards/GroupedBySalesStage.php
- fix #821 
1. ダッシュボードのセールスファネルのグラフの数値と、クリック先のリストの件数が合わない問題
1. セールスファネルのグラフは値が大きい順に上から配置されるように並び替える。その時に凡例も一緒に並び替えがされるべきなのにされていなかった。
(issueの例でいうと、「最終交渉」は20件でありグラフだと下のほうに配置される。それに応じて凡例の「最終交渉」も下に移動し色も変わるべきなのだが、それがされていなかった。)
1. phpで$dataに値をセットする際に件数の多い順にリストに入れるように修正した。
ダッシュボードのセールスステージ情報を用いる範囲。
リストの順番を変えただけなので影響なし。
jsのほうで凡例もグラフと対応するように修正したほうが都合がいい等ありましたらコメントください。
(php側でサニタイズしてtplにデータを持たせていたたため、js側で修正するのが少し大変そうに感じたためこのような修正になりました。）
=> ダッシュボードのセールスファネルのグラフの数値がずれている問題を修正

layouts/v7/modules/Settings/Picklist/EditView.tpl, layouts/v7/modules/Settings/Picklist/resources/Picklist.js
- fix #793 
1. 選択肢エディタで項目の色を設定すると項目名が英語になってしまう。
1. jsで表示していた項目名（value）が英語で渡されていた。
1. 選択肢エディタで編集したときに項目名として渡されるvalueを翻訳後の値にした。
2. 設定後の項目の表示がずれていたため、空白を追加した。
選択肢エディタ
=> #793 選択肢エディタで色を設定すると項目名が英語になる不具合を修正

modules/Import/actions/Data.php, modules/Vtiger/actions/ExportData.php
- fix #767 
1. 翻訳が掛かっている選択肢項目をエクスポートすると英語で出力される
2. 翻訳が掛かっている選択肢項目を日本語でインポートするとフィルターの条件が一致していても一覧に表示されない。また、新しい選択肢として同名の選択肢が追加されてしまった
1. データベース上で英語で登録されている項目名をそのまま出力していたから
2. インポートされた選択肢項目は翻訳前の選択肢項目と比較されるため、別の選択肢として扱われてしまい、フィルターの条件が一致していても一覧に表示されなかった。
1. 選択肢項目を翻訳してからエクスポートするように修正
エクスポート時に選択肢項目のみvtranslateにかけた
エクスポート時の項目名が、フィールド名ではなくカラム名になっている項目はフィールド名に変更したあと、選択肢項目ならvtranslateにかけるようにした
2. 翻訳がかかっている選択肢項目を日本語でインポートしてもフィルターに引っかかるように修正 
インポートする際に各項目のデータタイプを調べ、選択肢項目だった場合翻訳前後を取得、入力項目の翻訳前が存在する場合翻訳前の値を入れた。また、同名の選択肢が追加されるのを防ぐためにData.phpの655行目あたりで翻訳前が存在する場合に翻訳前の値を入れた。
インポートエクスポート
=> #767翻訳がかかっている選択肢項目のエクスポート、インポートについての修正

modules/Calendar/RepeatEvents.php
- fix #539 
1. 繰り返し予定の担当者を変更時、「以降の～」「全て」を選択すると一日だけ変更前・変更後の担当者が参加者に残る
1. 選択した活動に対して編集内容を保存した後に、「以降の～」「全て」の条件に合う活動に対して編集内容を保存していた。そのため選択した活動に対して二回保存の処理が行われていた。
1. 「以降の～」「全て」の条件に合う活動に対しての保存処理を、選択した活動に対しては行わないようにした。
> 変更前
> 変更後
カレンダーモジュールの繰り返し予定の範囲。
繰り返し予定に対して「以降の～」を選択して担当者の変更を行った後に「全て」を選択して担当者の変更を行うと一部のレコードが二重に登録されてしまう。
修正が終わり次第pushします。
=> #539 繰り返し予定の編集について、選択したレコードに対して二回処理を行っている問題を修正

layouts/v7/modules/Calendar/resources/Calendar.js
- fix #744
共有カレンダーマイグループで、記入済みの予定を別日や別の時間へドラッグ移動すると、チェックを外していた人全員にチェックが入って表示されてしまう
カレンダー上のイベントをアップデートするときにマイグループのユーザーリストにチェックを入れる処理があった
原因箇所をコメントアウト
カレンダー
該当箇所をコメントアウトしても、ドラッグ移動した予定の変更やマイグループのチェックボックスの情報は正しく保存はできましたが、少し不安なのでご確認お願い致します。
=> #744 マイグループのチェックボックスが変化しないよう修正

layouts/v7/modules/Calendar/resources/Edit.js
- fix #746 
活動追加において、活動を作成している途中で”活動タイプ”を変更すると終了側の日付が開始側の日付と同日に変更されてしまう
活動タイプを変更したときに動作する関数registerActivityTypeChangeEvent内で、活動の時刻を変更していた
活動タイプを変更しても時刻の変更を行わないように修正
活動
=> #746活動を作成している途中で活動タイプを変更しても終了側の日付が変更されないように修正

modules/Settings/LayoutEditor/models/Module.php
- fix #766 
1. 活動モジュールで並び替え可能な項目（カスタム情報）を並び替えた際に、「並び順を保存」ボタンが出てこず、保存ができない。
2. TODOモジュールの並び替え可能な項目（アラーム情報、カスタム情報）についても同様の不具合があった。
1. 活動・TODOモジュールでは「並び順を保存」ボタンを出さないように設定されていた。
1. 活動・TODOモジュールでも他のモジュールと同様、並び替えた直後に「並び替えを保存」ボタンが出るようにした。
項目設定の各モジュール内での項目の並び替え
TODOモジュールの「アラーム情報」で、デフォルトの項目（事前にメールを送信）はドラッグのアイコンが出ないが、新規追加した項目のみドラッグのアイコンが出る。（どちらもドラッグ可能である。）
=> #766 活動モジュール項目の並べ替えができない不具合を修正

layouts/v7/modules/Dailyreports/RelatedActivities.tpl, layouts/v7/modules/Dailyreports/SummaryViewWidgets.tpl
「更新履歴」を非表示にして活動の幅を広げたい(#891)
- fix #891 [要望]日報モジュールの概要画面の「活動」部分が読みづらいため、「更新履歴」を非表示にして活動の幅を広げたい
1. 日報の概要画面のレイアウトの修正
日報の概要画面
特になし
=> [要望]日報モジュールの概要画面の「活動」部分が読みづらいため、

modules/Vtiger/models/ListView.php
- fix #912
活動の追加項目を共有リスト「すべて」に表示した状態にて、ゴミ箱のカレンダーのリストを開くとFatalエラーが発生し、ゴミ箱の中身を表示することができない。
ゴミ箱でリスト表示する際に、Calendarのフィールドモデルしか取得を行っていなかったことが原因。
Eventsにしか存在しないフィールドがあった場合、フィールドモデルが取得できず、表示に使用するフィールド名をセットするメソッドによりFatalエラーが発生していた。
Vtiger_ListView_Model クラスのgetListViewHeadersメソッドにて、モジュール名がCalendarかつCalendarモジュールのフィールドモデルで取得が出来なかった場合、Eventsモジュールのフィールドモデルで取得を行うように修正。
Vtiger_ListView_Model クラスのgetListViewHeadersメソッドを利用する処理
=> 活動に項目を追加するとゴミ箱のカレンダーでエラーが発生する不具合を修正

modules/Settings/LayoutEditor/models/Module.php
- fix #882 
* 項目を追加した際のcf_XXXが連番になっていない
*  項目の追加時に、getUniqueID()を**2度**使用していることが原因.
* getUniqueID()は番号を取得すると同時に、**idをインクリメント**してしまう.
* 1回目はカラム名(cf_xxx)を作成するために、2回目はaddField()にて使用されている.
* getUniqueID()を使用せずにcf_xxxを作成する..
* vtiger_field_seqを参照する関数getSequenceNumber()を作成した.
* vtiger_fields
* 項目の新規作成時
=> #882 項目を追加した際のcf_XXXが連番になっていない箇所の修正

layouts/v7/modules/Calendar/CalendarSharedUsers.tpl, layouts/v7/modules/Calendar/resources/Calendar.js, layouts/v7/skins/marketing/style.css, resources/styles.css
- fix #872 
1. ワンボタンで現状表示されているグループの全チェック/全解除が出来るような機能が欲しい
* マイグループの左に全チェック/全解除用のチェックボックスを配置
* 各ユーザーの状態と全チェックボックスの状態が連動するように修正
* すべてのユーザーにチェックがついたら, 全チェックボックス→☑
* いずれかのユーザーのチェックが外れていたら, 全チェックボックス→□
* 選択前の状況
* 全選択
* 全解除
=> #872 共有カレンダーの全チェックON/OFF機能の追加

languages/ja_jp/Reports.php, layouts/v7/modules/Reports/resources/Edit1.js
- fix #570 
1. レポートを作成する際、同名のレポートが存在した場合に出る警告文が「レポートの複製」であるため、原因がわかりずらい。
1. 存在するレポート名を入力した際に出る警告文が「レポートの複製」と設定されている。
1. 「同名のレポートが存在します。」という警告文を作成し、存在するレポート名を入力した際に表示するようにする。
その他の警告文の表示
=> #570 同名のレポートが存在した場合の警告文を変更。

layouts/v7/modules/Settings/Vtiger/ListViewContents.tpl
- fix #489 
一番左の項目に罫線が入ってきてしまっていた。
同じクラスを適用した。
> 修正後
> 修正前
=> #489 一部罫線のスタイルの崩れを修正

languages/ja_jp/Vtiger.php, layouts/v7/modules/Vtiger/Comment.tpl, layouts/v7/modules/Vtiger/CommentsList.tpl, layouts/v7/modules/Vtiger/resources/Detail.js
- fix #897 
1. 関連のコメントを開いた際に子コメントが表示されていなくて、子コメントに気づきにくい。
1. コメントに子コメントがある場合はCommentsList.tplを再帰的に読み込みなおすようにした。
2. 表示、非表示ボタンを追加した
コメントを表示する範囲すべて
=> #897 関連のコメントを開いたときに子コメントがすべて表示されるようにする修正

layouts/v7/modules/Vtiger/resources/List.js
- fix #933 
一覧画面上でのダブルクリック編集時にチェックボックス項目について既存の値が「はい」だったとしても「いいえ」として編集状態になる。この為、意図せずチェックが外れてしまうことがある。
ダブルクリック編集時のチェックボックス項目に0,1ではなく，’はい’，’いいえ’が入力されていたため
1. fieldTypeがbooleanのときにvalueが0,1で取得するように修正
一覧画面
ダブルクリック時
一覧画面でダブルクリック編集をした時
=> #933 一覧画面上でダブルクリック編集時にチェックボックスが空欄になる不具合を修正

layouts/v7/modules/Calendar/resources/Calendar.js, layouts/v7/modules/Vtiger/resources/Vtiger.js
- fix #564 
1. カレンダー画面でTODOを編集した際に不適切なメッセージが表示されていた。
1. typeofでの場合分けがうまく機能していなかった。
1. typeofを使わずに、recordの値が適切か否かで場合分けをした。
2. 本来、活動の編集でも「活動を更新しました。」のメッセージが表示されるべきであったが表示されていなかったため、TODOと同じように場合分けをしてメッセージが表示されるようにした。
・TODOを編集した際のメッセージ
・活動を編集した際のメッセージ
その他のメッセージの表示
=> #564 TODOを編集した場合のメッセージの不具合を修正

layouts/v7/modules/Settings/Workflows/WorkFlowTrigger.tpl
- fix #644 
1. ワークフローを作成する際に、最大数を設定していないのに「定期的に実行」を選択することができない。
1. 最大数を設定していないとき、$MAX_ALLOWED_SCHEDULED_WORKFLOWSがnullであった。
2. ワークフロー数が常にnullと比較されていたため最大数を超えていると判定されていた。
1. $MAX_ALLOWED_SCHEDULED_WORKFLOWSがnullの場合は、「定期的に実行」を選択できるようにした。
ワークフロー最大数が関連する範囲
=> #644 ワークフローで定期的に実行が選択できない不具合を修正

modules/Calendar/actions/Feed.php
　修正
- fix #1003 [不具合] カレンダーで月をまたいで3か月以上の終日活動を登録すると、3か月先からカレンダーに活動が表示されない
1.  カレンダーで月をまたいで3か月以上の終日活動を登録すると、3か月先からカレンダーに活動が表示されない
1. 活動のみ範囲を絞っていた
1. 範囲を絞るのをやめた
1. 長期間の終日予定のカレンダー部分
=> #1003 [不具合] カレンダーで月をまたいで3か月以上の終日活動を登録すると、3か月先からカレンダーに活動が表示されない

modules/Reports/models/Record.php
- fix #1006
1. レポートのCSVエクスポートにてInternalServerErrorが発生する
1. Apacheのセキュリティ強化により、Transfer-Encoding: chunckedの指定に厳格になったものと思われる
1. CSVエクスポートの際、Transfer-Encoding: chunckedのheaderを削除し、Content-Lengthを指定するよう修正
レポートのCSVエクスポートのみ
=> #1006 [不具合]レポートのCSVエクスポートにてInternalServerErrorが発生する問題の対応

data/CRMEntity.php
修正
- fix #1008 
1.  レポート 明細のあるモジュールと明細の元となるモジュールを関連モジュールにすると余計に結合される
1.  明細と関連モジュールでそれぞれ結合していたため
1.  併せて結合するよう修正
※ 1レコードに3つの明細がある状態
レポートで主モジュールに明細があるモジュール、関連モジュールに明細の中身のモジュールを使用した場合
=> #1008 [不具合]レポート 明細のあるモジュールと明細の元となるモジュールを関連モジュールにすると余計に結合される

include/QueryGenerator/QueryGenerator.php, layouts/v7/modules/Vtiger/resources/AdvanceFilter.js
- fix #1010
1.  uitype=10の場合はリストの条件に「自分」を選択することが出来ない
1. uitype=10の場合はリストの条件で「自分」の選択肢を削除していた
2. uitype=10の場合は検索条件が氏名ではなくvtiger_users.idにする必要があるため、ownの条件の場合の処理に問題がある
1. uitype=10の場合はリストの条件で「自分」の選択肢を削除されないように修正
2. uitype=10の場合は検索条件が氏名ではなくvtiger_users.idにする必要があるため、ownの条件の場合の処理を修正
- リスト作成画面
- リスト検索
- レポート条件設定
ワークフローは未対応
=> Fix/#1010 uitype10でUsersモジュールが紐づいている場合はリスト作成時に「自分」を選択できるようにする

modules/com_vtiger_workflow/WorkFlowScheduler.php
- fix #1012
1. ワークフロー 定期的に実行 を使用する際に 日付項目に対して 空ではない 条件を指定すると正しく動作しない
1. 空でないに対して日付項目で != "" のSQL が発行されエラーになっていた
1. 日付項目に対しては!= ""が入らないように修正
- ワークフロー 定期的に実行 + 空ではない 条件を指定時
- [×] 自らテストを行った
- [×] 不必要な変更が無い
- [×] 影響範囲の検討を行った
=> #1012 [不具合] ワークフロー 定期的に実行 を使用する際に 日付項目に対して 空ではない 条件を指定すると正しく動作しない

modules/Calendar/Activity.php
1. PHP8移行、繰り返しスケジュールを作成すると、ワークフロー周りをスキップする処理でエラーになる不具合
1. 配列が初期化されていないため
1. 初期化を実施した
繰り返しスケジュール＋招待者がいる場合の活動の保存すべて
=> 繰り返しスケジュールを保存すると、エラーになる不具合の修正

layouts/v7/modules/Vtiger/resources/Vtiger.js
- fix #1046
1. クイック作成で選択した複数選択の項目が詳細入力遷移時に引き継がれない
1. 複数選択肢の値を配列のままRequesutに格納しているため詳細表示の項目で表示できていなかった
1. 複数選択項目のkeyから[](角括弧)を除外
2. 値が配列だった場合、|##|で区切った文字列に変更
- その他複数選択肢項目があった場合に影響がないか
=> #1046 クイック作成→詳細入力時に複数選択項目で1つ選択の場合に引き継がれない

layouts/v7/modules/Vtiger/resources/Vtiger.js
- fix #906 
1. チケットのクイック作成時に詳細内容を入力する際に，改行コードを使用しないと改行されない
1. 表示に`<br>`が使われていなかった．
1. 保存する際に，改行を改行コードに変換した．
2. チケットを詳細入力から保存したときには，詳細内容の入力にCKEditorを用いているため改行が<br>として保存される．この修正以前に詳細入力から保存されたチケットとの互換性を踏まえて，保存する際に改行を改行コードに変換している．
チケットモジュールにてクイック作成を行うとき
改行コードの保存を統一したほうが良いかもしれない．
チケット(CKEditorを使用しているモジュール)は改行コードを保存している
活動(CKEditorを使っていないモジュール)は改行コードを保存しない
=> #906 チケットのクイック作成時に改行を改行コードを使わなくても行えるようにする

modules/Portal/actions/DeleteAjax.php
- fix #905 
ブックマークの一覧画面にて，チェックボックスで選択してゴミ箱マークからは削除できるが，個々のドロップダウンから削除を選択してもブックマークが削除されなかった．
ドロップダウンから削除を行う時に存在しない関数を使用していた．
存在する関数を指定した
ドロップダウンから削除できるように修正
ブックマークのドロップダウン削除
=> #905 ブックマークを一覧画面から削除できない不具合を修正

layouts/v7/modules/Vtiger/RelatedActivities.tpl, modules/Calendar/models/Record.php
- fix #963
1.  RelatedActivities.tplでEmailの文章の場合はHTMLタグを除外するように変更
変更前
変更後
=> #963 [要望]活動一覧のメール文章からHTMLを除外する

modules/Accounts/models/Module.php
- fix #1063
顧客企業の活動一覧のデータが表示されない
以下のカラム名を重複した状態で取得しようとしてエラーが発生していた
1.  vtiger_crmentity.description とvtiger_activity.description
2.  vtiger_crmentity.smownerid と vtiger_activity.smownerid
活動一覧表示に不要なカラムをSELECT文から削除
1. vtiger_crmentity.smownerid
2. vtiger_crmentity.setype
3. vtiger_crmentity.description
- 顧客企業 活動一覧
=> #1063 [不具合]顧客企業の活動一覧データが表示されない

languages/ja_jp/Leads.php
- fix #980
1.  リードのフィールドである「メールアドレス(予備)」が「電話番号(予備)」と表示されている
※内部名称がsecondaryemail、デフォルトのuitypeがメールアドレスであることから判断
1. リードの「Secondary Email」への日本語翻訳が間違っていた
1. 「Secondary Email」の翻訳を「メールアドレス(予備)」に変更
変更前
変更語
リードのフィールド表記のみ
概要、詳細、編集ページで正常になっていることを確認済み
=> thinkingreed-inc#980 リードのメールアドレス(予備)のラベルが間違っている

languages/ja_jp/Vtiger.php, layouts/v7/lib/jquery/resizableColumns/css/jquery.resizableColumns.css, layouts/v7/lib/jquery/resizableColumns/js/jquery.resizableColumns.js, layouts/v7/modules/Vtiger/ListViewActions.tpl, layouts/v7/modules/Vtiger/resources/List.js, layouts/v7/skins/contact/style.css, layouts/v7/skins/inventory/style.css, layouts/v7/skins/marketing/style.css, layouts/v7/skins/marketing_and_sales/style.css, layouts/v7/skins/project/style.css, layouts/v7/skins/sales/style.css, layouts/v7/skins/support/style.css, layouts/v7/skins/tools/style.css, layouts/v7/skins/vtiger/style.less, resources/styles.css
- fix #1028 
1. 列を狭めると右端の項目が必ず大きくなってしまい，スクロールバーを消すことができない．
2. リストを切り替えた場合，他のリストの設定が反映されている？のか列の幅がおかしくなる．
3. 列幅をリセットできる機能がない．
2. 列幅を保存するときに「モジュール名-項目名」という形式で保存していたため，リストを変更しても他のリストの列幅が適用されていた．
1. 右端項目の列幅を調整できるように，ダミーカラムを右端に追加．
2. 列幅を保存するときに「cvid-fieldid」という形式で保存するように修正．一覧画面から項目を削除するときにローカルストレージから該当項目の列幅も削除するように修正
3. 一覧画面の「その他」に「列幅をリセット」を追加
ダミーカラムを追加後の一覧画面
全モジュールの一覧画面
=> 一覧画面の列幅可変機能の修正

include/Webservices/ChangePassword.php, include/Webservices/ConvertLead.php, include/Webservices/DeleteUser.php, include/Webservices/FileRetrieve.php, include/Webservices/GetUpdates.php, include/Webservices/LineItem/RetrieveInventory.php, include/Webservices/Login.php, include/Webservices/Logout.php, include/Webservices/OperationManager.php, include/Webservices/Query.php, include/Webservices/VtigerWebserviceObject.php, modules/Migration/schema/740_to_741.php, setup/scripts/78_Update_RESTAPI.php, setup/scripts/78_Update_SyncAPI.php
- fix #1093 
1. PHP8以上の環境で、REST APIが適切に動作しない
1. `call_user_func_array` の仕様変更による、関数と引数の設定がおかしいため
1. REST APIで使われる関数とAPIで投げるパラメーター（＝引数名）を一致させるように修正
2. 足りていないパラメーターがあったため、 `vtiger_ws_operation_parameters` を更新するMigrationを追加
- REST APIのみ
Migrationが必要なため、`7.4.1` としています。
また、本PRを早めに適用したい場合は、手動で以下のコマンドを実行してください。
`php setup/scripts/78_Update_RESTAPI.php`
※Migrationで複数回目の実行も問題ありません
=> Fix #1093 PHP8以上の環境で、REST APIがエラーになっていた不具合の修正

include/utils/UserInfoUtil.php, modules/PDFTemplates/views/Detail.php, modules/PDFTemplates/views/Edit.php, modules/PDFTemplates/views/List.php, modules/PDFTemplates/views/Popup.php
- fix #983
PDFテンプレートモジュールにモジュール自体を無効化しても、プロファイル設定で制限をかけても、PDFTemplateのURLを知っていればアクセスができてしまう
モジュール無効化が効かない
- PDFテンプレートの有効無効判定は行われていたが、適切にエラースローが行われていなかったため
プロファイル制限が効かない
- パーミッション判定の処理が適切に行われていなかったため
モジュール無効化が効かない
- PDFテンプレートの有効無効判定後、適切にエラーがスローされるように修正
プロファイル制限が効かない
1. パーミッション判定処理にてPDFテンプレートの判定行われるように修正
2.  PDFテンプレートモジュールの各Viewファイルで権限判定が行われるように修正
PDFテンプレート機能全体
=> PDFテンプレートモジュールにモジュール無効化やプロファイル設定で制限をかけてもアクセスができる不具合の修正

modules/Users/models/Field.php
- fix #1033 
1. ユーザー情報の項目「メールの署名」を詳細画面の鉛筆マークから編集すると編集できない
1. 「メールの署名」項目はリッチテキスト項目であり、詳細画面から編集できないが制御がかかっておらず編集可能項目となっていた
1. チケット、FAQなどと同様、リッチテキスト項目のため編集不可とするよう修正した
ユーザー詳細「メールの署名」のみ
=> #1033 ユーザー情報の項目「メールの署名」を詳細画面から変更できないよう修正

modules/Leads/models/Module.php
- fix #1108
リードのデータが保存された状態で、ダッシュボードの以下のリード関連のウィジェットを表示しても、
該当しているデータが表示されていない。
- リード（業界別）
- リード（ステータス別）
- リード（紹介元別）
リードのウィジェットで利用するSQLでWHERE句のカラム指定でテーブル名を記述していないため、
mysql の 1052エラーが発生していた。
テーブル名も含めてカラム名を指定するように変更した。
- リード（業界別）
- リード（ステータス別）
- リード（紹介元別）
=> #1108 リードのウィジェットの不具合を修正

layouts/v7/modules/ModComments/ListViewContents.tpl, layouts/v7/modules/RecycleBin/ListViewContents.tpl, layouts/v7/modules/Reports/ListViewContents.tpl, layouts/v7/modules/Reports/ListViewRecordActions.tpl, layouts/v7/modules/Vtiger/ListViewContents.tpl
- fix #1117
一覧画面でヘッダーカラムの検索フィールドにて、Enterキーによる検索を実行した場合に、
入力した内容でフィルタリングされない。
#985 で floatThead を利用しなくなったことにより、Enterキーで検索した際に検索ボタンの
クリックイベントが2回起動するようになっていた。
2回の起動でクリックイベントの処理が画面描画に間に合わず、リストが正しくない状態で表示されていた。
検索ボタンに`type="button"`を追加して、フォームのデフォルトで起動するクリックイベントを無効化した。
各モジュールの一覧検索
=> #1117 Enterキーで検索できるように修正

layouts/v7/modules/Portal/ListViewContents.tpl, layouts/v7/modules/RecycleBin/ListViewContents.tpl, layouts/v7/modules/Vtiger/ListViewContents.tpl, layouts/v7/modules/Vtiger/resources/List.js, resources/styles.css
- fix #1134
1. 一覧画面でスクロールを行うとヘッダーの項目名部分と検索ボックス部分の隙間からスクロールしたコンテンツが見える 
1. 一覧画面で使用するtableのスタイル設定が不適切だったため
1.一覧画面で使用するtableのスタイルを修正 
修正前
修正後
各一覧画面のスタイル
=> 一覧画面でスクロールを行うとヘッダーの項目名部分と検索ボックス部分の隙間からスクロールしたコンテンツが見えないように修正

layouts/v7/modules/Vtiger/ListViewActions.tpl
- fix #1135 
1. FAQモジュール一覧面に列幅をリセットするボタンがないため、列幅のリセット操作ができない。
1. 列幅リセットボタンが設置されている親の要素が、モジュールの設定値によって非表示となるため。
1. 列幅リセットボタンのみ、モジュールの設定値に関係なく表示されるようにテンプレートファイルを修正。
修正前
修正後
layouts/v7/modules/Vtiger/ListViewActions.tpl を利用して、リスト上部のボタンを表示している画面
=> 可変列幅機能が実装されている一覧画面に列幅リセットボタンが表示されるように修正

resources/styles.css
- fix #1138
1.一覧画面にてレコード件数が少ないときに、スクロールバーがレコードに被ってしまいクリックがやりにくいことがある。スマートフォンなどではスクロールバーが細いため問題にならないが、WindowsPCの場合スクロールバーが非常に邪魔になる。 
mediaqueryで830px以下になった際に、本来非表示になるスクロールバーが表示されてしまう
1. スクロールバーが表示されないように修正
修正前
修正後
各モジュールのリスト画面
=> レコード数が少ない時にスクロールバーでレコードが隠れる不具合を修正

modules/Users/Users.php
- fix #1140
ユーザーの作成/更新時に user_priviileges を作成する処理（createUserPrivilegesfile ）が
2回起動するような構造になっている。
VtigerCRMの実装によるもの。
Users.php#save と Users.php#saveentity のどちらでも createUserPrivilegesfile を利用して、
user_priviileges を2回作成するよう動作していた。
Users.php#saveentity の createUserPrivilegesfile を削除
動作順
1. modules/Users/actions/Save.php#process
2. modules/Users/models/Module.php#saveRecord
3. modules/Users/models/Users.php#save
4. data/CRMEntity.php#save
5. modules/Users/models/Users.php#saveentity
- ユーザーの作成
- ユーザーの更新
- ユーザーのインポート
=> #1140 1回の保存でuser_privilegesを2回作成する処理を修正

layouts/v7/modules/Vtiger/ListViewRecordActions.tpl, modules/Vtiger/views/List.php
- fix #1125 
レコードを複製する場合、現状モジュールのレコード一覧画面から対象レコードを選択した後の、概要・詳細画面「その他▼」からしか複製ができない。
編集や削除のように、モジュールのレコード一覧画面から複製ができるようにしてほしい。
一覧画面からレコードを複製するボタンの追加
モジュールの一覧画面
=> モジュールの一覧画面からレコードを複製する機能の追加

resources/styles.css
- fix #1123 
スクリーンショットにて提示するが、ウィジェット右下の更新ボタン・削除ボタンが重なって表示されている。
一覧画面において、列幅調整用のhandleと削除ボタン（ソート時に表示）が重なることを避けるために、削除ボタンの位置を調整していたため。
一覧画面のヘッダーに表示される削除ボタンの位置だけを調整するように修正
listview-tableの削除ボタン
=> #1123 ウィジェットの削除ボタンと更新ボタンが重ならないように修正

resources/styles.css
- fix #1015 
1. 編集画面にてタイトル文字列が見切れる
1. padding-leftが3%の相対指定であるため
1. サイドバーがあるときは57pxに固定する
57pxは詳細画面のcontent-areaと同値 #309 
- 1366×768の解像度
* レコード編集画面
=> ディスプレイサイズが推奨の解像度の範囲内にも関わらず文字が見切れる箇所の修正

modules/Vtiger/models/ListView.php
- fix #1024 
1. 一覧画面において?（半角ハテナ）を検索するとSQLエラーが発生する
1. リストの内容を取得するSQLにおいて、検索内容の?を置換しようとしていたため
1. WHERE句などはQueryGeneratorで作成されており、paramsで渡していたのはLIMIT句のもののみだったので、
LIMIT句を生成したQueryを自分で生成するようにし、PearDatabase::pqueryにparamsを渡さないように修正した
※Documentsモジュール用のgetListViewEntriesでは元々このような作りになっていたので、そちらにあわせる形の修正
各モジュールの一覧画面
=> #1024 一覧画面において?（半角ハテナ）を検索するとSQLエラーが発生する問題の対応

layouts/v7/modules/Settings/LayoutEditor/FieldCreate.tpl, modules/Settings/LayoutEditor/models/Module.php
- fix #954 
1. 項目設定でカレンダー、活動がモジュール一覧から出てこなくなった
1. #638 
* Module.phpの修正のみ影響
* FieldCreate.tplの修正は、カスタム項目を関連として作成するとテキストになるバグに対する修正なので本件とは無関係
1. FieldCreate.tpにてカレンダー・活動を表示しないように修正
* 項目設定の選択肢、カレンダーと活動を追加
* 関連項目の選択肢、カレンダーと活動を削除
ご指摘のあった#740については、
「活動」「カレンダー」を除外する**修正以前**に作成された関連項目を削除することを目的としています。
=> 項目設定でカレンダー、活動がモジュール一覧から出てこなくなったデグレの修正

layouts/v7/modules/Vtiger/ListViewContents.tpl
- fix #800
顧客担当者等の一覧画面にて関連項目のリンクにカーソルを合わせたときに表示されるツールチップに、モジュールの項目名ではなくデータの詳細を表記したい
例えば、案件一覧を開いて関連したモジュールの項目である顧客企業名のリンクにカーソルを合わせると「顧客企業名」とだけ表示され、リンクから少しカーソルを外すと「○○会社」と詳細企業名が表示される。
顧客企業名のリンクにカーソルを合わせたときも詳細を表示したい。
一覧画面を表示するときにデータタイプが関連ならばgetTitleを通らせた
一覧表示画面
=> #800 一覧画面で表示される関連項目のtooltipの表記をデータの詳細に変更

layouts/v7/modules/Reports/DetailViewActions.tpl
- fix #719
レポートの追加からグラフを作成後、ピンマークをクリックした際に出てくるタブの翻訳漏れ
翻訳前の項目名をそのまま表示していた
vtranslateを通した
レポート
=> #719 レポート画面の翻訳漏れの修正

modules/Reports/ReportRun.php, modules/Reports/actions/ChartSave.php
- fix #1133
1.  共有されたレポートの詳細画面を表示できない
2.  レポートの新規作成からグラフを作成できない
1. PHP8系で廃止された 「implode(array$array, string $separator)」でエラーが発生して閲覧できなかった
2. レポート作成で対応した 6e9bdbab48f36f4d11b950fd5db2d4e2cee95902 のグラフ横展開漏れ
1. 「implode(string $separator, array$array)」に変更
2. 6e9bdbab48f36f4d11b950fd5db2d4e2cee95902 と同じ横展開を実施
レポートの閲覧
=> #1133 レポートのPHP8対応漏れ修正

modules/Reports/models/Record.php
- fix #1167
レポート一覧から一括削除機能を実施しようとするとエラーメッセージが画面に表示されて失敗する。
PHP8系対応漏れ
インスタンスメソッドをstaticメソッドとして呼び出してエラーが発生していた
1.  メソッドをstaticメソッドに変更
- レポート一覧の一括削除
- レポート一覧の一括移動
=> thinkingreed-inc#1167 レポート一覧で一括削除できないバグの修正

layouts/v7/modules/Vtiger/resources/List.js, modules/Documents/models/Module.php
- fix #1173 
1. ドキュメントモジュールの一覧画面にてEnterキーを押して検索を実行すると、「成功」のメッセージが表示される。
2. 検索結果をクリアで解除すると、一覧先頭のファイル名のリンクが外れている。
1. Enter押下の際に一覧のインライン編集の保存イベントが発火していた。（ドキュメントモジュールはインライン編集はもともとの仕様で不可） 
2. 有効無効の値が更新されて、無効になっていた
1.  インライン編集が使用しないモジュールでは、原因となったイベントがセットされないように修正
- 検索機能を持つ一覧画面
- インライン編集機能
=> ドキュメントモジュールの一覧から検索を行うと勝手に無効化される不具合の修正

languages/ja_jp/Calendar.php, modules/Calendar/Activity.php, modules/Calendar/CalendarCommon.php, modules/Events/actions/Save.php, modules/Events/actions/SaveAjax.php
- fix #1144 
1. 活動に参加者を追加すると、それぞれの参加者が担当になった活動レコードが生成されるが、
活動の編集方法によっては関連づいた活動レコード内で同じ担当者の状態のレコードに変更できてしまう。
1. 活動レコ―ドの編集を行った際に、重複したユーザーが登録される可能性が考慮されていないため
1. 活動保存時に関連する活動のユーザーを確認し、重複する場合はユニークになるように重複した内容のレコードを論理削除するように修正
2. ゴミ箱から復元した際にも重複が発生する可能性があるため、重複する場合はエラーメッセージ表示して復元を行わない
重複するレコードの復元操作を行った際にエラーメッセージ
- 活動の保存機能
- ゴミ箱から活動のレコードを復元する処理
=> 関連している活動に重複したユーザーで活動の登録が行われないように修正

layouts/v7/modules/Calendar/resources/SharedCalendar.js, resources/styles.css
- fix #1148
1. 共有カレンダーのマイグループにて、マイグループを再選択した際に姓名の文字数が長いユーザーの表示が崩れる場合がある
1. htmlにclass設定が適切に付与されていなかったため必要なスタイルが付与されていなかった
1. グループを変更した際のhtml生成時に適切にclassが付与されるように修正
2. スタイルの調整
修正前
修正後
共有カレンダーのユーザーリスト部分
=> 共有カレンダーにてユーザーリストの表示が崩れる不具合の修正

layouts/v7/modules/Calendar/resources/SharedCalendar.js
- fix #1162 
ユーザー名に「×」や「∞」などの特殊文字が含まれている場合、共有カレンダーの左カラムに表示されるグループごとのユーザー名一覧にて、ユーザー名が正しく表示されない
* 通常時：CalendarSharedUsers.tpl内の$USER に特殊文字を含むユーザ名(例: &amp;infin;テストユーザ)が格納され、HTMLとして出力される. このため、ブラウザが自動的に &amp;infin; を解釈して ∞ へ変換する.
* グループ選択時：SharedCalendar.js内のchangeUserList関数では、ユーザ名がそのまま設定される. このためブラウザによる変換が行われず、&amp;infin; がそのまま表示される.
動的な処理でのみ発生する不具合であるため、changeUserList関数内でユーザ名をデコードするように修正
&amp;infin; が ∞ へ変換された様子
=> #1162 共有カレンダーにて、特殊文字が含まれているユーザー名が正しく表示されない不具合の修正

modules/Calendar/actions/Feed.php
- fix #1181
1. 終日の予定を帯で入れた際に、開始から終了まで正しく表示されない
2. 毎回発生するわけでは無く、発生の条件が不明
1. 検索を早めるために追加した活動レコードの検索条件に誤りがあった
2. 条件が誤っていたため、活動レコードに登録されている完了日を含む直近1週間前にならないとカレンダーの表示の対象として結果に含まれていなかった
1. 検索条件を修正
- 活動モジュールの共有カレンダー表示
=> 開始日と終了日を1週間近く跨いだ場合に予定が表示されない不具合の修正

include/utils/EmailTemplate.php
- fix #1201 
1. PDFテンプレートに通貨の変数を設定して、PDFを出力しても値が空で表示される。
通貨はvtiger_ws_entity_nameテーブルでidで検索された場合は通貨名に変換するロジックを持つ。
通貨名に変換後、通貨名を利用してvtiger_currency_infoのidで検索していたため、
nullを取得・設定していた。
```
＜SQL例＞
select
currency_name as entityname, 
id 
from
vtiger_currency_info 
where
id in ('Argentina, Pesos')
```
1. SQLでid検索するように通貨名を変換しない
- 修正後
uitypeが117のフィールドをPDF出力する場合
=> #1201 PDFテンプレートに通貨が表示されないバグの修正

layouts/v7/modules/Settings/LayoutEditor/DefaultValueUi.tpl
- fix #1203
1. 項目の新規作成をする際、デフォルト値に最初から半角スペースが設定されている場合がある
1. 項目作成モーダルのデフォルト値は、該当モジュールの最後の項目のデフォルト値を表示していた。
1. 項目作成モーダルのField_Modelからデフォルト値を取得するように修正
周辺を選択してもデフォルト値のフィールドに何も入っていない状態
- 項目作成モーダルのみ
=> #1203 項目の新規作成でデフォルト値に不要な半角スペースを設定させない

layouts/v7/modules/Calendar/resources/Calendar.js
- fix #1206 
1日あたりの予定が複数登録されている場合に、カレンダーで「月」表示を行うと1日の表示マスの高さによる制限で1日の予定が全件表示されない。
この場合、1日の予定全件を確認するために「+7more」などの表示をクリックして表示を展開させる必要がある。これを1日の予定が全件表示される状態に変更してほしい。
1. 表示件数の制限を解除
2. 1日のマスの高さを自動調整されるように修正
3. カレンダー全体の高さが必要に応じて伸びるように修正
カレンダーの月表示
=> 月表示の際に1日の予定を全件表示できるようにする修正

layouts/v7/modules/Calendar/resources/Calendar.js
- fix #1189 
カレンダーを月表示にした際、活動の開始時刻は表示されるが、終了時刻は表示されない。
終了時刻も表示されるようにしてほしい。
月表示の場合に終了時刻が表示されるように修正
カレンダーの月表示
=> カレンダーの月表示で終了時刻が表示されるように修正

modules/com_vtiger_workflow/VTSimpleTemplate.inc
- fix #1198 
メール送信を行うワークフローでメールに選択肢（複数）項目の値を使用すると、FatalErrorが発生しワークフローなど保存後処理が完了しない症状が発生
メール送信ワークフローで使用する値の変換処理が原因
選択肢（複数）の値が1個のみの場合、配列を期待している引数に文字列が渡され、型の不一致でFatalErrorが発生した
値が1個の場合でも、変換処理の引数が配列で渡されるように修正
- ワークフローにてメールを送信する処理
- ワークフローにてSMSを送信する処理
- ワークフローにて活動を作成する処理
=> 複数選択の値をメール送信ワークフローに使用するとFatalErrorが発生する不具合の修正

modules/ProjectTask/views/QuickCreateAjax.php
- fix #1212 
プロジェクトモジュールの関連タブからプロジェクトタスクレコ―ドを作成しようとするとエラーが発生して作成画面を開くことができない。
クイック作成の対象項目取得モードが他のモジュールと異なっていたため、取得した項目情報の展開に失敗していた
クイック作成の対象項目の取得が他のモジュールと同じモードで実行されるように修正
プロジェクトタスクモジュールのクイック作成画面
=> 1212 プロジェクト関連タブからプロジェクトタスクの作成が開けない不具合の修正

docker/headlesschrome/Dockerfile, docker/headlesschrome/docker-compose.yml
- fix #871
1. Ubuntuの24.04にはないライブラリをインストールしようとしてエラーが発生していた。
利用するubuntuのバージョンは常に最新を取得するような記述になっていたが、
Ubuntu24.04がリリースされて以降、削除されたライブラリを
Dockerfileでインストールしようとしてビルドに失敗していた。
1. Dockerのバージョンを24.04に指定
2. ライブラリを最新化
3. docker-composeファイルの記入ミスを修正
Dockerコンテナ headlesschrome のビルド
=> #871 Chromeをヘッドレスモードで動かすDockerfileのubuntu24.04対応

docker/headlesschrome/converthtmltopdf.php, modules/Vtiger/helpers/PDF.php
- fix #907
--print-to-pdf-no-header を利用することでdeprecatedのWarningがapacheログに残る
https://developer.chrome.com/docs/chromium/headless?hl=ja
Googleのサイトに「--print-to-pdf-no-header」が非推奨となっていることが明記されている。
--no-pdf-header-footer に修正
headlesschrom を利用したPDF出力
=> #907 google-chromeのdeprecatedなオプションを変更

layouts/v7/modules/Vtiger/resources/List.js, modules/Inventory/models/MassEditRecordStructure.php, modules/Vtiger/models/MassEditRecordStructure.php
- fix #1219
1. 一括編集画面でバリデーション効かず、必須項目でも空で送信できる状態だった。
1. 一括編集のsubmitやテンプレートからバリデーションを外していた
1. チェックボタンがついた項目にのみvalidation.jsの機能が効くように修正
- チェックボックス未選択
- 必須項目未入力
- URL形式不正
すべての一括編集モーダル
=> #1219 一括編集でバリデーションが効くように修正

include/QueryGenerator/QueryGenerator.php
- fix #1234 
レコードの抽出条件を設定したリストを開いた際にFatalErrorが発生する場合がある。
array_mapの第一引数の渡し方が不適切だったため。
DBを検索する際の条件として複数の値を使う場合に、検索に使用する値が配列で渡ってくる。
配列に対してarray_mapでそれぞれの値にtrimかを実行しているが、このtrimの渡し方が不適切だったためエラーが発生した。
array_mapの第一引数の渡し方を修正。
SQL発行時に検索条件の値が範囲になる場合
=> レコードの抽出条件を設定したリストを開いた際にFatalErrorが発生する場合がある 不具合の修正

layouts/v7/modules/Vtiger/resources/Edit.js
- fix #1239 
選択肢の連動設定がされた選択項目の連動元の選択肢の値を複数回変更すると連動先の選択肢の順番が入れ替わってしまうことがある。
Option要素オブジェクトの順番が処理の際に入れ替わってしまうことがある。
Option要素オブジェクトを保持する方法を、順番が保証されないオブジェクトから順番が保証される配列に変更。
選択肢連動設定がされた単数選択項目
=> 選択肢の連動設定を行うと選択肢の順番が入れ替わる場合がある不具合の修正

modules/com_vtiger_workflow/tasks/VTUpdateFieldsTask.inc
- fix #1224 
Workflowの処理で関連が空の場合にFatalErrorが発生する
---以下エラー内容---
Fatal error: Uncaught TypeError: count(): Argument https://github.com/thinkingreed-inc/F-RevoCRM/issues/1 ($value) must be of type Countable|array, null given in /var/www/html/F-RevoCRM/modules/com_vtiger_workflow/tasks/VTUpdateFieldsTask.inc:408
Stack trace: #0 /var/www/html/F-RevoCRM/modules/com_vtiger_workflow/VTWorkflowManager.inc(427): VTUpdateFieldsTask->doTask() https://github.com/thinkingreed-inc/F-RevoCRM/issues/1 /var/www/html/F-RevoCRM/modules/com_vtiger_workflow/VTEventHandler.inc(114): Workflow->performTasks() https://github.com/thinkingreed-inc/F-RevoCRM/issues/2 /var/www/html/F-RevoCRM/include/events/VTEventTrigger.inc(143): VTWorkflowEventHandler->handleEvent() …
=> 1244 関連モジュールの値を利用して表現式のワークフローを動作させるとFatalErrorが発生する不具合の修正

layouts/v7/skins/contact/style.css, layouts/v7/skins/inventory/style.css, layouts/v7/skins/marketing/style.css, layouts/v7/skins/marketing_and_sales/style.css, layouts/v7/skins/project/style.css, layouts/v7/skins/sales/style.css, layouts/v7/skins/support/style.css, layouts/v7/skins/tools/style.css, layouts/v7/skins/vtiger/style.less, resources/styles.css
- fix #1243 
1. 意図しないほど細いフォントが一部利用される
1. Noto SansのWindows追加＋ChromeによるFont利用の変更
1. font-familyを定義
表示に関連する場所全て
全ての影響範囲を追いきれているかは不安が残ります。
すぐわかる表示崩れは確認できませんでした。
=> フォントファミリーをヒラギノ＞Noto＞メイリオ＞MSゴシックとなるように修正

modules/CustomView/models/Record.php, modules/RecycleBin/models/Module.php
- fix #1225
案件件等の活動が紐づくレコードについて、一度詳細画面等から削除を行い
ゴミ箱を開き、そこから完全に削除を行うと、完全に削除したレコードと関係ない活動が削除される
1. 内部データの構造変更によるパフォーマンスチューニングの適用時にゴミ箱のリストのみ修正が漏れていた。そのため削除対象のレコードが正常に取得できていなかった。
2. 関連付く親のレコードを削除した際にメールのみを削除するはずが、活動などの他のレコードも対象になっていた
1. 条件に利用するテーブルの指定が正しく行われるように修正
2. メールのみに絞る条件を追加
ゴミ箱での削除処理
=> 1225 ごみ箱削除時に関係のないレコードが消える不具合を修正

layouts/v7/modules/CustomView/resources/CustomView.js
　修正
- fix #1250 [不具合]既存のリストを編集時「項目と並び順の選択」が必須項目が勝手に後ろに移動する
1. 既存のリストを編集時「項目と並び順の選択」が必須項目が勝手に後ろに移動する
1. 「'」を置換する際に選択肢の再セットを行っているが、必須項目はhtml部分が含まれ正しく判定されていなかった。
1.  html部分を除き正しく判定するように修正
- リスト画面
- 編集時
リストの編集時の「項目と並び順の選択」部分
=> #1250 [不具合]既存のリストを編集時「項目と並び順の選択」が必須項目が勝手に後ろに移動する

modules/Calendar/models/EditRecordStructure.php, modules/Dailyreports/models/EditRecordStructure.php, modules/Inventory/models/EditRecordStructure.php, modules/Vtiger/models/EditRecordStructure.php
- fix #1228
1. 項目設定でデフォルト値「0」を設定しても、新規作成画面に「0」がセットされない
1. デフォルト値の存在チェックでempty関数が使用されていた。
　empty関数は0をfalseと判定するため、不具合が発生
1. デフォルト値の存在チェックは != "" で行うように修正
顧客企業の企業形態のデフォルト値を「0」に設定
modules/Calendar/models/EditRecordStructure.php
modules/Dailyreports/models/EditRecordStructure.php
modules/Inventory/models/EditRecordStructure.php
modules/Vtiger/models/EditRecordStructure.php
- [×] 自らテストを行った
- [×] 不必要な変更が無い
- [×] 影響範囲の検討を行った
なし
=> thinkingreed-inc#1228 項目設定で設定したデフォルト値「0」が編集画面でセットされない不具合修正

include/ListView/ListViewController.php, layouts/v7/modules/ModComments/ListViewContents.tpl, layouts/v7/modules/Products/ProductsPopupContents.tpl, layouts/v7/modules/Reports/ListViewContents.tpl, layouts/v7/modules/Vtiger/ListViewContents.tpl
- fix #1150
1.  各モジュールの一覧画面にて、関連項目のtd要素にマウスホバーするとaタグなどが入った状態のtitle属性が表示されてしまう
1.  HTMLが含まれている場合を考慮せずに表示を行っていたから
1.  テンプレートファイルでHTMLを取り除く処理を追加
2. 併せてホバーした際に項目の値ではなくモジュール名しか表示されない点も修正
修正前
修正後
各モジュールの一覧画面にてaタグを含む出力がされる場合
=> 一覧画面にて関連項目のtd要素にマウスホバーするとaタグなどが入った状態のtitle属性が表示されないようにする修正

include/InventoryPDFController.php
- fix #1002 
* PDFテンプレートで原価項目（$quotes-purchase_cost$）が正常に表示されない。
テスト環境（v7.4.0）では原価の値が0と出力されるのではなく、何らかの別の値が表示されてしまうことを確認しました。
一方でv7.3.9およびv7.3.8では所望の値が表示されておりました。
もし、不具合の内容に関して私の認識に誤りがございましたら、ご指摘いただけますと幸いです。
* PDFテンプレートで入力された項目名（$quotes-purchase_cost$）とgetMergeInventoryBlock()で置換される項目名（$quotes-purchasecost$、ハイフン無し）が一致していなかったため、項目が置換されるべき場所で置換されていなかった
* プライベート関数convertFieldName()内でフィールド名を変更（purchasecost -> purchase_cost）し、getMergeInventoryBlock()内で置換されるように変更
* PDFテンプレート
* 修正前の見積書（製品A: 単価￥2,000 原価￥500、製品B: 単価￥1,000 原価￥100）
* 修正後の見積書
PDFテンプレート関係
=> PDFテンプレートで原価項目が出力されない問題の修正

layouts/v7/modules/Settings/LayoutEditor/resources/LayoutEditor.js, modules/Settings/LayoutEditor/actions/Field.php
- fix #1038 
1. 項目設定の一覧画面（項目単体の編集モーダルではなく、項目一覧が表示されている画面）から「必須」「クイック作成」などを変更すると、設定されているデフォルト値が消えてしまう
1. 複数選択肢項目の編集モーダルを開いた際、デフォルト値が設定されている場合にデフォルト値が表示されない
1. 「必須」「クイック作成」などをクイック編集する際、デフォルト値が空として送られている
2. 複数選択肢項目のデフォルト値が編集モーダルを開いたタイミングで削除されてしまっていた
1. デフォルト値が保存時にリクエストパラメータとして送られてきていない場合はデフォルト値を上書きしないように修正
※「空」で保存した場合はリクエストパラメータとして「空」が送られるため、削除可能
2. 複数選択肢項目のデフォルト値が編集モーダルを開いたタイミングで削除しないよう修正
項目設定
=> #1038 項目設定画面において「必須」などをクイック変更した場合にデフォルト値が消える問題などの対応

modules/Calendar/models/FilterRecordStructure.php
- fix #923
カレンダーのリスト画面にてステータス項目を2列表示することができる。
TODOと活動にそれぞれ「ステータス」項目があり、リストに表示する際は２つのステータス項目を統合して表示を行うが、項目に選択画面ではそのことが考慮されていないため
２つの項目のうち、リスト表示する場合はtaskstatus項目にeventstatus項目の値を統合して表示することから、eventstatus項目を選択するステータスの選択肢が表示されないように修正
カレンダーのリスト表示
=> カレンダーリストに「ステータス」が2列表示できてしまう不具合の修正

modules/Calendar/models/ListView.php
- fix #922
カレンダーの一覧リスト画面にて「ステータス」項目でソートをかけた状態にして、「ステータス」項目を非表示にするとレコードが表示されない。
内部でのステータス項目の取り扱い上、2カラムの結果を統合し別名が付けられているため、「ステータス」項目を非表示にした場合、別名のカラムが見つからずレコードの取得に失敗していた。
1. DBのカラムとして、status(TODOのステータス)とeventstatus(活動のステータス)が存在している。
2. リスト画面でレコードを取得する場合、statusとeventstatusは1カラムに統合され、別名が付いた状態で結果として返ってくる。
3. リストでステータスのソートを実行したまま、ステータス項目の列を削除した場合、統合された別名のカラムが存在しないため、レコードの取得に失敗する。
クエリ生成処理に渡す対象のフィールド名が、取得対象のフィールドに含まれているかチェックし、含まれていない場合は、デフォルトの更新日時でソートされるように修正。
カレンダーのリスト表示
=> カレンダーのリストにて「ステータス」でソートをかけたまま「ステータス」を非表示にするとレコードが表示されない

include/QueryGenerator/EnhancedQueryGenerator.php, include/QueryGenerator/QueryGenerator.php
- fix #921
カレンダーのリスト画面にて、ステータス(活動の基本情報ブロック内のステータス)項目でレコードのソートを変更するとレコードが表示されない。
一覧リストに表示する際にレコードを取得するクエリのソート句にて、存在しないカラム名を指定してしまう場合があり、正常に結果が取得されずレコードが0件となっていた。
1.  一覧リスト表示の際は、statusカラム(TODOのステータス)とeventstatusカラム(活動のステータス)をまとめて別名を付け、statusカラムとして取得を行っている。
2. カレンダーのリストには2つの「ステータス」フィールドが存在しており、ラベル名は同じ「ステータス」だが、内部ではtaskstatusとeventstatusに分かれている。
3. 取得クエリを組み立てる処理の中で、taskstatusフィールドでソート条件を指定した場合は、クエリ内のソートカラムの名称がstatusとなるが、eventstatusフィールドでソート条件をしていた場合は、クエリ内のソートカラムの名称がeventstatusになってしまう。
4. その結果、クエリ内に存在しないeventstatusカラム利用してソートをかけようとしたため、クエリの実行が正常に実行されず、レコードの取得に失敗していた。
一覧リストに表示する際にレコードを取得するクエリの生成処理のソート句処理部分にて、正しいカラム名が指定されるように修正。
1. include\QueryGenerator\QueryGenerator.php 
2. include\QueryGenerator\EnhancedQueryGenerator.php 
カレンダーのリスト表示機能
=> カレンダーリスト画面でステータス項目によりソートを行うとレコードが1件も表示されない

layouts/v7/modules/Settings/Workflows/resources/AdvanceFilter.js
- fix #682 #658 
1. #682 の修正でキーボード入力に制限を掛けたが、キーボード入力を有効に戻した。
1. ほかの日付項目などではキーボード入力ができるため、別途日付形式全体での仕様を検討する必要がある。
1. 誕生日の範囲選択におけるキーボード入力を有効に戻した。
日付の範囲選択に対するバリデーションの追加も行う必要がある。
=> #682 キーボード入力を有効に戻す修正

layouts/v7/modules/Settings/Workflows/resources/AdvanceFilter.js
- fix #658 
1. ワークフローの誕生日の「範囲」の機能していなかった。
1. 入力欄のreadonly属性がtrueになっており、valueの値を持つことができていなかった。
1. readonly属性をなくした。
2. キーボードからの入力ができないようにkeydownイベントが発生したらキャッチするようにした。(全角入力の時はキャッチすることができないため入力ができてしまう。)
ワークフローの範囲が設定できる個所では入力ができないようになっている。
入力が全角で行われたときは入力できてしまう。
=> #658 ワークフローの誕生日の「範囲」を入力ができるように修正

modules/Reports/models/Report.php
- fix #844 
レポート作成時、共有相手を「役割と部下」から選択すると、選択した役割の配下のユーザーがレポートを閲覧するときにエラーが起きる。
レコードを選択したときに閲覧権限の有無を確認するsql文と、レコードを取得するsql文の「役割と部下」に関する箇所で矛盾があった。
レコードを選択し閲覧権限の有無を確認するときは選択した役割とその配下に閲覧権限があるが、レコードを取得するときは選択した役割より上の役割で検索をかけていたためレコードを取得できず、閲覧権限があるのにレコードが存在しない状態になっていた。
レコードを取得するsql文の「役割と部下」の箇所を、閲覧権限の確認sql文と同じにした
共有相手を「役割と部下」から選択した際のレコードの閲覧権限
#840 の修正とも合わせてテスト行いました。
=> #844 レポートの共有相手を「役職と部下」から選択したとき、閲覧時にエラーが発生しないように修正

layouts/v7/modules/Users/UserViewHeader.tpl
- fix #816
1. ユーザー画面にて、ユーザー画像が一部表示されない場合がある。
1. ユーザー画像の余白が十分でなかった。
1. ユーザー画像の上部に余白を追加した。
ユーザー画像の表示範囲
=> #816 ユーザー画像が一部表示されない不具合を修正

modules/Calendar/iCal/iCalendar_properties.php
- fix #1237 
1. カレンダーエクスポートでICSファイルを選択したとき、FatalErrorで落ちる
1. PHP7.4以降、curly braceを使った配列アクセスが不可となっていた為
1. 該当コードのcurly brace部分を変更
カレンダーエクスポートの範囲のみ
=> CalendarのICSエクスポートでエラー落ちする不具合の修正

modules/Settings/CronTasks/models/Record.php, setup/scripts/80_Add_CronRetryTimeout.php, vtigercron.php, vtlib/Vtiger/Cron.php
- fix #1278 
1. スケジューラの周期をDB修正で短時間（1分等）に設定する
2. vtigercron.shの周期を短時間（1分等）に設定する
1. スケジューラの周期は最低15分で制御が入っているが、DB修正等で短時間にすると、cronが多重実行されてしまう。
2. 最低周期である15分の場合でもスケジュールインポート等で時間がかかってしまう場合にも発生してしまう。
1. スケジューラが実行中ステータスの場合は同様のスケジューラを実行しないよう修正
2. 何らかの影響で前回処理が実行中ステータスのまま終了してしまった場合を考慮し、リトライタイムアウト時間をスケジューラの設定用DBに追加
スケジューラ
=> fix #1278 cronタスクが同時実行されないように修正

languages/en_us/Events.php, modules/Calendar/actions/FetchOverlapEventsBeforeSave.php
- fix #1291 
活動レコード保存時の重複検出アラートのメッセージ内に、表示を「非公開」に設定した活動レコードのタイトルが表示されてしまう。
表示が「非公開」に設定されている場合の考慮がされていなかったため、重複検出アラートのメッセージにタイトルがそのまま表示されていた。
表示が「非公開」に設定されている場合は、表示内容を以下のように変更する
- タイトルを「予定あり」に置換
- リンクによる遷移ができないように変更
- 活動のカレンダーや一覧表示に準拠するため、開始日時、終了日時、担当者項目の値は非表示にしない
ただし、以下の場合おいては「非公開」にしても「公開」と同じ扱いとする（活動の表示条件に準拠）
- ログイン中のユーザーが活動レコードの担当者に設定されているユーザーである（参加者として登録されている場合も含む）
- ログイン中のユーザーが「システム管理者権限」を持つユーザである
- ユーザーに設定されているプロファイルが「管理者」かつ、プロファイル設定にて「すべて表示」または「すべて編集」のどちらかが有効な場合
- 予定登録者またはシステム管理者など「非公開」でも予定が見られる場合
- 「非公開」設定が適用されるユーザの場合 
画像内の活動レコードは以下の設定で登録（テスト2を変更することでアラートを発生させている）
-  テスト1
　担当と参加者：システム管理者、テスト太郎
　表示：非公開
- テスト2　
　担当と参加者：システム管理者、テスト太郎、テスト次郎
　表示：公開
- テスト3
　担当と参加者：システム管理者、テスト太郎、テスト次郎
　表示：公開
活動レコードの重複チェック機能
=> 活動の重複検出アラートのメッセージに表示「非公開」設定が適用されない

modules/Vtiger/models/Module.php
- fix #1222 
1. クイック入力の日報の箇所でレイアウトが乱れる。
1. [コミット#069e68a](https://github.com/thinkingreed-inc/F-RevoCRM/commit/069e98a4c306f68d93df41e2df49e38e2b388d0f) にてアイコンを表示するメソッドが修正されていることが原因。
　1文字出力であった箇所を、2文字出力する仕様にしている。
1. 1文字出力に戻す。
修正前
修正後
エンプラ版で同様の記述にしているため不要と判断する。
=> #1222　クイック入力の日報アイコンの乱れを修正

include/utils/UserInfoUtil.php
- fix #864 
1. MTGなどの活動に参加したとき、他者の活動は削除できないが、自分の活動は削除できる。
　自分の活動を削除したとき、他者の活動も同時に削除される仕様のため、本来なら他者の活動も削除できるべき。
1. 参加者がいる活動には、個人に紐づけられる子活動と同時に、子活動がどの親活動に紐づいているか管理されている。
　権限チェックの際に、子活動の権限のみ参照しているため、自分の活動しか変更できない。
1. 権限チェックの際に、親活動に紐づいたすべての子活動の変更ができるようにする。
編集するユーザー
他者個人が担当＆自分が参加
編集を保存できる。
削除できる。
他者グループが担当＆自分が参加
編集を保存できる。
削除できる。
他者の非公開のTODOがみえない。
自分が参加していない非公開カレンダーが見えない
公開中のユーザーの予定のみ表示される。
自分が参加していない公開カレンダーが削除できない。
削除不可のモジュールを削除できない
望ましくないですが、既存のコードに合わせてUtilを修正しました。
=> #864 参加者なら他者の活動も削除できる対応
