- languages/ja_jp/Calendar.php
- layouts/v7/modules/Calendar/resources/Calendar.js
- modules/Calendar/views/QuickCreateAjax.php
(cherry picked from commit fbee559d2988e0b8e9e136d69478c2f171e98256)
> カレンダー表示画面に活動コピーを追加

- .gitignore
- config.inc.php.sample
- resources/styles.css
Dockerで構築するとconfig.inc.phpが書き換えられるが、それがworking directoryに残ってしまう。
config.inc.phpは初期セットアップ時に不要であるし、コミットしないほうがセキュアなので、このように対応したい
なお、キャッシュを消さないとworkinig directoryから消えないので、
```
git rm -r --cached config.inc.php
```
を行う必要がある
> config.inc.phpの変更を追わないように修正

- resources/styles.css
> #2 スマホ表示時に詳細画面で項目タイトルが右寄せになる不具合の修正

- languages/ja_jp/Vtiger.php
> fix #31 製品のエクスポートの日本語翻訳修正

- resources/styles.css
> #40 編集画面もラベルは項目に違い右寄せに変更

- layouts/v7/modules/Settings/CustomerPortal/Index.tpl
- pkg/vtiger/modules/CustomerPortal/layouts/v7/modules/Settings/CustomerPortal/Index.tpl
ポータルURLが飛び出すケースを修正。width: auto;を追加し、これでのwidth: 300px;はmin-widthとして指定
> #64 fix ポータルURLが横に飛び出す不具合の修正

- modules/Install/models/InitSchema.php
- modules/Migration/schema/540_to_600RC.php
デフォルトのワークフローがインストール時に英語で生成される
日本語で生成されるように変更
* 文面は私が考えたものなので正確でない可能性あり
> インストール時のデフォルトワークフローが日本語で作成されるように修正

- modules/Migration/models/Module.php
- modules/Migration/schema/732_to_733.php
- vtigerversion.php
#73 vtiger_projecttaskstatusテーブルにある"Canceled[スペース]"を"Canceled"に変更
> #73 vtiger_projecttaskstatusテーブルにある"Canceled[スペース]"を"Canceled"に変更

- modules/Settings/Picklist/actions/SaveAjax.php
- modules/Settings/Picklist/models/Module.php
> #106 選択肢項目を開き、選択肢をホバーした時に選択肢の文字が白になる

- layouts/v7/modules/Settings/Webforms/FieldsDetailView.tpl
- layouts/v7/modules/Settings/Webforms/FieldsEditView.tpl
- layouts/v7/modules/Settings/Webforms/resources/Edit.js
#91 Webフォーム参照フィールドを「cf_xxx」の形で表示してほしい の修正
> #91 Webフォーム参照フィールドを「cf_xxx」の形で表示してほしい の修正

- layouts/v7/modules/Documents/ModuleHeader.tpl
- layouts/v7/modules/EmailTemplates/ModuleHeader.tpl
- layouts/v7/modules/PDFTemplates/ModuleHeader.tpl
- layouts/v7/modules/Portal/ModuleHeader.tpl
- layouts/v7/modules/RecycleBin/ModuleHeader.tpl
- layouts/v7/modules/Reports/ModuleHeader.tpl
- layouts/v7/modules/Rss/ModuleHeader.tpl
- layouts/v7/modules/Settings/ExtensionStore/ModuleHeader.tpl
- layouts/v7/modules/Settings/Vtiger/ModuleHeader.tpl
- layouts/v7/modules/Users/UsersModuleHeader.tpl
#49 でclearfixを削除しそこねていたモジュールを追加で修正
> いくつかのモジュールでヘッダーの一部がズレる問題を修正

- resources/styles.css
- fix #139 
アクティブリストとホバー時の背景色が見ずらい
背景色が#F7F7F7に指定されていた
背景色を#eeeへ変更。これは上のツールバーをホバーした時の背景色と同じ
各モジュールのリストの背景色(アクティブ・ホバー時)
> #139 選択しているリストの色を変更する修正

- modules/Events/models/Record.php
- fix #173 
1. 関連の活動に削除されて存在しない顧客担当者が残り続ける.
1. 関連クエリで該当関連レコードの削除フラグを確認していない
1. 該当のcontactsの削除フラグを確認するようにクエリを修正
活動の関連の顧客担当者
> #173 削除した顧客担当者が関連の活動に残る問題を修正

- layouts/v7/modules/CustomView/EditView.tpl
- modules/CustomView/views/EditAjax.php
- fix #199 
1. リストの複製をすると、項目と並び順の選択 に余計な項目が設定される
1. 新規作成時に自動追加される項目が複製したリストに追加されてしまっていた。
1. 操作が複製であるか判定できるようにした。
リストの新規作成/複製/編集時の項目
> #199 リストの複製をすると、項目と並び順の選択 に余計な項目が設定される箇所の修正

- modules/Migration/schema/720_to_730.php
- setup/scripts/18_Update_InviteeParentFromInviteeTable.php
- fix #130
1. F-RevoCRM6.Xから7.Xにマイグレーションした後、F-RevoCRM6.Xにて作成していた活動を削除すると、全活動が削除される。
1.  マイグレーションファイルを追加・詳細は #130 参照
データベース
> #130 vtiger_activityのinvitee_parentidを更新するマイグレーションファイルを追加

- include/InventoryPDFController.php
- languages/ja_jp/Vtiger.php
- modules/PDFTemplates/models/Module.php
- fix #159 
エクスポートした見積PDFの値引き額（貴社特別値引き）に反映されない。
小計には「見積:小計」ではなく「見積:税引前合計」を使う必要があったため。
総割引額(合計金額からの割引額)をテンプレート編集画面にて追加できるようにし、
テンプレートに以下の変更を加えた。
- 貴社特別値引きの行を削除
- 品目の割引合計の行を追加。金額には「見積:値引き額($quotes-discount_amount$)」
- 総割引額の行を追加。金額には「見積:総割引額($quotes-discount_amount_final$)」
- 小計の行の金額を「見積:税引前合計($salesorder-pre_tax_total$)」に変更
**【変更前】**
**【変更後】**
> エクスポートした見積PDFの値引き額（貴社特別値引き）に反映されない箇所の修正

- layouts/v7/modules/Settings/Webforms/EditView.tpl
- layouts/v7/modules/Settings/Webforms/uitypes/String.tpl
- layouts/v7/skins/marketing/style.css
- modules/Settings/Webforms/models/Record.php
- modules/Settings/Webforms/views/Edit.php
- fix #137 #122 
1. webフォーム作成画面にて複製の項目がなかった
2. 編集不可の項目(WEBフォーム名など)が編集可能のように見えていた
1. 複製の項目を追加
2. readonlyテキストに対してのcssを適応させた
- webformのreadonlyテキストの背景色など
- webform編集画面
> Webフォームを複製できるように修正

- modules/Accounts/models/Module.php
- fix #348 
1. 顧客企業の概要欄での活動取得スピードを高速化
1. ORの検索クエリが遅い
1. UNION ALLで繋げる形でSQLを発行
顧客企業の活動取得処理周りのみ
> fixed #348 顧客企業の概要欄での表示スピードの向上

- layouts/v7/modules/Vtiger/RelatedActivities.tpl
- modules/Contacts/models/Module.php
- modules/Dailyreports/models/Module.php
- modules/Vtiger/models/Module.php
- resources/styles.css
- fix #228
1. 概要画面の関連の活動の表示が少ないので増やしたい
1.  開始日時・担当・活動タイプ・詳細内容をテーブル形式で表示するように修正
- [] 自らテストを行った
* スマホ画面でタイトルが長いとはみ出る不具合あり
* 顧客企業以外もmodules\Accounts\views\Detail.phpで生成されている
* 複数のモジュールでのテストが不十分
> #228 概要画面の関連の活動の表示を修正

- data/CRMEntity.php
- languages/en_us/Vtiger.php
- languages/ja_jp/Vtiger.php
- layouts/v7/modules/Import/ImportStepThree.tpl
- modules/Import/actions/Data.php
- modules/Import/readers/FileReader.php
- fix #285
1. タグのインポートができなかった
1. タグのインポートする機能がなかった
1. タグをインポートできるように変更(複数インポートする場合、|##|で区切る)
2. vtiger_import_xにタグはvarchar(500)に設定する
vtiger_freetagged_objectsとvtiger_freetagsを使用した箇所(インポートしたタグ関連)
> タグのインポートができない箇所の修正

- layouts/v7/modules/Accounts/DetailViewHeaderTitle.tpl
- layouts/v7/modules/Contacts/DetailViewHeaderTitle.tpl
- layouts/v7/modules/HelpDesk/DetailViewHeaderTitle.tpl
- layouts/v7/modules/Invoice/DetailViewHeaderTitle.tpl
- layouts/v7/modules/Leads/DetailViewHeaderTitle.tpl
- layouts/v7/modules/Potentials/DetailViewHeaderTitle.tpl
- layouts/v7/modules/Products/DetailViewHeaderTitle.tpl
- layouts/v7/modules/PurchaseOrder/DetailViewHeaderTitle.tpl
- layouts/v7/modules/Quotes/DetailViewHeaderTitle.tpl
- layouts/v7/modules/SalesOrder/DetailViewHeaderTitle.tpl
- layouts/v7/modules/Vendors/DetailViewHeaderTitle.tpl
- layouts/v7/modules/Vtiger/DetailViewHeaderTitle.tpl
- modules/Vtiger/views/Detail.php
- resources/styles.css
Reverts thinkingreed-inc/F-RevoCRM#308
> Revert "[WIP]背景透明化のcssがデフォルトのアイコンにも適応されてしまっていたので修正"

- modules/Migration/schema/734_to_735.php
- fix #360 
1. 作成日時と更新日時のtype_of_dataがDとなっていることで、検索条件の（等しい）で当たらない現象が起きていた
1. type_of_dataが適切ではない
1. マイグレーションスクリプトで修正
日報モジュールのみ
> fixed: #360 日報モジュールの作成日時と更新日時のtype_of_dataをDTに変更するMigrationスクリプトを追加

- modules/Migration/models/Module.php
- modules/Migration/schema/735_to_736.php
- fix #373 
1. マイグレーションで指定のSQLを流す
- [] 自らテストを行った
- [] 不必要な変更が無い
> reqest #373 契約モジュールのテーブルにprimary keyの設定

- languages/ja_jp/Documents.php
- layouts/v7/modules/Documents/ListViewRecordActions.tpl
- fix #353 
1. ドキュメントのリスト表示の翻訳漏れ
> fix #353 ドキュメントのリスト表示の日本語訳

- vtlib/Vtiger/FieldBasic.php
- fix #364 
1. レポート等で結合条件として使われるので、INDEXがないと遅くなる
1. uitype10のインデックスが作成されていなかった
1. インデックスを作成する修正
> #364 関連項目を追加した際にINDEXを付与して欲しい

- modules/Calendar/Activity.php
- fix #358
1.  見込み客,顧客担当者,顧客企業,案件モジュールにおいて,最終活動日フィールドが最後に関連づけられた活動の終了日となっている
1. 活動のステータスが完了になったときその活動の終了日を最終活動日とするため,複数の活動があったときその前後を考慮していない
2. 顧客企業モジュールは顧客企業に直接紐付いた活動だけでなく,関連の顧客担当者と案件の活動も(あたかも直接紐付いているかのように)表示する.最終活動日は間接的に紐付いた活動無視している
1. 活動の新規作成・更新時には常に最終活動日を更新するように変更
2. 変更された活動だけでなく,親レコードに関連するすべての活動から最終活動日を設定
3. 顧客企業の関連モジュールの活動を含んで最終活動日を設定
見込み客,顧客担当者,顧客企業,案件モジュール
> #358 活動のステータスを完了にしたとき,親レコードの最終活動日の更新条件を修正

- modules/Import/helpers/Utils.php
- fix #411 
1. ファイル拡張子が大文字のCSVの場合、インポートができない。
> fix #411 大文字拡張子のインポート

- docker/mysql/Dockerfile
- fix #469
1. MySQLのDockerをBuildすると有効期限関連のエラーが表示される
1. #469 のログ参照、鍵の有効期限
1. 必要な鍵情報を取り込むようにDockerfileを修正
MySQLのBuildのみ
> fix #469 MySQLのコンテナがビルドできない不具合の修正

- languages/en_us/Vtiger.php
- languages/ja_jp/Vtiger.php
- layouts/v7/modules/Vtiger/Comment.tpl
- layouts/v7/modules/Vtiger/CommentThreadList.tpl
- layouts/v7/modules/Vtiger/RecentComments.tpl
- layouts/v7/modules/Vtiger/resources/Detail.js
- modules/Vtiger/actions/DeleteAjax.php
> #328 コメント削除機能の実装 (with @pavish69)

- layouts/v7/modules/Vtiger/Comment.tpl
- layouts/v7/modules/Vtiger/CommentThreadList.tpl
- layouts/v7/modules/Vtiger/RecentComments.tpl
- layouts/v7/modules/Vtiger/resources/Detail.js
- modules/Vtiger/actions/DeleteAjax.php
- fix #328 
- wip #383 
1. コメントを削除できない
1. コメントの削除機能の追加
2. コメントを削除できる人を限定する機能の追加（コメント投稿者とシステム管理者のみ削除可能）
▲システム管理者でログインしたとき
▲システム管理者以外でログインしたとき
> fixed#328 コメント削除機能の追加

- modules/Contacts/Contacts.php
- setup/Setup.php
- setup/scripts/58_Fix_Infportalmail_Tojp.php
> #385 ポータルユーザーへのアカウント通知メールがインストール時に日本語になるように修正

- modules/Contacts/Contacts.php
- setup/Setup.php
- setup/scripts/58_Fix_Infportalmail_Tojp.php
- fix #385 
1. Contactsのportalをonとした際に送られてくるメールがすべて英語になってしまう。
1. 
1. 初回インストール時にメールテンプレートのデータベースを日本語に書き換えるように修正。
ポータルがオンになった際に自動で送られるメールテンプレートに関する範囲
> #385 Contactsのportalをonとした際に送られてくるメールを日本語に修正

- layouts/v7/modules/Vtiger/uitypes/File.tpl
- layouts/v7/modules/Vtiger/uitypes/Image.tpl
- resources/styles.css
- fix #453
1. 画像をアップロードした際にプレビューを表示して欲しい
1. [jQuery MultiFile](http://lampspw.wallonie.be/dgo4/tinymvc/myfiles/plugins/multifile-2.2.1/docs.html)でclassに`with-preview`を追加
2. プレビューのスタイルを一部修正
* 製品の編集
* コメント
* 製品画像では画像以外はアップロードできない
* 画像以外はプレビューされない
> #453 画像をアップロードした際にプレビューが表示されるように修正

- modules/Potentials/models/Module.php
- fix #517 
1. ダッシュボードの案件（ステージ別）が表示されない。
1. MYSQLの文法が間違っていた。
1. 文法の修正
2. ダッシュボードのトップの案件において金額が0円の案件も表示されるよう修正
ダッシュボードの案件の範囲
> #517 ダッシュボードの案件が表示されない不具合の修正

- include/Webservices/EntityMeta.php
- fix #559 
1. 非表示の必須項目が存在する場合に、API経由でモジュールの作成を行うとエラーが発生する。FrevoCRMからの作成は問題なし
1. 非表示の必須項目が作成されてしまうケースが想定されていなかった。
※本来FrevoCRMからは作成できない。SQL等で項目が作成された場合などに発生する。
1. 項目の判定に表示/非表示の条件を追加
- APIのエラー判定
> #559 WebAPIで非表示の項目の必須入力チェックがされないようにする修正

- include/Webservices/VTQL_Parser.php
- fix #558 
1. WebAPIの最大取得件数が100であった
1. 制限を100から1000へ変更
- WebAPIの取得件数上限
> #558 WebAPIの最大取得件数を100から1000へ増やす修正

- modules/ServiceContracts/ServiceContracts.php
- fix #514 
1. 契約モジュールをAPI経由で作成すると処理が遅い。
1. calculateProgress()内で$this->dbを使っている。
1. あらかじめ宣言されている「global $adb;」を利用し、calculateProgress()内の$this->dbを$adbに書き換える。
<変更前>
＜変更後＞
契約モジュールの作成
> #514 API経由で契約を作成すると処理が遅い問題を修正

- modules/ServiceContracts/ServiceContracts.php
- fix #616 
1. 契約＞「契約の追加」をクリック
2. 必須項目を入力して保存→エラー発生
1. #616での修正にて$adbが宣言されていなかった
1. $adbの宣言追加
> 契約を作成するとシンタックスエラーが発生する箇所の修正

- libraries/jquery/multiplefileupload/jquery_MultiFile.js
- fix #667
1. Mutifile.jsの特定の箇所でエラーが出ていた
1. 変数の扱いが正しくなかった（ライブラリ内部の問題）
1. マイナーバージョンアップで対応
複数ファイル選択の箇所だが、マイナーバージョンアップであるため問題ない認識
> #667 リストからメール送信ダイアログを開くときにエラーが出る不具合の修正

- include/Webservices/VtigerCRMObjectMeta.php
- fix #675
1. スペースが無いことによるSQLのSyntax Error
1. スペースが無いことによるSQLのSyntax Error
1. スペースを足す
動くようになったことによる影響はあるかもしれない
> fix #675 一般ユーザーでフィールド取得SQLがエラーとなっていた不具合の修正

- modules/com_vtiger_workflow/tasks/VTUpdateFieldsTask.inc
- fix #679
1. 内部のコードが一部混入していた
1. 不要な処理の削除
ワークフローの値の更新
> #679 fix 誤って関係ないコードもコミットしてしまっていたため修正

- modules/Vtiger/actions/ExportData.php
でも##  関連Issue / Related Issue
- fix #653 
1. エクスポート時、ユーザーの関連項目が正常にエクスポートされない。
1. モジュール名を取得している処理にて、複数モジュールに同じ項目名の項目があると、クエリエラーが発生していたため。
1.項目名だけでなく、モジュールIDでも判定するように変更。
エクスポート
> #653 関連のユーザーをエクスポートする際、異なるデータがエクスポートされる。

- modules/com_vtiger_workflow/expression_engine/VTExpressionEvaluater.inc
- modules/com_vtiger_workflow/expression_engine/VTExpressionsManager.inc
- fix #319 
1. 生年月日から年齢を表示できるようにする。
1. ワークフローに「age」を追加し年齢を更新できるようにした
ワークフローのage関数の範囲
> #319 年齢を表示できるようにする

- config.template.php
- fix #687
1. config.inc.phpに指定がないので、インストール時に付与するように修正
1. config.template.phpに追記
> インストール時にスケジュールワークフローの最大件数をconfig.inc.phpで指定するように修正

- .github/ISSUE_TEMPLATE/translation-report.md
> 翻訳漏れ報告用のIssueテンプレートを追加

- include/ComboStrings.php
- fix #90 
1. 製造業者名の選択肢の名前の例がわかりずらい。
1. 
1. インストール時に作成される選択肢の例の内容を変更した。
あまり重要な問題ではないと考えられるためため現在インストールしている方の選択肢まで変更する使用にはなっていない。次回インストール時がら選択肢が変更される。
> #90 製造業者名の選択肢の例の名前を変更

- includes/runtime/LanguageHandler.php
- fix #560 
1. モジュールを指定した文語変更がwebAPIを使ったときに反映されない問題があった。
> 修正前
> 修正後
webAPIを用いる箇所
webAPIを通してモジュール詳細情報の取得をすることで文語変更されているか検証した。
> #560 webAPI取得されるモジュール名が文語変更機能を通るように修正

- resources/styles.css
- fix #459 
1. カレンダーのリストビューの検索欄のスタイルが統一されていなかった。
1. 
1. 「timepicker-default」の枠のスタイルを修正
「timepicker-default」を利用している入力欄など。
> #459 カレンダーの検索欄のスタイルを修正

- modules/Reports/Reports.php
- fix #694
1. 選択肢に表示するようSQLを修正
> uitype10の関連項目からレポートの副モジュールを選択できるように修正

- libraries/jquery/VtJqplotInterface.js
- fix #119
1. 外側に凡例を表示するように設定していたため、枠外に表示されていた
1. グラフの表示方法を変更
> ダッシュボードでレポートのウィジェットを出すと、凡例が外に飛び出してしまう不具合の修正

- modules/Calendar/Activity.php
- fix #508
1. 活動であるユーザーの活動を別のユーザーに切り替えても、元のユーザーを消すことができない
1. 招待ユーザー管理周りで削除がなかった
1. 内部の修正を適用、Inviteeの中身を整理するように修正
> 活動の担当を変更しても元のユーザーの予定を残さないように修正

- layouts/v7/modules/Calendar/uitypes/OwnerFieldTaskSearchView.tpl
- fix #280 #431 
get_user_arrayによる修正は影響範囲が広いためテンプレート側で修正した。
1. selectタグの先頭に現在のユーザーが来るようにした。
2. 「自分」をユーザ名に変更する
TODOリストの担当欄だけに影響する
> テンプレートによる修正

- include/InventoryPDFController.php
- include/utils/EditViewUtils.php
- include/utils/InventoryUtils.php
- languages/ja_jp/Products.php
- layouts/v7/modules/Inventory/LineItemsDetail.tpl
- layouts/v7/modules/Inventory/partials/LineItemsContent.tpl
- layouts/v7/modules/Inventory/partials/LineItemsEdit.tpl
- layouts/v7/modules/Inventory/resources/Edit.js
- modules/Inventory/actions/GetTaxes.php
- modules/Inventory/models/Record.php
- modules/Migration/schema/736_to_737.php
- fix #620 
- fix #625 
消費税を「個別」に変更した際、小計、合計、消費税の値が正しく表示されていなかった
請求、受注、見積、発注
> #620 軽減税率に対応した請求書を発行できるよう修正

- layouts/v7/modules/Vtiger/uitypes/MultiPicklist.tpl
- layouts/v7/modules/Vtiger/uitypes/Owner.tpl
- layouts/v7/modules/Vtiger/uitypes/Picklist.tpl
- fix #735
選択肢を利用不可にした場合、編集画面で選択肢項目が空欄になる
選択肢を利用不可にする際、置換先の選択肢を選択するように修正
選択肢項目全般
> #735 選択肢を利用不可にする際、置換先を選択するように修正

- layouts/v7/modules/Vtiger/resources/Field.js
- modules/Calendar/Activity.php
> [不具合]複数選択肢を鉛筆マークから編集すると役割による制限が効かない #822

- modules/Migration/models/Module.php
- modules/Migration/schema/736_to_7381.php
- modules/Migration/schema/738_to_7381.php
- vtigerversion.php
- fix #851 
1.
1. getAllowedMigrationVersionsに3.7.7と3.7.8が追加されていなかった。
1. getAllowedMigrationVersionsに3.7.8と3.7.8.1を追加した。
2. 738_to_7381のマイグレーションファイルには736_to_737と737_to_738のマイグレーションファイルを合わせたものが入っている。
3.7.6からバージョンアップしていない人は736_to_738のマイグレーションファイルがないため738_to_7381のマイグレーションのみ実行される。
バージョンアップしていた人も736_to_737と737_to_738のマイグレーションは実行されていないはずなので、738_to_7381が実行されるようにした。
737_to_738のマイグレーションファイルは使わなくなるので削除してもいいかもしれません。
> #851 Migurationを実行されるようにする修正

- modules/Calendar/Activity.php
- fix #774
1. Issueに記載の通り
1. 実装時の考慮漏れ
1. 日またぎのパターンを追加
なし
活動登録時の期間、期間(分)の計算
なし
> #774 日またぎの終日の活動の期間が計算されていない問題を修正

- layouts/v7/modules/Reports/resources/Detail.js
- fix #829 
* レポートの条件保存ボタンが条件を変更しても表示されない
1. 保存後にイベントの登録が行われていなかった
1. 保存後にregisterConditionBlockChangeEvent()を呼び出すように修正
* 「飛び込み」から「既存顧客」に変更した後。保存ボタンが表示されている
* レポートの条件保存のところの挙動
> #829 レポートの保存ボタンが表示されるように修正

- layouts/v7/modules/Calendar/resources/Calendar.js
- modules/Calendar/actions/Feed.php
- fix #742 
一覧画面ではなくカレンダー上から予定を確認する場合が多いため、カレンダー上から他ページとの連携が取れないのは不便
活動のポップアップ上に表示されている担当者と顧客企業等の関連モジュールから詳細ページに飛べる機能を追加した
カレンダーのポップアップ
> #742 カレンダー上の予定から、顧客企業や担当者などの関連リンクに飛べる機能を追加

- languages/ja_jp/Vtiger.php
- なし
1. 「重複の検出」を制御するはずのプロファイルの項目名が「複製」になっており、あたかも複製の作成が制御されるように見える
1. 翻訳ミス
1. 翻訳ファイルの修正
before
after
翻訳のみ
> trans: プロファイルの権限は「複製」の作成を制御するものではなく、「重複の検出」を制御するための権限であるため、翻訳を修正

- layouts/v7/modules/Users/ChangeUsername.tpl
- なし
1. ユーザー管理→ユーザー名の変更において、「新しいユーザー名」のinputにCSSが当たっていない
1. クラスの適用漏れ
1. inputタグにform-control及びinputElementクラスを付与
before
after
表示のみ
> ユーザー名の変更モーダルの「新しいユーザー名」にinputElementクラスが当たっていなかったので追加

- layouts/v7/modules/PDFTemplates/templates/QualifiedInvoiceTemplate.tpl
> #887 適格請求書のテンプレートを追加

- docker/php/Dockerfile
- include/utils/utils.php
- modules/Install/models/Utils.php
- modules/Install/views/Index.php
- modules/Migration/schema/540_to_600RC.php
- modules/Migration/schema/600_to_610.php
- modules/Migration/schema/610_to_620.php
- modules/Migration/schema/700_to_701.php
- schema/DatabaseSchema.xml
- setup/scripts/10_Delete_Modules.php
- vtlib/Vtiger/PackageImport.php
- vtlib/Vtiger/PackageUpdate.php
- fix #908
1. DockerがPHP8に対応していない
2. インストーラーがPHP8対応により劣化
思い切って上書きしすぎた。
> PHP8対応でDocker未対応及びインストーラーが動作していない #908 

- README.md
1. README.mdのheadlesschromeの説明のリンクが間違っていた。
1. リンクの修正
プルリクで出すほどじゃないですが、出しておきます。
> README.mdのリンク先の間違いの修正

- modules/Import/actions/Data.php
- fix #591 
1. 活動のインポートで「00:00:00」が含まれるとエラーとなってしまう。
1. 条件が間違っていた。
1. if($fieldValue == null || $fieldValue == '00:00:00') {
→　if($fieldValue == null) {
活動のインポートでのエラー表示
> #591 活動のインポートでの不具合を修正

- modules/Vtiger/models/Tag.php
- fix #728
同名の個人タグが存在すると削除したときに、同名の他タグも消えてしまう
タグを作成するときに同名のタグが存在する場合、既存の同名タグのIDを使用していた。
タグを作成する際、同名のタグが存在しても別IDで新たなタグとして作成するように修正
タグ
> #728 作成するタグが他タグと同名でも、別IDになるように修正

- modules/Assets/views/Detail.php
- fix #968 
1. 資産・レンタル管理を新規作成するとFatal Errorが発生する
1. Vtiger_Detail_Viewで定義されている関数の引数と一致していない。PHP8から厳密なチェックとなったため発生した。
1. 引数に$displayを追加
資産・レンタル管理
> 資産・レンタル管理を新規作成するとFatal Errorが発生する箇所の修正

- modules/Import/actions/Data.php
- fix #712 
インポート時にマージを選択し、マッチング項目で複数件マッチした場合、
最初の1件を残して他のマッチしたレコードが削除される。
マッチング項目でマッチした2件目以降を削除する処理が存在する
マッチング項目でマッチした2件目以降を削除する処理を削除
マージインポート
> #712マージインポートをしても、重複するレコードが自動で削除されないよう修正

- layouts/v7/modules/Vtiger/resources/Detail.js
- fix #
1. 
1. 
1. 
- [] 自らテストを行った
- [] 不必要な変更が無い
> #1026 [不具合]チケットの項目「解決方法」の更新ができない対応

- modules/Calendar/actions/Feed.php
- fix #1050 
1. カレンダー取得が未来予定が増えるほど遅くなり、データ通信量が増える
1. カレンダー表示上、終わりの日付から、未来の予定をすべて取得してしまっていた
1. 予定の終わり日が、カレンダー表示における開始日よりも未来で、終了日よりも過去であることも追加で検証する
カレンダーの予定取得範囲
> #1050 カレンダーの取得が遅い問題を修正

- modules/Import/actions/Data.php
- fix #1095 
1. 2回以上に分割して行われるスケジュールインポートにおいて、スキップ・上書き・マージ等が発生するとインポートが進まなくなる場合がある
1. スケジュールインポートにおいて、前回のインポート処理が完了しているかどうかの判断を、以下の条件で行っていた
* インポート仮テーブル（vtiger_import_ユーザーID）のstatusが1のものをcountする
* countした結果をmodules/Import/models/Config.phpに定義されているimportPagingLimit（スケジュールインポートにおける1回の最大インポート件数）で割り、割り切れる場合は前回インポートが完了していると判断する
2. statusが1というのはインポートにおいて「レコードの作成完了」を表しており、スキップ・上書き・マージの場合はそれぞれ別の値が設定される状態となる
3. 結果として、分割してスケジュールインポートが行われる場合、スキップ・上書き・マージが1件でも発生するとそれ以降のスケジュールインポートが実行されなくなってしまっていた
1. インポート仮テーブル（vtiger_import_ユーザーID）にて、前回のインポートが完了したかの判断をstatusが1のものではなく、0以外のものを全てcountした結果を使用するように変更
デフォルトでは10001件以上のインポート処理
※modules/Import/models/Config.phpにimportPagingLimitより大きい場合のインポート処理
> #1095 スケジュールインポートにおける前回処理のcount条件を変更

- layouts/v7/modules/Calendar/resources/Calendar.js
- modules/Calendar/actions/Feed.php
- modules/Migration/schema/740_to_741.php
- setup/Setup.php
- setup/scripts/78_Add_smcreatorid.php
- fix #1092
1. カレンダーで活動をマウスオーバーした時に、作成者を表示させる。
1. カレンダーで活動をマウスオーバーした時に、作成者を表示させる。
> #1092 カレンダーの登録者表示機能を修正

- modules/CustomView/CustomView.php
- fix #1106
他ユーザーから共有されたリストをデフォルトに設定しても画面に反映しない。
「全てのユーザー」で共有した場合は発生しない。
共有されたリストのデフォルト設定へのチェックは維持されている。
リストのデフォルト表示する際に CustomView.php#isPermittedCustomView で閲覧できるかチェックする。
上記のチェックで共有されたリストであっても作成者以外は権限がないような判定になっているため表示できていなかった。
※詳細
- 「カスタムリスト、かつ一部のユーザーに共有」状態ではvtiger_customviewのstatusが1 (プライベートリスト)
- statusが1or2の場合は以下のSQLでリストの閲覧権限をチェック
```
select
vtiger_users.id 
from
vtiger_customview 
inner join vtiger_users 
where
vtiger_customview.cvid = {デフォルト指定したcustomlistのID} 
and vtiger_customview.userid in ( 
select
vtiger_user2role.userid 
from
vtiger_user2role 
inner join vtiger_users 
on vtiger_users.id = vtiger_user2role.userid 
inner join vtiger_role 
on vtiger_role.roleid = vtiger_user2role.roleid 
where
vtiger_role.parentrole like '% {カレントユーザーの上位ロール} %'
)
```
- 上記SQLで vtiger_cv2users, …
> #1106 共有リストがデフォルト表示しない不具合の修正

- modules/Leads/models/Module.php
- modules/Vtiger/models/Module.php
- fix #1115
リードのウィジェット各3種で条件を指定するとデータが表示されなくなる
#1108 の修正漏れ
条件を指定した際に発行されるSQLが、#1108 で利用しなくなったテーブルを参照するようになっていたため
syntax errorが発生していた。
条件指定時に発行されるSQLが利用しているテーブルを利用するように変更
- リード（業界別）
- リード（ステータス別）
- リード（紹介元別）
> #1115 リードウィジェットで条件を指定してデータを表示させる修正

- modules/Calendar/CalendarCommon.php
- fix #1127 
1. ユーザーの情報を取得するときに存在しないプロパティを指定してエラーが発生する
2. ICSファイルを保存する際、活動に/が含まれているとファイルの書き込みができずにエラーが発生する
1. 同上
1. ユーザー情報を取得する際の呼び出し方を変更
2. ICSファイル名をエスケープするように修正
> Fix/1127 ICSファイルを生成する際にエラー落ちする不具合の修正

- modules/HelpDesk/models/Module.php
- modules/Potentials/models/Module.php
- modules/Vtiger/helpers/Util.php
- fix #1120 
1. 一例として、「ステータス毎のチケット」を登録日時範囲で絞り込むと表示されない
2. 案件のレコードを削除すると履歴ウィジェットが表示されなくなる
1. クエリにおいて、カラムの参照元テーブルが曖昧になっていた
2. レコードの存在判定を行う関数Vtiger_Util_Helper::CheckRecordExistance()において、クエリのインデックス番号が指定されていなかった
1. 各カラムにテーブル名を追加
2. 0を指定 $adb->query_result($result, 0, 'deleted');
* 修正前（履歴ウィジェットとステータス毎のチケット）
* 修正後
ウィジェット
> ウィジェット関係のSQLが劣化し、正常に表示されないものが存在する不具合の修正

- modules/Vtiger/models/SummaryRecordStructure.php
- fix #1052
ユーザが追加したモジュールにて、主要項目に設定された項目が一つも存在しない場合、レコードの詳細画面の概要タブまたは詳細タブの表示でFatal Errorが発生する。
1. 追加したモジュールの項目に「主要項目」の設定がされていない場合、対象の項目が存在しないためVtiger_Field_Modelのインスタンスの取得に失敗する
2. Vtiger_Field_Modelのインスタンスが取得できていないに関わらず、Vtiger_Field_Modelのメソッドを実行しようとしてFatal Errorが発生する
1. Vtiger_Field_Modelのメソッドを実行する前に、Vtiger_Field_Modelのインスタンスが正常に取得できているかチェックする処理を追加
各モジュールの概要、詳細表示
> Vtiger_Field_Modelのインスタンスであることを確認するように修正

- layouts/v7/modules/Vtiger/resources/Utils.js
- resources/app.js
- fix #1143
1. 修正の影響で設定画面にて、選択肢項目に選択肢が追加できなくなった
1. 複数選択肢で選択肢が自由に増やせる状態だったので修正を行ったが、追加できる必要がある設定画面まで追加不可になっていたため
1. 設定画面では選択肢の追加機能を無効化しないように修正
複数選択肢項目
> 設定画面のみ選択肢の追加不可設定を解除

- layouts/v7/modules/Reports/resources/ChartEdit3.js
- layouts/v7/modules/Reports/resources/Edit3.js
- fix #1164
レポートを新規作成する際に、保存ボタンを連続クリックすると
同じレコードを複数登録できてしまう。
1. submit時に二度押し防止対応がされていなかった
1. 保存ボタンを押下した後にボタンを非活性にする
レポートの保存
> #1164 レポートの新規登録の二度押し防止対応

- layouts/v7/modules/Calendar/resources/Calendar.js
- fix #1189
関連Issueを参照
修正時にfalsyな値が入る可能性の考慮が漏れていた
falsyな値が来た場合に、後続のHTML出力処理を行わないように修正
カレンダーの月表示
> 1189 falsyな値が渡ってくる可能性を考慮した実装に変更

- layouts/v7/modules/Inventory/partials/LineItemsContent.tpl
- fix #1214 
関連タブから発注レコードの追加を行うとエラーが表示され、作成画面が表示されない。
金額の計算時に0除算を行っていたため
0の場合後続の処理を行わずデフォルトの値を出力するように修正
発注の作成、編集画面
> 関連タブから発注レコードの追加ができない不具合の修正

- layouts/v7/lib/jquery/fullcalendar/fullcalendar.css
- layouts/v7/modules/Calendar/resources/Calendar.js
- modules/Calendar/actions/Feed.php
#1183
1. 阿部長様より、カレンダー上にて、スケジュール最終更新者を追加したい要望あり。
カレンダーに活動の最終更新者を表示するように修正
カレンダーの表示デザインが崩れる可能性
- [☑] 自らテストを行った
- [☑] 不必要な変更が無い
- [☑] 影響範囲の検討を行った
> カレンダーに活動の最終更新者を表示するように修正

- .github/workflows/manage_jira_issues.yml
> TR社内管理用github Actionsの登録 JIRA登録時にbodyをエスケープ＆Markdown → JIRA Wikiへ変換するよう修正

- layouts/v7/skins/inventory/style.css
- layouts/v7/skins/marketing/style.css
- layouts/v7/skins/marketing_and_sales/style.css
- layouts/v7/skins/project/style.css
- layouts/v7/skins/sales/style.css
- layouts/v7/skins/support/style.css
- layouts/v7/skins/tools/style.css
- layouts/v7/skins/vtiger/style.less
- fix #1263 
1. スクロールバーが表示されてしまう
1. chromeのフォント周りが変わったことが影響している可能性が高い
1. overflow: hiddenを追加（本来は高さが良い感じに変わるべき）
> font問題でスクロールバーが表示される環境があるため、修正

- layouts/v7/modules/Users/Login.tpl
- fix #1258 
1. login.tplに不具合が残っていた部分を修正。
1. 変換ミス
1. JSのvtanslate部分の'と"の修正
> thinkingreed-inc#1258 login.tplのvtranslate部分の不具合を修正

- modules/Settings/Roles/models/Record.php
- fix #1044 
1. 役割の並び順が不定（作成順と思われる）
1. 並び順を指定する構文(ORDER BY)が抜けていた
1. rolenameに従って並び順を変更するように修正
* デフォルトのCOLLATION（utf8mb3_general_ci）を使用して並べ替え
* utf8mb3_unicode_ciを使用することでカタカナも含めて並べ替えを行うことができるが、
* utf8mb4へ移行時に再度修正が必要になるのでデフォオルトCOLLATIONを使用する
* 左図：修正前（作成順・不定）、右図：修正後（utf8mb3_general_ci）
* システム設定＞ユーザー管理＞役割
* ユーザー作成・編集画面やユーザー一覧画面の検索欄は**影響範囲外**（並び順が修正内容と異なる）
> 役割の並び順が不定である不具合の修正

- data/CRMEntity.php
- fix #1016 
1. 項目でない関連付けが行われているものを紐づけると遅くなっている
1. OR で JOIN しているため
1. OR を使用せず結合するように修正
項目でない関連付けが行われているものを紐づけたレポート
> #1016 [要望]レポート：項目でない関連付けが行われているものを紐づけると遅くなっている

- include/Webservices/Create.php
- include/Webservices/VtigerCRMObjectMeta.php
- languages/en_us/Vtiger.php
- languages/ja_jp/Vtiger.php
- layouts/v7/modules/Settings/Workflows/Tasks/VTCreateEventTask.tpl
- layouts/v7/modules/Settings/Workflows/Tasks/VTCreateTodoTask.tpl
- modules/com_vtiger_workflow/tasks/VTCreateEventTask.inc
- modules/com_vtiger_workflow/tasks/VTCreateTodoTask.inc
- fix #1274 
1. ワークフローで活動、TODOを追加するときに、ログインユーザーを担当として作成できるようにする
1. 新たに「ログインユーザー」という特殊な選択肢を追加し、この場合にログインユーザーIDを含めるように修正
Workflowで活動、TODOを作る箇所のみ
> #1274 Feature/add own activity for workflow

- languages/en_us/Settings/Parameters.php
- languages/ja_jp/Settings/Parameters.php
- languages/ja_jp/Settings/Vtiger.php
- layouts/v7/modules/Settings/Parameters/EditAjax.tpl
- layouts/v7/modules/Settings/Parameters/ListViewContents.tpl
- layouts/v7/modules/Settings/Parameters/ListViewRecordActions.tpl
- layouts/v7/modules/Settings/Parameters/resources/List.js
- layouts/v7/modules/Settings/Parameters/resources/Parameters.js
- modules/Migration/schema/741_to_742.php
- modules/Settings/Parameters/Parameters.php
- modules/Settings/Parameters/actions/DeleteAjax.php
- modules/Settings/Parameters/actions/SaveAjax.php
- modules/Settings/Parameters/models/ListView.php
- modules/Settings/Parameters/models/Module.php
- modules/Settings/Parameters/models/Record.php
- modules/Settings/Parameters/views/EditAjax.php
- modules/Settings/Parameters/views/List.php
- setup/scripts/03_Make_Parameters.php
- fix #1286 
1. システム変数モジュールの追加
1. 
1. エンプラ版からシステム変数モジュールの部分を取り込みました。
> thinkingreed-inc#1286 [要望]システム変数モジュールの追加

- modules/Users/views/Login.php
- fix #1293 
1. RSS取得処理にTimeoutが設定されていないため、該当Webサイトの障害に引きづられてログイン画面が表示できなかった
1. Timeoutを設定し、3秒を最大として表示するように修正
> rss取得処理で、Timeoutを設定するように修正

- modules/Vtiger/models/Record.php
- fix #1280 
-
1. 上部で検索ができない不具合
1. 意図しないModulesが取得され、ADBでエラーが発生していた
1. 配列が入っているケースは特殊なため、Stringだけを見るようにした。
※根本的に、この処理で特定のModuleを取得する処理が走っていない可能性があるため、後々修正する必要がありそうです。
そのため、この修正は暫定対応となります。
> ラベル検索のSQL生成に問題があったため対応

- layouts/v7/modules/Calendar/ListViewRecordActions.tpl
- fix #1337 
- #1118 
- #1337 
1. #1118 修正時の対応漏れ。原因は同一のため省略
1. #1118 参照
カレンダーモジュールの一覧検索
> #1337 カレンダーモジュールの一覧画面において、Enterキーによる検索が正常に動作していない問題の修正
